### ISSUE TITLE
Mix.Tasks.IexTest fails

### ISSUE THREAD

**Issue by bmwiedemann** [elixir-lang/elixir#10001]
Found this issue while filing #10000 

### Environment

* Elixir & Erlang/OTP versions (elixir --version): elixir-1.10.3 ; erlang-22.3
* Operating system: openSUSE-Tumbleweed 20200427

### Current behavior

A build of the elixir openSUSE package on a 3-core-VM failed a test

```
 + umask 022
 + cd /home/abuild/rpmbuild/BUILD
 + cd elixir-1.10.3
 + export LANG=en_US.UTF-8
 + LANG=en_US.UTF-8
 + make test
 ==> elixir (eunit)
   All 190 tests passed.
 
 ==> elixir (ex_unit)
 Excluding tags: [windows: true]
 
 .......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
 
 Finished in 57.3 seconds (33.6s on load, 23.7s on tests)
 1574 doctests, 3401 tests, 0 failures, 8 excluded
 
 Randomized with seed 782712
 ==> ex_unit (ex_unit)
 ....................................................................................................................................................................................................................................................................................................................................................................
 
 Finished in 6.0 seconds (3.0s on load, 2.9s on tests)
 42 doctests, 314 tests, 0 failures
 
 Randomized with seed 65345
 ==> logger (ex_unit)
 ............................................................................................................................
 
 Finished in 2.9 seconds (2.4s on load, 0.4s on tests)
 3 doctests, 121 tests, 0 failures
 
 Randomized with seed 953586
 ==> mix (ex_unit)
 Excluding tags: [windows: true]
 
 ..
 
   1) test raises error message about correct usage (Mix.Tasks.IexTest)
      test/mix/tasks/iex_test.exs:6
      ** (ArgumentError) argument error
      stacktrace:
        (stdlib 3.12) :ets.next(:ac_tab, {:loaded, :runtime_tools})
        (stdlib 3.12) ets.erl:775: :ets.do_filter/5
        test/test_helper.exs:52: anonymous fn/0 in MixTest.Case.__ex_unit_setup_0/1
        (ex_unit 1.10.3) lib/ex_unit/on_exit_handler.ex:142: ExUnit.OnExitHandler.exec_callback/1
        (ex_unit 1.10.3) lib/ex_unit/on_exit_handler.ex:128: ExUnit.OnExitHandler.on_exit_runner_loop/0
 
 ...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
 
 Finished in 171.2 seconds (7.6s on load, 163.5s on tests)
 9 doctests, 617 tests, 1 failure
 
 Randomized with seed 680726
```

A second build under similar conditions went fine, so there might be some race condition involved.

### Expected behavior

All tests should pass reliably.

**Comment by josevalim** [comment]
This is an issue upstream that will be addressed as part of this PR: https://github.com/erlang/otp/pull/2601

**Comment by josevalim** [comment]
Closing this for now, as I am tracking the issue upstream and I will reopen this in case upstream is not going to address it. Thanks!
