### ISSUE TITLE
mix release fails with :latency_μs present

### ISSUE THREAD

**Issue by kyleVsteger** [elixir-lang/elixir#10011]
### Environment
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.10.3 (compiled with Erlang/OTP 21)
```
* Operating system: 
`elixir:1.10.3-alpine`

### Current behavior
in our `prod.exs` we have this line:
```elixir
config :logger_json, :backend, metadata: [:client, :connection, :domain, :latency_μs, :node, :request_id]
```
when we run `mix release` this error occurs: 
```
* using config/releases.exs to configure the release at runtime
** (File.Error) could not write to file "/opt/app/_build/prod/rel/gateway/releases/0.1.0/sys.config": bad argument
    (elixir 1.10.3) lib/file.ex:1050: File.write!/3
    (mix 1.10.3) lib/mix/release.ex:405: Mix.Release.make_sys_config/3
    (mix 1.10.3) lib/mix/tasks/release.ex:1141: Mix.Tasks.Release.build_rel/2
    (mix 1.10.3) lib/mix/tasks/release.ex:1041: Mix.Tasks.Release.assemble/1
    (mix 1.10.3) lib/mix/tasks/release.ex:1017: Mix.Tasks.Release.run_steps/1
    (mix 1.10.3) lib/mix/task.ex:330: Mix.Task.run_task/3
    (elixir 1.10.3) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir 1.10.3) lib/enum.ex:783: Enum.each/2
```

when we remove the `:latency_μs` atom, everything works as expected

### Expected behavior

This is a valid atom, so there should not be an error when writing the file

**Comment by josevalim** [comment]
Closing in favor of #10012.
