### ISSUE TITLE
Unhelpful error message when you make a mistake in `with`

### ISSUE THREAD

**Issue by jjl** [elixir-lang/elixir#10051]
Here's some code I was just writing

```elixir
  defp chase_delete(user, users, []) do
    with :ok <- Activities.soft_delete_by(user, creator: users), # Not yet required but ok
         :ok <- Activities.soft_delete_by(user, context: users),
         :ok <- Blocks.soft_delete_by(user, creator: users),
         :ok <- Blocks.soft_delete_by(user, context: users) # <- there is a comma missing here
         :ok <- Flags.soft_delete_by(user, context: users),
         :ok <- Follows.soft_delete_by(user, creator: users),
         :ok <- Follows.soft_delete_by(user, context: users),
         :ok <- Likes.soft_delete_by(user, creator: users),
         :ok <- Likes.soft_delete_by(user, context: users),
         :ok <- Threads.Comments.soft_delete_by(user, creator: users),
         :ok <- Communities.give_away(users),
         :ok <- Collections.give_away(users),
         :ok <- Features.give_away(users),
         :ok <- Flags.give_away(users) do
      :ok
    end
  end
```

For which I get this error message, pointing 10 lines ahead of the real error:

```
❯ mix compile
Compiling 36 files (.ex)

== Compilation error in file lib/moodle_net/users/users.ex ==
** (SyntaxError) lib/moodle_net/users/users.ex:315: syntax error before: do
    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by josevalim** [comment]
@jjl yup. This has been reported in the past and although we try to improve error messages as much as we can, parsers are black boxes and sometimes it is really hard to get it to spit something else. This is unfortunately one of these cases. :(
