### ISSUE TITLE
Invalid syntax when using `mix format` on elixir-lang/elixir codebase

### ISSUE THREAD

**Issue by elbow-jason** [elixir-lang/elixir#10351]
I've never seen this error before, but I've also never encountered the `+++` in the wild.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
[I] ➜  elixir git:(master) elixir -v                                                                                                                     
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.2 (compiled with Erlang/OTP 21)
```

* Operating system: 
```
elixir git:(master) uname -a                                                                                                              254ms   
Darwin Jasons-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
```
### Current behavior

On master branch of elixir-lang/elixir (this repo) running `mix format` changes valid syntax to invalid syntax and raises an error.

```
[I] ➜  elixir git:(master) git log --oneline | head -n 1                                                                                         108ms   
6ad842a2e Add guard checks to Keyword.update/4 (#10348)
[I] ➜  elixir git:(master) mix format                                                                                                                    
warning: found "++" followed by "+", please use a space between "++" and the next "+"
  lib/elixir/test/elixir/macro_test.exs:654

warning: found "++" followed by "+", please use a space between "++" and the next "+"
  lib/elixir/test/elixir/macro_test.exs:654

mix format failed for file: lib/elixir/test/elixir/inspect_test.exs
** (SyntaxError) lib/elixir/test/elixir/inspect_test.exs:57: syntax error before: ')'
    (elixir 1.10.2) lib/code.ex:645: Code.format_string!/2
    (mix 1.10.2) lib/mix/tasks/format.ex:418: Mix.Tasks.Format.format_file/2
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

It changes this line: https://github.com/elixir-lang/elixir/blob/6ad842a2e64b0d84789c6e1c26a580a5b4c5e105/lib/elixir/test/elixir/macro_test.exs#L654

from: 

```elixir
assert Macro.to_string(quote(do: (x +++ y) +++ z)) == "(x +++ y) +++ z"
```

to:

```elixir
assert Macro.to_string(quote(do: (x ++ +y) ++ +z)) == "(x +++ y) +++ z"
```

### Expected behavior

Running `mix format` should not turn valid syntax to invalid syntax and raise an error.

**Comment by josevalim** [comment]
`+++` was added on v1.11. You are most likely running `mix format` from a previous Elixir version on Elixir master. You can run `bin/elixir bin/mix format` or `make format` instead.
