### ISSUE TITLE
Compile error when type checking

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir#10411]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.0 (compiled with Erlang/OTP 23
* Operating system: Mac OS X

### Current behavior

```
** (KeyError) key 8 not found in: %{0 => {:var, 0}, 1 => {:var, 1}, 4 => {:var, 3}, 5 => {:var, 4}, 11 => {:var, 2}}
        :erlang.map_get(8, %{0 => {:var, 0}, 1 => {:var, 1}, 4 => {:var, 3}, 5 => {:var, 4}, 11 => {:var, 2}})
        (elixir 1.11.0) lib/module/types/unify.ex:318: Module.Types.Unify.get_var!/2
        (elixir 1.11.0) lib/module/types/expr.ex:112: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:83: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:382: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:83: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/expr.ex:297: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/expr.ex:136: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:195: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types.ex:63: Module.Types.warnings_from_clause/6
        (elixir 1.11.0) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5
        (elixir 1.11.0) lib/enum.ex:3421: Enum.flat_map_list/2
        (elixir 1.11.0) lib/enum.ex:3422: Enum.flat_map_list/2
        (elixir 1.11.0) lib/module/parallel_checker.ex:104: Module.ParallelChecker.check_module/2
        (elixir 1.11.0) lib/module/parallel_checker.ex:300: anonymous fn/5 in Module.ParallelChecker.spawn_checkers/1
```

```
** (EXIT from #PID<0.109.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for Connect.Contacts.Contact.at_least_one_match/2

def(at_least_one_match(query, map)) do
  case(Enum.any?(map, fn {_, value} -> :erlang.not(:erlang.orelse(:erlang."=:="(value, nil), :erlang."=:="(value, ""))) end)) do
    x when :erlang.orelse(:erlang."=:="(x, false), :erlang."=:="(x, nil)) ->
      :erlang.error(RuntimeError.exception("Can't match completly empty"))
    _ ->
      nil
  end
  condition = for({field, value} when :erlang.not(:erlang.==(value, nil)) <- map, do: (false -> %Ecto.Query.DynamicExpr{fun: fn query ->
    _ = query = Ecto.Queryable.to_query(query)
    {{:==, [], [{{:., [], [{:&, [], [Ecto.Query.Builder.count_alias!(query, :contact)]}, Ecto.Query.Builder.field!(field)]}, [], []}, {:^, [], [0]}]}, [{Ecto.Query.Builder.not_nil!(value), {Ecto.Query.Builder.count_alias!(query, :contact), field}}], []}
  end, binding: [contact: {:contact, [line: 163], nil}], file: "/Users/benni/Work/madeit/Projekte/connect/lib/connect/contacts/contact.ex", line: 163}; acc -> %Ecto.Query.DynamicExpr{fun: fn query ->
    _ = query = Ecto.Queryable.to_query(query)
    {{:or, [], [{:^, [], [0]}, {:==, [], [{{:., [], [{:&, [], [Ecto.Query.Builder.count_alias!(query, :contact)]}, Ecto.Query.Builder.field!(field)]}, [], []}, {:^, [], [1]}]}]}, [{Ecto.Query.Builder.not_nil!(acc), :boolean}, {value, {Ecto.Query.Builder.count_alias!(query, :contact), field}}], []}
  end, binding: [contact: {:contact, [line: 164], nil}], file: "/Users/benni/Work/madeit/Projekte/connect/lib/connect/contacts/contact.ex", line: 164}), reduce: false)
  Ecto.Query.Builder.Filter.filter!(:where, :and, Ecto.Query.Builder.From.apply(query, 0, nil, nil, []), condition, 0, "/Users/benni/Work/madeit/Projekte/connect/lib/connect/contacts/contact.ex", 167)
end

Please report this bug: https://github.com/elixir-lang/elixir/issues
```

The function in question:
```
def at_least_one_match(query, map) do
    unless Enum.any?(map, fn {_, value} -> value not in [nil, ""] end) do
      raise "Can't match completly empty"
    end

    condition =
      for {field, value} when not is_nil(value) <- map, reduce: false do
        false -> dynamic([contact: contact], field(contact, ^field) == ^value)
        acc -> dynamic([contact: contact], ^acc or field(contact, ^field) == ^value)
      end

    from query, where: ^condition
  end
```

### Expected behavior

Should compile.

**Comment by LostKobrakai** [comment]
Seems toe be caused by the `for` + `reduce`, as the following compiles fine:

```
  def at_least_one_match(query, map) do
    unless Enum.any?(map, fn {_, value} -> value not in [nil, ""] end) do
      raise "Can't match completly empty"
    end

    condition =
      for {field, value} when not is_nil(value) <- map do
        dynamic([contact: contact], field(contact, ^field) == ^value)
      end
      |> Enum.reduce(fn a, b -> dynamic(^a or ^b) end)

    from query, where: ^condition
  end
```

**Comment by anronin** [comment]
I can confirm that and here is even simpler example
```elixir
def test do
  for i <- [1,2,3], reduce: nil do
    _ -> i
  end
end
```
and compiler error:
```
Compiling 1 file (.ex)
** (EXIT from #PID<0.109.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for TypesErrorTest.hello/0

def(hello()) do
  for(i <- [1, 2, 3], do: (_ -> i), reduce: nil)
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (KeyError) key :version not found in: [line: 17]
        (elixir 1.11.0) lib/keyword.ex:420: Keyword.fetch!/2
        (elixir 1.11.0) lib/module/types/unify.ex:318: Module.Types.Unify.get_var!/2
        (elixir 1.11.0) lib/module/types/expr.ex:112: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:83: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:374: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
```
