### ISSUE TITLE
Autocomplete of preloaded modules fails in releases

### ISSUE THREAD

**Issue by fhunleth** [elixir-lang/elixir#10437]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```
$ elixir --version
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [hipe]

Elixir 1.11.1 (compiled with Erlang/OTP 23)
```

* Operating system: 

Linux

### Current behavior

Here's a script to reproduce (at the IEx prompt, I typed `:zlib.<tab>`):

```sh
$ mix new autocomplete_test
$ cd autocomplete_test
$ mix release
$ _build/dev/rel/autocomplete_test/bin/autocomplete_test start_iex
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [hipe]

Interactive Elixir (1.11.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(autocomplete_test@sprint)1> :zlib.*** ERROR: Shell process terminated! (^G to start new job) ***

10:17:22.644 [error] Process #PID<0.589.0> on node :autocomplete_test@sprint raised an exception
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir 1.11.1) lib/io.ex:589: IO.chardata_to_string({:error, :bad_name})
    (elixir 1.11.1) lib/path.ex:520: Path.join/2
    (elixir 1.11.1) lib/path.ex:491: Path.join/1
    (elixir 1.11.1) lib/code.ex:1376: Code.fetch_docs/1
    (iex 1.11.1) lib/iex/autocomplete.ex:483: IEx.Autocomplete.get_docs/2
    (iex 1.11.1) lib/iex/autocomplete.ex:437: IEx.Autocomplete.get_module_funs/1
    (iex 1.11.1) lib/iex/autocomplete.ex:260: IEx.Autocomplete.expand_require/2
    (kernel 7.1) group.erl:596: :group.get_line1/5
```

The exception is due to the `:code.lib_dir(:erts)` call at https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/code.ex#L1376. In the release, it returns:

```
iex(autocomplete_test@sprint)1> :code.lib_dir(:erts)                                                                                       
{:error, :bad_name}
```

This is due to the `:erts` app not being in the release. 

Adding `:erts` to `:extra_applications` fixes the issue. There are, of course, other fixes, but I wasn't sure what was desired or whether there was more to this issue.

**Comment by josevalim** [comment]
Thanks @fhunleth! This issue also happens in Erlang, so I will open up an issue there and see what is the most appropriate solution.

**Comment by josevalim** [comment]
For now, I have improved it so it doesn't choke.

**Comment by fhunleth** [comment]
Thanks for the super fast fix on a weekend and for sending up to the OTP team!
