### ISSUE TITLE
Crash in Mix.Tasks.Xref.calls() during mix test --cover

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#10502]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Operating system: macOS 10.15.7

### Current behavior

Given test module `test/repro.exs`
```
defmodule ReproTest do
  use ExUnit.Case
  test "crashes" do
    refute [] == Mix.Tasks.Xref.calls()
  end
end
```

```
mix test test/repro.exs --cover
```

```
  1) test crashes (ReproTest)
     test/repro.exs:3
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for :cover_compiled of type Atom. This protocol is implemented for the following type(s): HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
     code: refute [] == Mix.Tasks.Xref.calls()
     stacktrace:
       (elixir 1.11.2) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir 1.11.2) lib/enum.ex:141: Enumerable.reduce/3
       (elixir 1.11.2) lib/enum.ex:3461: Enum.reduce/3
       (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
       (mix 1.11.2) lib/mix/tasks/xref.ex:243: Mix.Tasks.Xref.calls/1
       test/repro.exs:4: (test)
```

### Expected behavior

Test should pass with `--cover`

**Comment by josevalim** [comment]
@lukaszsamson I will push a fix for the error but note the test will fail because if the modules are cover compiled, we can't read their contents. :)

**Comment by lukaszsamson** [comment]
Sure, that's just a minimal repro. The real test does some useful work.
