### ISSUE TITLE
Macro.to_string/1 generates invalid code

### ISSUE THREAD

**Issue by SteffenDE** [elixir-lang/elixir#10599]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): see below
* Operating system: macOS 11.1

### Current behavior

```bash
~> iex
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.11.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> EEx.compile_string(~s[<%= <<(if true, do: "1", else: "0")::binary>> %>]) |> Code.eval_quoted()
{"1", [{{:arg0, EEx.Engine}, "1"}]}
iex(2)> EEx.compile_string(~s[<%= <<(if true, do: "1", else: "0")::binary>> %>]) |> Macro.to_string() |> Code.format_string!()
** (SyntaxError) nofile:6:14: unexpected token: >>. The "do" at line 2 is missing terminator "end"
    (elixir 1.11.2) lib/code.ex:654: Code.format_string!/2
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (iex 1.11.2) lib/iex/evaluator.ex:261: IEx.Evaluator.handle_eval/5
    (iex 1.11.2) lib/iex/evaluator.ex:242: IEx.Evaluator.do_eval/3
    (iex 1.11.2) lib/iex/evaluator.ex:220: IEx.Evaluator.eval/3
```

### Expected behavior

I guess the code should be formatted like this:
```
arg0 =
  String.Chars.to_string(
    <<if(true) do
        "1"
      else
        "0"
      end::binary>>
  )

<<arg0::binary>>
```

This code also fails when directly using it in Elixir. Putting a space after the `end` makes this work:
```
iex(4)> arg0 =
...(4)>   String.Chars.to_string(
...(4)>     <<if(true) do
...(4)>         "1"
...(4)>       else
...(4)>         "0"
...(4)>       end ::binary>>
...(4)>   )
"1"
iex(5)>
nil
iex(6)> <<arg0::binary>>
"1"
```

**Comment by wojtekmach** [comment]
> This code also fails when directly using it in Elixir.

yeah, this is the culprit, it doesn't seem to be necessarily related to the formatter. I was able to narrow it down to the following:

```elixir
iex> quoted = quote do to_string(<<(if true, do: "1", else: "0")::binary>>) end

iex> Code.eval_quoted(quoted)
{"1", []}

iex> quoted |> Macro.to_string() |> Code.eval_string()
** (SyntaxError) nofile:5:12: unexpected token: >>. The "do" at line 1 is missing terminator "end"
    (elixir 1.12.0-dev) lib/code.ex:340: Code.eval_string_with_error_handling/3
    (stdlib 3.14) erl_eval.erl:677: :erl_eval.do_apply/6
    (iex 1.12.0-dev) lib/iex/evaluator.ex:276: IEx.Evaluator.handle_eval/3
    (iex 1.12.0-dev) lib/iex/evaluator.ex:252: IEx.Evaluator.do_eval/3
    (iex 1.12.0-dev) lib/iex/evaluator.ex:241: IEx.Evaluator.eval/3
```

seems to be a problem with `Macro.to_string/2`.

**Comment by Eiji7** [comment]
Actual:
```elixir
iex> quoted = quote do to_string(<<(if true, do: "1", else: "0")::binary>>) end
iex> quoted |> Macro.to_string() |> IO.puts
<<if(true) do
  "1"
else
  "0"
end::binary>>
```
Expected:
```elixir
iex> quoted = quote do to_string(<<(if true, do: "1", else: "0")::binary>>) end
iex> quoted |> Macro.to_string() |> IO.puts
<<(if(true) do
  "1"
else
  "0"
end)::binary>>
```
Quoted expression:
```elixir
{:<<>>, [],
 [
   {:"::", [],
    [
      {:if, [context: Elixir, import: Kernel], [true, [do: "1", else: "0"]]},
      {:binary, [], Elixir}
    ]}
 ]}
```
Problem:
`Macro.to_string/1` for `::` bitstring (`<<>>`) operator should wrap first argument (here: `{:if, [context: Elixir, import: Kernel], [true, [do: "1", else: "0"]]}`) into parentheses in case it contains value which is not `binary`, `float`,`integer` and variable.

Expected results for other cases:
```elixir
iex> quote(do: <<("1")::binary>>) |> Macro.to_string() |> IO.puts
<<"1"::binary>>

iex> func = fn -> "1" end
iex> quote(do: <<(func.())::binary>>) |> Macro.to_string() |> IO.puts
<<(func.())::binary>>

iex> data = "1"
iex> quote(do: <<(data)::binary>>) |> Macro.to_string() |> IO.puts
<<data::binary>>
```
