### ISSUE TITLE
** (Module.Types.Error) found error while checking types

### ISSUE THREAD

**Issue by TBK145** [elixir-lang/elixir#10613]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
$ elixir --version
Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
$ kerl active
The current active installation is:
/home/thijs/.kerl/installations/23.2.1
```
* Operating system:
```
$ uname -srvmo
Linux 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux
```

### Current behavior

I was trying to construct some complex guard, and while compiling stumbled upon a error that told me to post it here :). I was able to reproduce it with this example:
```
defmodule Foo do
  def handle_info(%{payload: payload}, state)
      when is_map_key(payload, state.a <> state.b) do
    {:ok, state}
  end
end
```
Tyring to compile it returns this error:
```
$ elixirc foo.ex
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for Foo.handle_info/2

def(handle_info(%{payload: payload}, state) when :erlang.is_map_key(<<state.a::binary(), state.b::binary()>>, payload)) do
  {:ok, state}
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (FunctionClauseError) no function clause matching in Module.Types.Pattern.of_pattern/3
        (elixir 1.11.2) lib/module/types/pattern.ex:22: Module.Types.Pattern.of_pattern({{:., [line: 3], [{:state, [version: 1, line: 3], nil}, :a]}, [no_parens: true, line: 3], []}, %{context: :pattern, last_expr: {:<<>>, [line: 3], [{:"::", [line: 3], [{{:., [line: 3], [{:state, [version: 1, line: 3], nil}, :a]}, [no_parens: true, line: 3], []}, {:binary, [], []}]}, {:..., [], Module.Types.Of}]}, trace: true, type_guards_enabled?: false, unify_stack: []}, %{cache: {#PID<0.100.0>, #Reference<0.4115884105.668073985.192513>}, counter: 2, file: "/home/thijs/Documents/grid/foo.ex", function: {:handle_info, 2}, guard_sources: %{}, module: Foo, no_warn_undefined: [], traces: %{0 => [], 1 => []}, types: %{0 => :unbound, 1 => :unbound}, types_to_vars: %{0 => {:payload, [version: 0, line: 2], nil}, 1 => {:state, [version: 1, line: 2], nil}}, vars: %{0 => {:var, 0}, 1 => {:var, 1}}, warnings: []})
        (elixir 1.11.2) lib/module/types/of.ex:165: Module.Types.Of.binary_segment/4
        (elixir 1.11.2) lib/module/types/of.ex:128: Module.Types.Of.binary/4
        (elixir 1.11.2) lib/module/types/pattern.ex:49: Module.Types.Pattern.of_pattern/3
        (elixir 1.11.2) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.2) lib/module/types/pattern.ex:363: Module.Types.Pattern.of_guard/3
        (elixir 1.11.2) lib/module/types/pattern.ex:14: Module.Types.Pattern.of_head/4
        (elixir 1.11.2) lib/module/types.ex:62: Module.Types.warnings_from_clause/6
```

### Expected behavior

I'm not sure if this is even valid code, but I've tried a few variations, with different outcomes:

```
defmodule Foo do
  def handle_info(%{payload: payload}, %{a: a, b: b} = state)
      when is_map_key(payload, a <> b) do
    {:ok, state}
  end
end
```
This compiles without issue, and runs fine:
```
$ iex foo.ex
iex(1)> Foo.handle_info(%{payload: %{"ab" => true}}, %{a: "a", b: "b"})
{:ok, %{a: "a", b: "b"}}
```

This returns the same error as the initial code:
```
defmodule Foo do
  def handle_info(%{payload: payload}, state)
      when is_map_key(payload, :erlang.map_get(:a, state) <> :erlang.map_get(:b, state)) do
    {:ok, state}
  end
en
```

**Comment by eksperimental** [comment]
> I'm not sure if this is even valid code, but I've tried a few variations, with different outcomes:

the guard in your first example is wrong as you cannot use <>/2 when the left side is not a literal.


From the docs:
> The <>/2 operator can also be used in pattern matching (and guard clauses) as long as the left argument is a literal binary:
> 
> "foo" <> x = "foobar"
> 
> x
> "bar"
> 
> x <> "bar" = "foobar" would have resulted in a CompileError exception.

I guess a CompileError should have been raised

**Comment by josevalim** [comment]
The usage is valid. Patterns != guards.

**Comment by v0idpwn** [comment]
Tried reproducing on master with 23.1.1 and didn't happen.

Don't know if did something wrong: https://gist.github.com/v0idpwn/8bc3613dd662fbf0f26e2b7fa51d16c7

**Comment by ericmj** [comment]
@v0idpwn You need to go through the ParallelCompiler to use the group pass where this checking happens. You can either use `Kernel.ParallelCompiler` directly or you can create a test project with `mix new` and compile using `mix compile` which will also invoke the group pass.
