### ISSUE TITLE
ExUnit generates an exception on a pattern match with assert

### ISSUE THREAD

**Issue by kpanic** [elixir-lang/elixir#10808]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```bash
$ elixir --version
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.4 (compiled with Erlang/OTP 23)
```

* Operating system: 

Linux

### Current behavior

```elixir
defmodule MatchBubuTest do
  use ExUnit.Case
  doctest MatchBubu

  test "greets the world" do
    assert [%_{payload: %{"hello" => "world"}}] = []
  end
end
```

if I run this test, I get back this not descriptive exception:

```elixir
19:53:08.244 [error] GenServer #PID<0.143.0> terminating
** (FunctionClauseError) no function clause matching in Code.Identifier.inspect_as_atom/1
    (elixir 1.11.4) lib/code/identifier.ex:135: Code.Identifier.inspect_as_atom({:_, [line: 6], nil})
    (ex_unit 1.11.4) lib/ex_unit/diff.ex:919: ExUnit.Diff.safe_to_algebra/2
    (ex_unit 1.11.4) lib/ex_unit/diff.ex:1022: ExUnit.Diff.wrap_on_diff/3
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ex_unit 1.11.4) lib/ex_unit/diff.ex:986: ExUnit.Diff.container_to_algebra/5
    (ex_unit 1.11.4) lib/ex_unit/formatter.ex:407: ExUnit.Formatter.format_sides/6
    (ex_unit 1.11.4) lib/ex_unit/formatter.ex:395: ExUnit.Formatter.format_context/4
    (ex_unit 1.11.4) lib/ex_unit/formatter.ex:160: ExUnit.Formatter.format_exception/6
    (ex_unit 1.11.4) lib/ex_unit/formatter.ex:131: anonymous fn/7 in ExUnit.Formatter.format_test_failure/5
    (elixir 1.11.4) lib/enum.ex:1508: anonymous fn/2 in Enum.map_join/3
    (elixir 1.11.4) lib/enum.ex:3449: Enum.map_intersperse_list/3
    (elixir 1.11.4) lib/enum.ex:1508: Enum.map_join/3
    (ex_unit 1.11.4) lib/ex_unit/formatter.ex:130: ExUnit.Formatter.format_test_failure/5
    (ex_unit 1.11.4) lib/ex_unit/cli_formatter.ex:99: ExUnit.CLIFormatter.handle_cast/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:test_finished, %ExUnit.Test{case: MatchBubuTest, logs: "", module: MatchBubuTest, name: :"test greets the world", state: {:failed, [{:error, %ExUnit.AssertionError{args: :ex_unit_no_meaningful_value, context: {:match, []}, doctest: :ex_unit_no_meaningful_value, expr: {:assert, [line: 6], [{:=, [line: 6], [[{:%, [line: 6], [{:_, [line: 6], nil}, {:%{}, [line: 6], [payload: {:%{}, [line: 6], [{"hello", "world"}]}]}]}], []]}]}, left: [{:%, [line: 6], [{:_, [line: 6], nil}, {:%{}, [line: 6], [payload: {:%{}, [line: 6], [{"hello", "world"}]}]}]}], message: "match (=) failed", right: []}, [{MatchBubuTest, :"test greets the world", 1, [file: 'test/match_bubu_test.exs', line: 6]}]}]}, tags: %{async: false, case: MatchBubuTest, describe: nil, describe_line: nil, file: "/tmp/match_bubu/test/match_bubu_test.exs", line: 5, module: MatchBubuTest, registered: %{}, test: :"test greets the world", test_type: :test}, time: 3797}}}
State: %{colors: [enabled: true, diff_delete: :red, diff_delete_whitespace: "\e[48;5;88m", diff_insert: :green, diff_insert_whitespace: "\e[48;5;28m"], excluded_counter: 0, failure_counter: 0, invalid_counter: 0, seed: 150800, skipped_counter: 0, slowest: 0, test_counter: %{doctest: 1}, test_timings: [%ExUnit.Test{case: MatchBubuTest, logs: "", module: MatchBubuTest, name: :"doctest MatchBubu.hello/0 (1)", state: nil, tags: %{async: false, case: MatchBubuTest, describe: nil, describe_line: nil, file: "/tmp/match_bubu/test/match_bubu_test.exs", line: 3, module: MatchBubuTest, registered: %{}, test: :"doctest MatchBubu.hello/0 (1)", test_type: :doctest}, time: 1}], trace: false, width: 106}
```

repeated 3 times (I guess the standard restart times of the GenServer)

### Expected behavior

We should get a meaningful error about the failing pattern match

**Comment by kpanic** [comment]
I'll give it a try to fix it. 😉

**Comment by kpanic** [comment]
Closing issue because #10811 was merged
