### ISSUE TITLE
kw list parsing error (releases.exs) 

### ISSUE THREAD

**Issue by bryanhuntesl** [elixir-lang/elixir#11065]
### Environment

elixir 1.11.2-otp-23
erlang 23.1.4

### Current behaviour

'releases.exs' looks like this (truncated, original on request): 

```
import Config

# Configure BetEpsStore using Environment variables
case System.get_env("STORAGE_ADAPTER") do
  "COCKROACH" ->
    config :bet_eps_store, :storage_adapter, Store.Storage.Cockroach
    config :bet_eps_store, Store.Storage.Cockroach.Repo,
      ssl:
        case System.get_env("COCKROACH_SSL") do
           "true" -> true
           _ -> "false"
         end,
      ssl_cert: System.get_env("COCKROACH_SSL_CERT"),
      show_sensitive_data_on_connection_error: false
  _ ->
    config :bet_eps_store, Store.Storage.Filesystem,
      dir_path: System.fetch_env!("OUTPUT_DIR")
end
```

Generates the following error :

```
** (SyntaxError) config/releases.exs:46:10: syntax error before: ','
    (elixir 1.11.2) lib/code.ex:654: Code.format_string!/2
    (mix 1.11.2) lib/mix/tasks/format.ex:418: Mix.Tasks.Format.format_file/2
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Add the following parenthesis to the 'COCKROACH_SSL' block and the error no longer manifests : 

```
 (case System.get_env("COCKROACH_SSL") do
           "true" -> true
           _ -> "false"
         end),
```

**Comment by bryanhuntesl** [comment]
haha you're quick enough it's almost like you wrote the language. thanks @josevalim

**Comment by Eiji7** [comment]
Parenthesis are not required if you wrap `Keyword`  using <kbd>[</kbd> and <kbd>]</kbd> characters it would work as expected.

Simple example of `raise`:
```elixir
IO.inspect :example,
  sample: case true do
    true -> true
    _ -> false
  end,
  something: true
```

Example solution:
```elixir
IO.inspect :example, [
  sample: case true do
    true -> true
    _ -> false
  end,
  something: true
]
```
