### ISSUE TITLE
ExUnit fails on Ecto exception error

### ISSUE THREAD

**Issue by Apelsinka223** [elixir-lang/elixir#11108]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12.2
* Operating system: macOS 10.15.7

I made an error in test case:
```
    test "failing ExUnit" do

      # here supposed to be ^ in front of the id value
      assert [] = MyApp.Accounts.User |> where(id: "3341d7dd-ba97-4f73-82c9-149a7a6db008") |> Repo.all()
    end
```
And whole testing process failed with the error:

### Current behavior
 ```
15:05:24.765 [error] GenServer #PID<0.543.0> terminating
** (ArgumentError) argument error
    (stdlib 3.15.1) :io.put_chars(:standard_io, :unicode, [<<32, 32, 49, 41, 32, 116, 101, 115, 116, 32, 117, 112, 100, 97, 116, 101, 95, 99, 104, 97, 110, 110, 101, 108, 47, 50, 32, 102, 97, 105, 108, 105, 110, 103, 32, 69, 120, 85, 110, 105, 116, 32, 40, 67, 97, 116, 101, 110, 97, ...>>, 10])
    (ex_unit 1.12.2) lib/ex_unit/cli_formatter.ex:116: ExUnit.CLIFormatter.handle_cast/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:test_finished, %ExUnit.Test{case: MyApp.Test, logs: "", module: MyApp.Test, name: :"test ufailing ExUnit", state: {:failed, [{:error, %Postgrex.Error{connection_id: 7947, message: nil, postgres: %{code: :character_not_in_repertoire, file: "mbutils.c", line: "1597", message: "invalid byte sequence for encoding \"UTF8\": 0xed 0xcf 0xde", pg_code: "22021", routine: "report_invalid_encoding", severity: "ERROR", unknown: "ERROR"}, query: <<83, 69, 76, 69, 67, 84, 32, 117, 48, 46, 34, 105, 100, 34, 44, 32, 117, 48, 46, 34, 101, 110, 97, 98, 108, 101, 100, 34, 44, 32, 117, 48, ...>>}, [{Ecto.Adapters.SQL, :raise_sql_call_error, 1, [file: 'lib/ecto/adapters/sql.ex', line: 760]}, {Ecto.Adapters.SQL, :execute, 5, [file: 'lib/ecto/adapters/sql.ex', line: 693]}, {Ecto.Repo.Queryable, :execute, 4, [file: 'lib/ecto/repo/queryable.ex', line: 224]}, {Ecto.Repo.Queryable, :all, 3, [file: 'lib/ecto/repo/queryable.ex', line: 19]}, {MyApp.Test, :"test failing ExUnit", 1, [file: 'test/test.exs', line: 162]}]}]}, tags: %{async: true, case: MyApp.Test, describe: "test", describe_line: 126, file: "/Users/anastasia/my_app/test/test.exs", line: 160, module: MyApp.Test, registered: %{}, test: :"test failing ExUnit", test_type: :test, user: %MyApp.Accounts.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, created_at: ~U[2021-07-08 12:05:24Z], updated_at: ~U[2021-07-08 12:05:24Z]}}, time: 32434}}}
15:05:24.784 [error] Task #PID<0.536.0> started from #PID<0.93.0> terminating
** (stop) exited in: GenServer.stop(#PID<0.543.0>, :normal, :infinity)
    ** (EXIT) exited in: :sys.terminate(#PID<0.543.0>, :normal, :infinity)
        ** (EXIT) an exception was raised:
            ** (ArgumentError) argument error
                (stdlib 3.15.1) :io.put_chars(:standard_io, :unicode, [<<32, 32, 49, 41, 32, 116, 101, 115, 116, 32, 117, 112, 100, 97, 116, 101, 95, 99, 104, 97, 110, 110, 101, 108, 47, 50, 32, 102, 97, 105, 108, 105, 110, 103, 32, 69, 120, 85, 110, 105, 116, 32, 40, 67, 97, 116, 101, 110, 97, ...>>, 10])
                (ex_unit 1.12.2) lib/ex_unit/cli_formatter.ex:116: ExUnit.CLIFormatter.handle_cast/2
                (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
                (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
                (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.12.2) lib/gen_server.ex:982: GenServer.stop/3
    (ex_unit 1.12.2) lib/ex_unit/event_manager.ex:22: anonymous fn/2 in ExUnit.EventManager.stop/1
    (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_unit 1.12.2) lib/ex_unit/event_manager.ex:21: ExUnit.EventManager.stop/1
    (ex_unit 1.12.2) lib/ex_unit/runner.ex:62: ExUnit.Runner.run_with_trap/2
    (ex_unit 1.12.2) lib/ex_unit/runner.ex:31: ExUnit.Runner.run/2
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<0.95028733/0 in ExUnit.async_run/0>
    Args: []
** (EXIT from #PID<0.93.0>) exited in: GenServer.stop(#PID<0.543.0>, :normal, :infinity)
    ** (EXIT) exited in: :sys.terminate(#PID<0.543.0>, :normal, :infinity)
        ** (EXIT) an exception was raised:
            ** (ArgumentError) argument error
                (stdlib 3.15.1) :io.put_chars(:standard_io, :unicode, [<<32, 32, 49, 41, 32, 116, 101, 115, 116, 32, 117, 112, 100, 97, 116, 101, 95, 99, 104, 97, 110, 110, 101, 108, 47, 50, 32, 102, 97, 105, 108, 105, 110, 103, 32, 69, 120, 85, 110, 105, 116, 32, 40, 67, 97, 116, 101, 110, 97, ...>>, 10])
                (ex_unit 1.12.2) lib/ex_unit/cli_formatter.ex:116: ExUnit.CLIFormatter.handle_cast/2
                (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
                (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
                (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```
### Expected behavior
I expected testing process to handle exception and show human readable error.
```
 1) test ...
     test/my_app/test.exs:142
     ** (ArgumentError) argument error
     ...
     stacktrace:
       test/test.exs:152: (test)
```

Perhaps this is also Ecto issue, the way it handle errors, but it seemed to me that ExUnit should handle it in any way.

**Comment by josevalim** [comment]
Hi @Apelsinka223, thank you for the report. I have tried to reproduce this issue but failed. Can you please provide a small application that reproduces it? Thanks!

**Comment by al2o3cr** [comment]
@Apelsinka223 
The test fails with an error from Postgres; something is trying to pass a non-UTF8 binary as a string in a query, producing the error `message: "invalid byte sequence for encoding \"UTF8\": 0xed 0xcf 0xde"`.

But that's not the whole problem.

Manually decoding the binary in the following exceptions gives me `1) test update_channel/2 failing ExUnit (Catena`. ExUnit is _trying_ to report a human-readable error and something it's putting into the _log message_ isn't UTF-8! This is causing the `ArgumentError` from `:io.put_chars`.

To solve this, you'll need to figure out what's producing the bad Postgres query (the error message only has a fragment, `SELECT u0."id", u0."enabled", u0`).

**Comment by josevalim** [comment]
I will be closing this for now. If someone can isolate and reproduce the issue, please drop a comment or open up a new one. Thanks!
