### ISSUE TITLE
Process exit while type checking

### ISSUE THREAD

**Issue by sabiwara** [elixir-lang/elixir#11189]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.12.1 (compiled with Erlang/OTP 24)`
* Operating system:  `Ubuntu 18.04.5`

### Current behavior

The following snippet (which makes absolutely no sense, sorry!)

```elixir
defmodule Foo do
  defmacro foo(__CALLER__) do
  end
end
```

generates the following error message:

```
** (EXIT from #PID<0.223.0>) shell process exited with reason: an exception was raised:
    ** (Module.Types.Error) found error while checking types for Foo.foo/1

defmacro(foo(__CALLER__)) do
  nil
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (KeyError) key :version not found in: [line: 48]
        (elixir 1.12.1) lib/keyword.ex:420: Keyword.fetch!/2
        (elixir 1.12.1) lib/module/types/unify.ex:352: Module.Types.Unify.new_var/2
        (elixir 1.12.1) lib/module/types/pattern.ex:39: Module.Types.Pattern.of_pattern/3
        (elixir 1.12.1) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.12.1) lib/module/types/pattern.ex:12: Module.Types.Pattern.of_head/4
        (elixir 1.12.1) lib/module/types.ex:62: Module.Types.warnings_from_clause/6
        (elixir 1.12.1) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5
        (elixir 1.12.1) lib/enum.ex:3865: Enum.flat_map_list/2
```

Since it was asked, I reported the issue even if the code didn't make sense in the first place and was just a silly mistake on my end :sweat_smile:.

### Expected behavior

A more explicit compile error explaining what went wrong (cannot use `__CALLER__` in arguments)

**Comment by josevalim** [comment]
Yes, even if the code is non-sense, the compiler should always fail cleanly. :) Thanks for the report!
