### ISSUE TITLE
`Mix.install/2` gives advice that is not applicable after a `deps.compile` failure

### ISSUE THREAD

**Issue by thbar** [elixir-lang/elixir#11214]
### Environment

* Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
* Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Operating system: Mac OS X 11.4

### Current behavior

I have been trying out the `Mix.install/2`-based scripts at https://github.com/wojtekmach/mix_install_examples on a new machine (one without Rust/Cargo installed at time of initial test, and without glfw3 as well).

Running `elixir erqwest.exs` on a machine without cargo installed gives:

```
elixir erqwest.exs 
cargo build --release
make: cargo: No such file or directory
make: *** [compile] Error 1
===> Hook for compile failed!

** (Mix.Error) Could not compile dependency :erqwest, "/Users/thbar/.asdf/installs/elixir/1.12.2-otp-24/.mix/rebar3 bare compile --paths /Users/thbar/Library/Caches/mix/installs/elixir-1.12.2-erts-12.0.3/f021d3bceb98687af521289d70c481ef/_build/dev/lib/*/ebin" command failed. 
You can recompile this dependency with "mix deps.compile erqwest", update it with "mix deps.update erqwest" or clean it with "mix deps.clean erqwest"
    (mix 1.12.2) lib/mix.ex:454: Mix.raise/2
    (elixir 1.12.2) lib/file.ex:1560: File.cd!/2
    (mix 1.12.2) lib/mix/tasks/deps.compile.ex:285: Mix.Tasks.Deps.Compile.do_command/5
    (mix 1.12.2) lib/mix/tasks/deps.compile.ex:98: anonymous fn/4 in Mix.Tasks.Deps.Compile.compile/2
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.12.2) lib/mix/tasks/deps.compile.ex:79: Mix.Tasks.Deps.Compile.compile/2
    (mix 1.12.2) lib/mix/tasks/deps.loadpaths.ex:89: Mix.Tasks.Deps.Loadpaths.deps_check/2
    (mix 1.12.2) lib/mix/tasks/deps.loadpaths.ex:28: Mix.Tasks.Deps.Loadpaths.run/1
```

If one follows the advice provided, it will not work (as expected, given there is no real mix project there):

```
❯ mix deps.compile erqwest
** (Mix) Could not find a Mix.Project, please ensure you are running Mix in a directory with a mix.exs file
```

The same issue will appear (even more easily probably) with `elixir scenic.exs`, when the dependencies mentioned at top of the script are not provided:

```
could not compile dependency :scenic_driver_glfw, "mix compile" failed. 
You can recompile this dependency with "mix deps.compile scenic_driver_glfw", 
update it with "mix deps.update scenic_driver_glfw" or clean it with "mix deps.clean scenic_driver_glfw"
** (Mix.Error) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
```

### Expected behavior

I would have expected an advice that is applicable (maybe: use `force: true`, or something better on the command line is already available?).

(unless I have missed something!)

**Comment by thbar** [comment]
Thanks @josevalim!
