### ISSUE TITLE
One time error while checking types.

### ISSUE THREAD

**Issue by kaaboaye** [elixir-lang/elixir#11547]
I've run `recompile` after git branch checkout and this happened. After `iex -S mix phx.server` everything works fine.

I had VScode with ElixirLS v0.9.0 running in the background.

```
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: invalid options

    (stdlib 3.16.1) :ets.new(Mix.Compilers.ApplicationTracer, [:public, :named_table, :set, {:read_concurrency, true}])
    (mix 1.12.3) lib/mix/compilers/application_tracer.ex:180: Mix.Compilers.ApplicationTracer.build_manifest/2
    (mix 1.12.3) lib/mix/compilers/application_tracer.ex:25: Mix.Compilers.ApplicationTracer.init/1
    (mix 1.12.3) lib/mix/compilers/elixir.ex:81: Mix.Compilers.Elixir.compile/6
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (phoenix 1.6.4) lib/phoenix/code_reloader/server.ex:249: Phoenix.CodeReloader.Server.mix_compile/2
    (phoenix 1.6.4) lib/phoenix/code_reloader/server.ex:178: Phoenix.CodeReloader.Server.mix_compile/4
    (phoenix 1.6.4) lib/phoenix/code_reloader/server.ex:73: anonymous fn/3 in Phoenix.CodeReloader.Server.handle_call/3
    (phoenix 1.6.4) lib/phoenix/code_reloader/server.ex:286: Phoenix.CodeReloader.Server.proxy_io/1
    (phoenix 1.6.4) lib/phoenix/code_reloader/server.ex:71: Phoenix.CodeReloader.Server.handle_call/3
    (stdlib 3.16.1) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.16.1) gen_server.erl:750: :gen_server.handle_msg/6
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

** (EXIT from #PID<0.1105.0>) shell process exited with reason: an exception was raised:
    ** (Module.Types.Error) found error while checking types for SomeModule.resolver/2

def(resolver(%{input: input}, %{context: %{account: %SurferLocal.Customer{} = customer}})) do
                 ...removed...
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (UndefinedFunctionError) function SurferLocal.Customer.__struct__/0 is undefined (module SurferLocal.Customer is not available)
        (surfer_local 0.1.0) SurferLocal.Customer.__struct__()
        (elixir 1.12.3) lib/module/types/of.ex:131: Module.Types.Of.struct/3
        (elixir 1.12.3) lib/module/types/pattern.ex:517: Module.Types.Pattern.of_shared/4
        (elixir 1.12.3) lib/module/types/pattern.ex:47: Module.Types.Pattern.of_pattern/3
        (elixir 1.12.3) lib/module/types/of.ex:75: anonymous fn/4 in Module.Types.Of.map_pairs/4
        (elixir 1.12.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.12.3) lib/module/types/of.ex:33: Module.Types.Of.open_map/4
        (elixir 1.12.3) lib/module/types/of.ex:75: anonymous fn/4 in Module.Types.Of.map_pairs/4
        (elixir 1.12.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.12.3) lib/module/types/of.ex:33: Module.Types.Of.open_map/4
        (elixir 1.12.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.12.3) lib/module/types/pattern.ex:12: Module.Types.Pattern.of_head/4
        (elixir 1.12.3) lib/module/types.ex:62: Module.Types.warnings_from_clause/6
        (elixir 1.12.3) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5
        (elixir 1.12.3) lib/enum.ex:3900: Enum.flat_map_list/2
        (elixir 1.12.3) lib/module/parallel_checker.ex:104: Module.ParallelChecker.check_module/2
        (elixir 1.12.3) lib/module/parallel_checker.ex:300: anonymous fn/5 in Module.ParallelChecker.spawn_checkers/1

Interactive Elixir (1.12.3) - press Ctrl+C to exit (type h() ENTER for help)
[error] Process #PID<0.5680.0> raised an exception
** (Module.Types.Error) found error while checking types for SurferLocalWeb.Mutations.CreateSmartGrid.resolver/2

def(resolver(%{input: input}, %{context: %{account: %SurferLocal.Customer{} = customer}})) do
                 ...removed...
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (UndefinedFunctionError) function SurferLocal.Customer.__struct__/0 is undefined (module SurferLocal.Customer is not available)
    (surfer_local 0.1.0) SurferLocal.Customer.__struct__()
    (elixir 1.12.3) lib/module/types/of.ex:131: Module.Types.Of.struct/3
    (elixir 1.12.3) lib/module/types/pattern.ex:517: Module.Types.Pattern.of_shared/4
    (elixir 1.12.3) lib/module/types/pattern.ex:47: Module.Types.Pattern.of_pattern/3
    (elixir 1.12.3) lib/module/types/of.ex:75: anonymous fn/4 in Module.Types.Of.map_pairs/4
    (elixir 1.12.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
    (elixir 1.12.3) lib/module/types/of.ex:33: Module.Types.Of.open_map/4
    (elixir 1.12.3) lib/module/types/of.ex:75: anonymous fn/4 in Module.Types.Of.map_pairs/4
    (elixir 1.12.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
    (elixir 1.12.3) lib/module/types/of.ex:33: Module.Types.Of.open_map/4
    (elixir 1.12.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
    (elixir 1.12.3) lib/module/types/pattern.ex:12: Module.Types.Pattern.of_head/4
    (elixir 1.12.3) lib/module/types.ex:62: Module.Types.warnings_from_clause/6
    (elixir 1.12.3) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5
    (elixir 1.12.3) lib/enum.ex:3900: Enum.flat_map_list/2
    (elixir 1.12.3) lib/module/parallel_checker.ex:104: Module.ParallelChecker.check_module/2
    (elixir 1.12.3) lib/module/parallel_checker.ex:300: anonymous fn/5 in Module.ParallelChecker.spawn_checkers/1
Error while evaluating: / ...$(pwd)... /.iex.exs
** (CompileError) .iex.exs:2: module SurferLocal.Customers is not loaded and could not be found

```

In my `.iex.exs` I'm aliasing both SurferLocal.Customer and SurferLocal.Customers. I don't have reliable reproduction.

### Environment

* Elixir & Erlang/OTP versions (elixir --version):  

```
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

* Operating system: 
![image](https://user-images.githubusercontent.com/12039839/148261782-29738038-f5a7-4778-a766-a50d552fbe0a.png)

**Comment by josevalim** [comment]
This should be addressed in more recent versions due to c8a52fde0550789da7468bc3a44213a7a654b7b4. If you still have this issue on v1.13, please let us know! Thank you for the report!
