### ISSUE TITLE
Arguments in mix command are ignored on Windows

### ISSUE THREAD

**Issue by moogle19** [elixir-lang/elixir#11568]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.13.2 (compiled with Erlang/OTP 22)
```
* Operating system: Windows 10

### Current behavior

Running `mix setup` from `ex_doc` fails on Windows, because it seems to ignore the `--prefix assets` for npm. 

`setup` in `ex_doc` is defined as:
```
 setup: ["deps.get", "cmd npm install --prefix assets"]
```

Running `mix cmd npm install --prefix assets` also fails but

**`mix cmd install --prefix assets foo` works for some reason.**

The output is:
```
C:\Users\moogle\Documents\ex_doc-custom_scrollbar>mix setup
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  earmark_parser 1.4.19
  jason 1.2.0
  makeup 1.0.5
  makeup_elixir 0.15.0
  makeup_erlang 0.1.0
  nimble_parsec 1.1.0
All dependencies are up to date
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\moogle\Documents\ex_doc-custom_scrollbar/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\moogle\Documents\ex_doc-custom_scrollbar\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\moogle\AppData\Local\npm-cache\_logs\2022-01-14T17_57_26_637Z-debug-0.log
** (exit) -4058
    (mix 1.13.2) lib/mix/tasks/cmd.ex:64: Mix.Tasks.Cmd.run/1
    (mix 1.13.2) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.2) lib/mix/task.ex:455: Mix.Task.run_alias/5
    (mix 1.13.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

### Expected behavior

`npm install` should be executed with the prefix `assets`

**Comment by josevalim** [comment]
Can you please try doing these changes and let me know if it works:

```diff
diff --git a/mix.exs b/mix.exs
index 9839d7c..58c271e 100644
--- a/mix.exs
+++ b/mix.exs
@@ -41,11 +41,11 @@ defmodule ExDoc.Mixfile do

   defp aliases do
     [
-      build: ["cmd npm run --prefix assets build", "compile --force", "docs"],
+      build: ["cmd --cd assets npm run build", "compile --force", "docs"],
       clean: [&clean_test_fixtures/1, "clean"],
-      fix: ["format", "cmd npm run --prefix assets lint:fix"],
-      lint: ["format --check-formatted", "cmd npm run --prefix assets lint"],
-      setup: ["deps.get", "cmd npm install --prefix assets"]
+      fix: ["format", "cmd --cd assets npm run lint:fix"],
+      lint: ["format --check-formatted", "cmd --cd assets npm run lint"],
+      setup: ["deps.get", "cmd --cd assets npm install"]
     ]
   end
```

In a nutshell, pass the `--cd` option to `cmd`. IIRC, `--prefix assets` is problematic for npm on Windows.

**Comment by moogle19** [comment]
Yes, that seems to work. 
But I am still a bit puzzled, why adding a random string to the end of the command seem to fix the issue. 😆 

Thanks for the quick help!
