### ISSUE TITLE
MatchError: Wrong line number -  errors on previous match statement(?)

### ISSUE THREAD

**Issue by tmjoen** [elixir-lang/elixir#11585]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.1.3] [source-b5c571a3ec] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
Elixir 1.13.2 (compiled with Erlang/OTP 24)
```
* Operating system: 
OSX 12.1

### Current behavior

If I create a test file `test.exs`
```
%{cfg: _cfg} = %{cfg: :hello}
{:ok, _image} = :test

```

It will error on line 1, instead of 2:
```
➜  ln_test elixir test.exs
** (MatchError) no match of right hand side value: :test
    test.exs:1: (file)
    (elixir 1.13.2) lib/code.ex:1183: Code.require_file/2
```

If I change the test file to:
```
for i <- 0..5 do
  i
end
%{cfg: _cfg} = %{cfg: :hello}
for i <- 0..5 do
  i
end
{:ok, _image} = :test
```
It errors on line 4:
```
** (MatchError) no match of right hand side value: :test
    test.exs:4: (file)
    (elixir 1.13.2) lib/code.ex:1183: Code.require_file/2
```
So it seems it just errors on the previous match statement (maybe?)

### Expected behavior

Error on the correct line.

This is a very reduced test case from a MatchError I had in a larger Phoenix/LiveView project, where I could not understand that the error was where it was reported 😄

**Comment by tmjoen** [comment]
I had some other people try to recreate and they could not. I use a custom erlang build that someone from the elixir forums had put together for better results with the Apple M1 (https://elixirforum.com/t/anyone-received-their-new-macbook-pros-today/43404/11). When I switch my erlang version away from that build, the line numbers are correct.

Sorry for the noise
