### ISSUE TITLE
Record.extract fails on first compilation with elixir 1.13.2

### ISSUE THREAD

**Issue by albertored** [elixir-lang/elixir#11598]
### Current behavior

I have a simple project with a single dependency
```elixir
defmodule Foo.MixProject do
  use Mix.Project

  def project do
    [
      app: :foo,
      version: "0.1.0",
      elixir: "~> 1.12",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp deps do
    [
      {:yaml_elixir,">= 0.0.0"}
    ]
  end
end
```
If used with elixir 1.13.2 compilation fails the first time while elixir 1.12.3 works correctly.
Both versions were compiled with OTP 23.3.4.5

```
$ kiex use 1.13.2
Using 1.13.2

$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  yamerl 0.9.0
  yaml_elixir 2.8.0
* Getting yaml_elixir (Hex package)
* Getting yamerl (Hex package)

$ mix compile
===> Compiling yamerl
==> yaml_elixir
Compiling 6 files (.ex)

== Compilation error in file lib/yaml_elixir/records.ex ==
** (ArgumentError) lib file yamerl/include/internal/yamerl_constr.hrl could not be found
    (elixir 1.13.2) lib/record/extractor.ex:41: Record.Extractor.from_lib_file/1
    (elixir 1.13.2) lib/record/extractor.ex:18: Record.Extractor.from_or_from_lib_file/1
    (elixir 1.13.2) lib/record/extractor.ex:5: Record.Extractor.extract/2
    lib/yaml_elixir/records.ex:6: (module)
could not compile dependency :yaml_elixir, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile yaml_elixir", update it with "mix deps.update yaml_elixir" or clean it with "mix deps.clean yaml_elixir"

$ mix compile
===> Compiling yamerl
==> yaml_elixir
Compiling 6 files (.ex)
Generated yaml_elixir app
==> foo
Compiling 1 file (.ex)
Generated foo app

$ rm -rf deps _build

$ kiex use 1.12.3
Using 1.12.3

$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  yamerl 0.9.0
  yaml_elixir 2.8.0
* Getting yaml_elixir (Hex package)
* Getting yamerl (Hex package)

$ mix compile
===> Compiling yamerl
==> yaml_elixir
Compiling 6 files (.ex)
Generated yaml_elixir app
==> foo
Compiling 1 file (.ex)
Generated foo app
```

On my environment the error happens every time it is not some random failure.

The lib file exists, looking at the `Record` module code it seems that the error is generated by a failure on this call: `:code.lib_dir(:yamerl)`.

Let me know if you can reproduce it and if you need some additional info.

Thanks!

**Comment by albertored** [comment]
**Update:** just tried on `hexpm/elixir:1.13.2-erlang-23.3.4.5-alpine-3.14.0` docker image and it works as expected so it should me something messed up with my machine. If you have some suggestion on how to find the problem is very welcome, otherwise the issue can be closed, sorry for the noise.

**Comment by josevalim** [comment]
@albertored please try `mix local.rebar` and see if it works the first time on your machine.

**Comment by albertored** [comment]
> @albertored please try `mix local.rebar` and see if it works the first time on your machine.

it works like a charm! Thanks @josevalim!
