### ISSUE TITLE
String.split_at error when split big binary

### ISSUE THREAD

**Issue by feng19** [elixir-lang/elixir#11617]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Operating system: mac os

### Current behavior

```elixir
String.split_at(big_binary, 7500)
```

### Expected behavior

```shell
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a bitstring

This typically happens when calling Kernel.byte_size/1 with an invalid argument or when performing binary construction or binary concatenation with <> and one of the arguments is not a binary
    :erlang.byte_size([<<171, 5, 79, 201, 252, 254, 101, 162, 66, 8, 224, 115, 32, 18, 119, 217, 233, 38, 225, 140, 4, 252, 22, 137, 46, 124, 185, 102, 200, 79, 38, 240, 112, 150, 121, 2, 50, 191, 235, 127, 169, 33, 111, 59, 166, 217, 189, 143, 155, ...>>])
    (elixir 1.13.1) lib/string.ex:2727: String.byte_size_remaining_at/2
    (elixir 1.13.1) lib/string.ex:653: String.do_split_at/2
```

https://github.com/elixir-lang/elixir/blob/0c0f7af6799c2131077e348563ee59763e118c7e/lib/elixir/lib/string.ex#L2817

This line, the `rest` is a list, not a binary.

**Comment by josevalim** [comment]
@feng19 this function should not crash though. It will give you the invalid result (because it will try to count codepoints) but it should not crash. Can you share the part of the input that lead to an error so we can fix it? Thank you! :)

**Comment by ericmj** [comment]
It looks like the binary was wrapped in a list:

> `:erlang.byte_size([<<171, 5, 79, 201, 2, ...`

**Comment by feng19** [comment]
Hi, @josevalim 

I got the case:

```elixir
iex(1)> [_ | rest] = :unicode_util.gc(<<107, 205, 135, 184>>)
[[107, 839], <<184>>]
iex(2)> rest
[<<184>>]
iex(3)> String.split_at(<<107, 205, 135, 184>>, 1)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a bitstring

This typically happens when calling Kernel.byte_size/1 with an invalid argument or when performing binary construction or binary concatenation with <> and one of the arguments is not a binary
    :erlang.byte_size([<<184>>])
    (elixir 1.13.1) lib/string.ex:2727: String.byte_size_remaining_at/2
    (elixir 1.13.1) lib/string.ex:653: String.do_split_at/2
```

**Comment by feng19** [comment]
I found on old version is ok:

Erlang/OTP 23 [erts-11.1.5]
Elixir 1.12.3

```elixir
iex(1)> :unicode_util.gc(<<107, 205, 135, 184>>)
[[107, 839], <<184>>]
iex(2)> String.split_at(<<107, 205, 135, 184>>, 1)
{"k͇", <<184>>}
```
