### ISSUE TITLE
ExUnit: exception raised in setup is missing in stacktrace, making it hard to debug

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11814]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.3.4 / OTP 24
* Operating system: Linux

### Current behavior

Having a hard time trying to debug a fie with a lot of tests when the culprit was in the setup.

Here's a sample repo: https://github.com/eksperimental/raise_in_setup

run `mix test`

Include code samples, errors and stacktraces if appropriate.
If reporting a bug, please include the reproducing steps.

```console
$ mix test


  1) test raises with OK setup, and faulty function call (RaiseInSetupOKTest)
     test/raise_in_setup_ok_test.exs:11
     ** (FunctionClauseError) no function clause matching in RaiseInSetup.foo/1

     The following arguments were given to RaiseInSetup.foo/1:
     
         # 1
         "string"
     
     Attempted function clauses (showing 1 out of 1):
     
         def foo(term) when is_atom(term)
     
     code: assert RaiseInSetup.foo("string") == {:foo, :atom}
     stacktrace:
       (raise_in_setup 0.1.0) lib/raise_in_setup.ex:19: RaiseInSetup.foo/1
       test/raise_in_setup_ok_test.exs:12: (test)

.

  2) test raises with faulty setup (RaiseInSetupFaultyTest)
     test/raise_in_setup_faulty_test.exs:10
     ** (FunctionClauseError) no function clause matching in RaiseInSetup.foo/1

     The following arguments were given to RaiseInSetup.foo/1:
     
         # 1
         "string"
     
     Attempted function clauses (showing 1 out of 1):
     
         def foo(term) when is_atom(term)
     
     stacktrace:
       (raise_in_setup 0.1.0) lib/raise_in_setup.ex:19: RaiseInSetup.foo/1
       (ex_unit 1.13.4) lib/ex_unit/on_exit_handler.ex:143: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit 1.13.4) lib/ex_unit/on_exit_handler.ex:129: ExUnit.OnExitHandler.on_exit_runner_loop/0



Finished in 0.03 seconds (0.00s async, 0.03s sync)
1 doctest, 2 tests, 2 failures

Randomized with seed 928352
```

### Expected behavior

I expect the stacktrace for the test with the faulty setup to include a reference to the culprit file:line, in this case `raise_in_setup_faulty_test.exs:7`

**Comment by josevalim** [comment]
It is tail call optimization kicking in. Rewrite the callback to:

```elixir
    on_exit(fn ->
      RaiseInSetup.foo(:atom)
      :ok
    end)
```

and you will get:

```

  2) test raises with faulty setup (RaiseInSetupFaultyTest)
     test/raise_in_setup_faulty_test.exs:11
     ** (FunctionClauseError) no function clause matching in RaiseInSetup.foo/1

     The following arguments were given to RaiseInSetup.foo/1:

         # 1
         "string"

     Attempted function clauses (showing 1 out of 1):

         def foo(term) when is_atom(term)

     stacktrace:
       (raise_in_setup 0.1.0) lib/raise_in_setup.ex:19: RaiseInSetup.foo/1
       test/raise_in_setup_faulty_test.exs:6: anonymous fn/0 in RaiseInSetupFaultyTest.__ex_unit_setup_0/1
       (ex_unit 1.14.0-dev) lib/ex_unit/on_exit_handler.ex:143: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit 1.14.0-dev) lib/ex_unit/on_exit_handler.ex:129: ExUnit.OnExitHandler.on_exit_runner_loop/0
```

There is nothing we can do. It is how the VM works. :)

**Comment by eksperimental** [comment]
Noted!
Thank you.
