### ISSUE TITLE
Elixir 1.13.4 is not compatible with OTP 25

### ISSUE THREAD

**Issue by extesy** [elixir-lang/elixir#11857]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
D:\Dev\Elixir\bin>elixir.bat -v
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:36:32] [ds:36:32:10] [async-threads:1] [jit:ns]

Elixir 1.13.4 (compiled with Erlang/OTP 22)
```
* Operating system: Windows 11

### Current behavior

```
D:\Projects\Research\followshows>mix deps.update --all

20:54:06.782 [error] beam\beam_load.c(86): Error loading module 'Elixir.Code.Formatter':
  lambda already defined for label 749. To fix this, please recompile this module with an OTP 25 compiler.



20:54:06.782 [error] Loading of d:/Dev/Elixir/lib/elixir/ebin/Elixir.Code.Formatter.beam failed: :badfile

** (UndefinedFunctionError) function Code.Formatter.locals_without_parens/0 is undefined (module Code.Formatter is not available)
    (elixir 1.13.4) Code.Formatter.locals_without_parens()
    (elixir 1.13.4) lib/code/normalizer.ex:22: Code.Normalizer.normalize/2
    (elixir 1.13.4) lib/code.ex:1107: Code.quoted_to_algebra/2
```

### Expected behavior

No error

**Comment by josevalim** [comment]
It is compatible but unfortunately not the precompiled versions. So for now you have to compile it yourself. From Elixir v1.14, we will provide compiled packages per OTP Version.
