### ISSUE TITLE
ExUnit test names longer than 255 chars creating SystemLimitError 

### ISSUE THREAD

**Issue by developess** [elixir-lang/elixir#11946]
### Elixir and Erlang/OTP versions

Elixir 1.12.1 (compiled with Erlang/OTP 24)

### Operating system

macOS Montery 12.2.1

### Current behavior

Noticed we're getting a compilation error when running mix test on a particularly long test name (long test name, inside long describe block name) - can replicate with brand new repo created with `mix new` and a single test

```elixir
  test "greets the world but a test name over 255 characters because that is the max size of an atom in erlang so this should error during the test run. What is love? baby dont hurt me, dont hurt me, no more. What is love? Baby dont hurt me, dont hurt me, no more" do
    assert ExunitBug.hello() == :world
  end
```

```sh
❯ mix test

== Compilation error in file test/exunit_bug_test.exs ==
** (SystemLimitError) a system limit has been reached
    :erlang.binary_to_atom("test greets the world but a test name over 255 characters because that is the max size of an atom in erlang so this should error during the test run. What is love? baby dont hurt me, dont hurt me, no more. What is love? Baby dont hurt me, dont hurt me, no more", :utf8)
    (ex_unit 1.12.1) lib/ex_unit/case.ex:560: ExUnit.Case.register_test/6
    test/exunit_bug_test.exs:5: (module)
    (stdlib 3.15.1) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.1) lib/kernel/parallel_compiler.ex:428: Kernel.ParallelCompiler.require_file/2
    (elixir 1.12.1) lib/kernel/parallel_compiler.ex:321: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected behavior

I'm not sure if this is a bug or I just couldn't find the documentation that limits test names to 255 chars. Should it be in ExUnit.Case? 

We only started getting this error when running our test suites this morning (was fine on Friday) so unsure where it has surfaced from

**Comment by developess** [comment]
Just thought I'd add that the error in our main codebase has a different stacktrace:
```
** (CompileError) test/our_test_file_name.exs: internal error in pass v3_kernel:
exception error: a system limit has been reached
  in function  list_to_atom/1
     called as list_to_atom("-inlined-test updating a guarantee payment for a deal of type advance_may2018 with a single remainder of advance payment updates the guarantee payment in the database with calculated projected_total_net_of_fees, advance_fee, agency_fee, total_gross and total_fees/1-")
  in call from v3_kernel:translate_fc_args/4 (v3_kernel.erl, line 451)
  in call from v3_kernel:translate_match_fail/4 (v3_kernel.erl, line 419)
  in call from v3_kernel:match_guard_1/3 (v3_kernel.erl, line 1057)
  in call from v3_kernel:match_guard/3 (v3_kernel.erl, line 1050)
  in call from lists:foldr_1/3 (lists.erl, line 1372)
  in call from v3_kernel:expr/3 (v3_kernel.erl, line 317)
  in call from v3_kernel:expr/3 (v3_kernel.erl, line 285)
  in call from v3_kernel:function/2 (v3_kernel.erl, line 168)
  in call from lists:mapfoldl_1/3 (lists.erl, line 1462)
  in call from lists:mapfoldl_1/3 (lists.erl, line 1463)
  in call from v3_kernel:module/2 (v3_kernel.erl, line 134)
  in call from compile:v3_kernel/2 (compile.erl, line 1508)
  in call from compile:fold_comp/4 (compile.erl, line 405)
  in call from compile:internal_comp/5 (compile.erl, line 389)
  in call from compile:'-internal_fun/2-anonymous-0-'/2 (compile.erl, line 227)
  in call from elixir_erl_compiler:compile/3 (src/elixir_erl_compiler.erl, line 54)
  in call from elixir_erl:load_form/5 (src/elixir_erl.erl, line 440)
  in call from elixir_module:'-compile/5-fun-0-'/8 (src/elixir_module.erl, line 149)
  in call from elixir_erl_compiler:'-spawn/1-fun-0-'/2 (src/elixir_erl_compiler.erl, line 12)
    (stdlib 4.0) lists.erl:1442: :lists.foreach_1/2
```

**Comment by josevalim** [comment]
We have recently improved the error message for this in main but it is indeed a limitation for functions in Erlang/Elixir.
