### ISSUE TITLE
"erl_child_setup" logs when using PartitionSupervisor

### ISSUE THREAD

**Issue by mhanberg** [elixir-lang/elixir#11988]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 23 [erts-11.2.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.12.3 (compiled with Erlang/OTP 22)
```

(note that PartitionSupervisor is not available in v1.12.x, but I have vendored it)

as well as

```
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0-dev (d404168) (compiled with Erlang/OTP 25)
```

### Operating system

macOS 12.4 (ARM)

### Current behavior

When running the [Wallaby](https://github.com/elixir-wallaby/wallaby) test suite locally on my MacBook, I see these logs printed to the console. 

Nothing crashes and the tests still pass, but this is odd behavior.

```
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.12.3) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.12.3) lib/supervisor.ex:556: Supervisor.start_link/2
  (kernel 7.3.1.2) application_master.erl:277: :application_master.start_it_old/4

Excluding tags: [pending: true]

.................................................................................................................................................................................................................................................erl_child_setup: failed with error 32 on line 260
.erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
.erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
.erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
.erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
.erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
.erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
.erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
erl_child_setup: failed with error 32 on line 260
.......

Finished in 146.4 seconds (130.1s async, 16.3s sync)
4 features, 251 tests, 0 failures

Randomized with seed 773197
```

### Expected behavior

No logs are printed about `erl_child_setup`.

**Comment by whatyouhide** [comment]
@mhanberg were you able to reproduce this issue consistently in a dedicated codebase? Just to understand how much of this is tied to Wallaby.
