### ISSUE TITLE
Macro.to_string quote do: :erlang.binary_to_atom(..., :utf8)

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#12162]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0 (compiled with Erlang/OTP 24)
```

### Operating system

linux

### Current behavior

```elixir
iex> x
{:<<>>, [],
 [
   {:"::", [],
    [
      {{:., [], [String.Chars, :to_string]}, [], [{:x, [], nil}]},
      {:binary, [], nil}
    ]},
   "_y"
 ]}
iex> IO.puts Macro.to_string x
<<String.Chars.to_string(x)::binary, "_y">>
:ok
iex> IO.puts Macro.to_string quote do: :erlang.binary_to_atom(unquote(x), :utf8)
** (CaseClauseError) no case clause matching: :utf8
    (elixir 1.14.0) lib/code/formatter.ex:2256: Code.Formatter.force_args?/2
    (elixir 1.14.0) lib/code/formatter.ex:1162: Code.Formatter.call_args_to_algebra_no_blocks/6
    (elixir 1.14.0) lib/code/formatter.ex:1100: Code.Formatter.call_args_to_algebra/6
    (elixir 1.14.0) lib/code/formatter.ex:994: Code.Formatter.remote_to_algebra/3
    (elixir 1.14.0) lib/code/formatter.ex:576: anonymous fn/3 in Code.Formatter.block_args_to_algebra/4
    (elixir 1.14.0) lib/code/formatter.ex:1957: Code.Formatter.each_quoted_to_algebra_with_comments/6
    (elixir 1.14.0) lib/code/formatter.ex:1935: Code.Formatter.quoted_to_algebra_with_comments/6
    (elixir 1.14.0) lib/code/formatter.ex:581: Code.Formatter.block_args_to_algebra/4
```

### Expected behavior

This code doesn't raise

**Comment by wojtekmach** [comment]
Good catch. I was able to find an even smaller reproduction:

```elixir
iex> Macro.to_string(quote do :erlang.binary_to_atom(<<1>>, :utf8) end)
** (CaseClauseError) no case clause matching: :utf8
```

interestingly we also have:

```elixir
iex> Macro.to_string(quote do :erlang.binary_to_atom(<<>>, :utf8) end)
":\"\""
```
