### ISSUE TITLE
Macro.to_string bug in List.to_charlist

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#12248]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.3.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 24)
```

### Operating system

Linux

### Current behavior

```
iex> x = {{:., [], [List, :to_charlist]}, [],
 [
   [
     {:case, [line: 4, generated: true],
      [
        {:not_before, [counter: 1, line: 4], nil},
        [
          do: [
            {:->, [],
             [
               [
                 {:when, [],
                  [
                    {:underscore, [counter: 1, line: 4, generated: true], nil},
                    {{:., [], [:erlang, :is_binary]}, [],
                     [
                       {:underscore, [counter: 1, line: 4, generated: true],
                        nil}
                     ]}
                  ]}
               ],
               {:underscore, [counter: 1, line: 4, generated: true], nil}
             ]},
            {:->, [],
             [
               [{:underscore, [counter: 1, line: 4, generated: true], nil}],
               {{:., [], [String.Chars, :to_string]}, [],
                [{:underscore, [counter: 1, line: 4, generated: true], nil}]}
             ]}
          ]
        ]
      ]},
     {:<<>>, [], '000000Z'}
   ]
 ]}

iex> Macro.to_string x
** (CaseClauseError) no case clause matching: {:do, [{:->, [], [[{:when, [], [{:underscore, [counter: 1, line: 4, generated: true], nil}, {{:., [], [:erlang, :is_binary]}, [], [{:underscore, [counter: 1, line: 4, generated: true], nil}]}]}], {:underscore, [counter: 1, line: 4, generated: true], nil}]}, {:->, [], [[{:underscore, [counter: 1, line: 4, generated: true], nil}], {{:., [], [String.Chars, :to_string]}, [], [{:underscore, [counter: 1, line: 4, generated: true], nil}]}]}]}
    (elixir 1.14.2) lib/code/formatter.ex:2259: Code.Formatter.force_args?/2
    (elixir 1.14.2) lib/code/formatter.ex:1137: Code.Formatter.call_args_to_algebra_no_blocks/6
    (elixir 1.14.2) lib/code/formatter.ex:1100: Code.Formatter.call_args_to_algebra/6
    (elixir 1.14.2) lib/code/formatter.ex:1048: Code.Formatter.local_to_algebra/5
    (elixir 1.14.2) lib/code/formatter.ex:2109: Code.Formatter.many_args_to_algebra/3
    (elixir 1.14.2) lib/code/formatter.ex:1650: anonymous fn/5 in Code.Formatter.args_to_algebra_with_comments/7
    (elixir 1.14.2) lib/code/formatter.ex:1960: Code.Formatter.each_quoted_to_algebra_with_comments/6
    (elixir 1.14.2) lib/code/formatter.ex:1938: Code.Formatter.quoted_to_algebra_with_comments/6
```

Related to #12162

### Expected behavior

`Macro.to_string x` returns
```
"List.to_charlist([\n  case not_before do\n    underscore when :erlang.is_binary(underscore) -> underscore\n    underscore -> String.Chars.to_string(underscore)\n  end,\n  <<48, 48, 48, 48, 48, 48, 90>>\n])"
```

**Comment by wojtekmach** [comment]
This seems to work here. I'm on Elixir main:

```elixir
iex> quote do List.to_charlist([case not_before do underscore when :erlang.is_binary(underscore) -> underscore ; underscore -> String.Chars.to_string(underscore) ;  end, <<48, 48, 48, 48, 48, 48, 90>>]) end |> Macro.to_string() |> IO.puts()
List.to_charlist([
  case not_before do
    underscore when :erlang.is_binary(underscore) -> underscore
    underscore -> String.Chars.to_string(underscore)
  end,
  <<48, 48, 48, 48, 48, 48, 90>>
])
```

if there's still a bug, could you paste the quoted expression, not the raw ast?

**Comment by josevalim** [comment]
I was able to isolate it to:

```
Macro.to_string(quote do
  :"Elixir.List".to_charlist([case var do var -> var end])
end)
```
