### ISSUE TITLE
IEx fails with "shell process exited with reason: an exception was raised" on failure of a simple guard check

### ISSUE THREAD

**Issue by theenglishway** [elixir-lang/elixir#12243]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 24)

### Operating system

Arch Linux

### Current behavior

In a project of mine I implemented a very simple guard that checks whether a `Ecto.Changeset` helds some particular kind of data, with the following code :

```
  defguard is_cs(cs) when is_struct(cs, Ecto.Changeset)
  defguard is_cs(cs, type) when is_cs(cs) and is_struct(cs.data, type)
```

For some reason, using this guard with a value that does not pass the guard makes IEx fail in a spectacular fashion.

I've written a minimal test case that reproduces the problem :

```
defmodule NestedStruct do
  defstruct [:inner_struct]
end

defmodule SimpleStruct do
  defstruct [:field]
end

defmodule GuardTest do
  defguard is_nested(struct) when is_struct(struct, NestedStruct)
  defguard is_nested(struct, type) when is_nested(struct) and is_struct(struct.inner_struct, type)

  def test_guard_partial(cs) when is_nested(cs, SimpleStruct), do: :nested_simple
  def test_guard_partial([]), do: :list
end
```

Running it in iex yields the following error : 

```
iex(1)> %NestedStruct{} |> GuardTest.test_guard_partial
** (EXIT from #PID<0.186.0>) shell process exited with reason: an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:
  * 1st argument: not an atom
        :erlang.atom_to_binary({:., [], [{:cs, [version: 0, line: 40], nil}, :inner_struct]})
        (elixir 1.14.2) lib/code/formatter.ex:280: Code.Formatter.quoted_to_algebra/3
        (elixir 1.14.2) lib/code/formatter.ex:1650: anonymous fn/5 in Code.Formatter.args_to_algebra_with_comments/7
        (elixir 1.14.2) lib/code/formatter.ex:1960: Code.Formatter.each_quoted_to_algebra_with_comments/6
        (elixir 1.14.2) lib/code/formatter.ex:1938: Code.Formatter.quoted_to_algebra_with_comments/6
        (elixir 1.14.2) lib/code/formatter.ex:1676: Code.Formatter.args_to_algebra_with_comments/7
        (elixir 1.14.2) lib/code/formatter.ex:1167: Code.Formatter.call_args_to_algebra_no_blocks/6
        (elixir 1.14.2) lib/code/formatter.ex:1100: Code.Formatter.call_args_to_algebra/6
```

I've run into this behaviour on Elixir 1.14.0, 1.14.1, and 1.14.2 (the latter both with otp 25 and otp 24)

### Expected behavior

On Elixir versions < 1.13.4 (with OTP24 or 25), the same code yields a much nicer error message : 

```
iex(1)> %NestedStruct{} |> GuardTest.test_guard_partial
** (FunctionClauseError) no function clause matching in GuardTest.test_guard_partial/1
    The following arguments were given to GuardTest.test_guard_partial/1:
        # 1
        %NestedStruct{inner_struct: nil}
    Attempted function clauses (showing 2 out of 2):
        def test_guard_partial(cs) when is_map(cs) and is_atom(NestedStruct) or :fail and is_map_key(cs, :__struct__) and :erlang.map_get(:__struct__, cs) == NestedStruct and is_map(cs.inner_struct) and is_atom(SimpleStruct) or :fail and is_map_key(cs.inner_struct, :__struct__) and :erlang.map_get(:__struct__, cs.inner_struct) == SimpleStruct
        def test_guard_partial([])
    (guard_test 0.1.0) lib/guard_test.ex:16: GuardTest.test_guard_partial/1
    (guard_test 0.1.0) lib/guard_test.ex:42: GuardTest.run_test_no_rescue/2
    (guard_test 0.1.0) lib/guard_test.ex:27: anonymous fn/4 in GuardTest.test/0
    (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (guard_test 0.1.0) lib/guard_test.ex:24: GuardTest.test/0
```

I've written a gist that tests a few scenarios that came to my mind, e.g. trying to cover all the possible cases with a "catch-all" clause for the function on which the guard applies, or rescuing the error : https://gist.github.com/theenglishway/0b0f7d32f74a6adeea2d0f138a638048

The 12 tests run in `GuardTest.test` run perfectly well on Elixir 1.13 ; the last one produces the helpful `FunctionClauseError` message posted right above.

In all versions of Elixir 1.14, 11 of them pass ; but the last one (which runs `%NestedStruct{} |> GuardTest.test_guard_partial` without a `try/rescue` block around it) produces the behaviour I described above.

**Comment by josevalim** [comment]
Thanks @theenglishway for the report. I was able to reproduce it with the following steps. Created a file named `foo.exs`:

```
defmodule NestedStruct do
  defstruct [:inner_struct]
end

defmodule SimpleStruct do
  defstruct [:field]
end

defmodule GuardTest do
  defguard is_nested(struct) when is_struct(struct, NestedStruct)
  defguard is_nested(struct, type) when is_nested(struct) and is_struct(struct.inner_struct, type)

  def test_guard_partial(cs) when is_nested(cs, SimpleStruct), do: :nested_simple
  def test_guard_partial([]), do: :list
end
```

And then I did:

```
$ elixirc foo.exs
$ iex
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Interactive Elixir (1.15.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> %NestedStruct{} |> GuardTest.test_guard_partial
** (FunctionClauseError) no function clause matching in GuardTest.test_guard_partial/1

    The following arguments were given to GuardTest.test_guard_partial/1:

        # 1
        %NestedStruct{inner_struct: nil}

    foo.exs:13: GuardTest.test_guard_partial/1
    iex:1: (file)
iex(1)>
```

**Comment by theenglishway** [comment]
That was super fast !

Thanks :+1:
