### ISSUE TITLE
Mix fails on run

### ISSUE THREAD

**Issue by Kartstig** [elixir-lang/elixir#12514]
### Elixir and Erlang/OTP versions

herman@herman-Galago-Pro ⏎  elixir --version
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.11.2 (compiled with Erlang/OTP 25)

### Operating system

Ubuntu Linux

### Current behavior

Mix fails whenever I run it. Tried to run the suggested commands but they didn't resolve the issue:
```
herman@herman-Galago-Pro ⏎  mix

12:36:24.729 [error] beam/beam_load.c(551): Error loading function 'Elixir.Hex.Netrc.Cache':child_spec/1: op put_tuple u x:
  please re-compile this module with an Erlang/OTP 25 compiler



12:36:24.733 [error] beam/beam_load.c(551): Error loading function 'Elixir.Hex.Netrc.Cache':child_spec/1: op put_tuple u x:
  please re-compile this module with an Erlang/OTP 25 compiler



12:36:24.729 [error] Loading of /home/herman/.mix/archives/hex-2.0.6/hex-2.0.6/ebin/Elixir.Hex.Netrc.Cache.beam failed: :badfile


12:36:24.733 [error] Loading of /home/herman/.mix/archives/hex-2.0.6/hex-2.0.6/ebin/Elixir.Hex.Netrc.Cache.beam failed: :badfile


12:36:24.739 [info]  Application hex exited: exited in: Hex.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Hex.Netrc.Cache was given as a child to a supervisor but it does not exist.
            (elixir 1.11.2) lib/supervisor.ex:631: Supervisor.init_child/1
            (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
            (elixir 1.11.2) lib/supervisor.ex:617: Supervisor.init/2
            (elixir 1.11.2) lib/supervisor.ex:556: Supervisor.start_link/2
            (kernel 8.4.2) application_master.erl:293: :application_master.start_it_old/4

12:36:24.741 [info]  Application inets exited: :stopped

12:36:24.742 [info]  Application ssl exited: :stopped

12:36:24.742 [info]  Application public_key exited: :stopped

12:36:24.742 [info]  Application asn1 exited: :stopped

12:36:24.742 [info]  Application crypto exited: :stopped
Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"
** (MatchError) no match of right hand side value: {:error, {:hex, {:bad_return, {{Hex.Application, :start, [:normal, []]}, {:EXIT, {%ArgumentError{message: "The module Hex.Netrc.Cache was given as a child to a supervisor but it does not exist."}, [{Supervisor, :init_child, 1, [file: 'lib/supervisor.ex', line: 631]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1399]}, {Supervisor, :init, 2, [file: 'lib/supervisor.ex', line: 617]}, {Supervisor, :start_link, 2, [file: 'lib/supervisor.ex', line: 556]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 293]}]}}}}}}
    (hex 2.0.6) lib/hex.ex:5: Hex.start/0
    (mix 1.11.2) lib/mix/hex.ex:59: Mix.Hex.start/0
    (mix 1.11.2) lib/mix/dep/loader.ex:194: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.11.2) lib/mix/dep/loader.ex:147: Mix.Dep.Loader.to_dep/3
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.11.2) lib/mix/dep/loader.ex:364: Mix.Dep.Loader.mix_children/2
    (mix 1.11.2) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix 1.11.2) lib/mix/dep/converger.ex:57: Mix.Dep.Converger.all/4
```

I have tried the following:
- Recompile elixir with OTP25
- `mix local.hex`
- `mix archive.uninstall hex.ez`
- rm -rf of project `_build/` directory

### Expected behavior

mix doesn't fail

**Comment by josevalim** [comment]
Your Elixir version does not support Erlang/OTP 25. Either use an earlier Erlang or later Elixir please. You can find the compatibility table here: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

**Comment by Kartstig** [comment]
Updated to v1.14.4 and it's working:
```
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.4 (compiled with Erlang/OTP 25)
```

Is there anything I can do to help provide a less cryptic error message? Specifically, I felt this message was misleading to me:
```
12:36:24.729 [error] beam/beam_load.c(551): Error loading function 'Elixir.Hex.Netrc.Cache':child_spec/1: op put_tuple u x:
  please re-compile this module with an Erlang/OTP 25 compiler
```

I'm closing this, but feel free to provide any additional comments. Thanks for the quick response!

**Comment by josevalim** [comment]
I will investigate, thank you!
