### ISSUE TITLE
[Mix] Package not prefetched error

### ISSUE THREAD

**Issue by mickel8** [elixir-lang/elixir#12636]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Operating system

Arch Linux x86_64

### Current behavior

When doing `mix deps.update`, I got `not prefetched` error.
There is `please report this issue` so I assume you want to know about the issue?
 Re-running `mix deps.update membrane_rtp_plugin` solved the problem so feel free to close if that's minor thing.

```
[17:08] michal:membrane_videoroom (update-engine) | mix deps.update membrane_rtp_plugin
* Updating membrane_rtp_plugin (https://github.com/membraneframework/membrane_rtp_plugin.git - origin/outbound-rtp-bytes)
Resolving Hex dependencies...
Resolution completed in 0.191s
Unchanged:
  acceptor_pool 1.0.0
  beamchmark 1.4.1
  bimap 1.3.0
  bunch 1.6.0
  bunch_native 0.5.0
  bundlex 1.1.1
  bunt 0.2.1
  castore 1.0.3
  certifi 2.9.0
  coerce 1.0.1
  cowboy 2.10.0
  cowboy_telemetry 0.4.0
  cowlib 2.11.0
  credo 1.7.0
  ctx 0.6.0
  db_connection 2.5.0
  decimal 2.1.1
  dialyxir 1.3.0
  ecto 3.10.1
  ecto_sql 3.10.1
  erlex 0.2.6
  esbuild 0.7.0
  ex_dtls 0.12.0
  ex_libsrtp 0.6.0
  ex_sdp 0.11.0
  fake_turn 0.4.1
  fast_tls 1.1.13
  file_system 0.2.10
  floki 0.34.3
  gproc 0.8.0
  grpcbox 0.16.0
  hackney 1.18.1
  heap 2.0.2
  hpack_erl 0.2.3
  httpoison 1.8.2
  idna 6.1.1
  jason 1.4.0
  math 0.7.0
  membrane_common_c 0.14.0
  membrane_file_plugin 0.13.3
  membrane_funnel_plugin 0.7.0
  membrane_h264_ffmpeg_plugin 0.26.2
  membrane_h264_format 0.5.0
  membrane_ice_plugin 0.15.1
  membrane_opentelemetry 0.1.0
  membrane_opus_format 0.3.0
  membrane_raw_video_format 0.3.0
  membrane_rtc_engine_timescaledb 0.1.0
  membrane_rtp_format 0.6.0
  membrane_rtp_h264_plugin 0.15.1
  membrane_rtp_opus_plugin 0.7.0
  membrane_rtp_vp8_plugin 0.7.1
  membrane_tee_plugin 0.10.1
  membrane_telemetry_metrics 0.1.0
  membrane_vp8_format 0.4.0
  membrane_webrtc_plugin 0.14.6
  metrics 1.0.1
  mime 2.0.5
  mimerl 1.2.0
  numbers 5.2.4
  opentelemetry 1.0.5
  opentelemetry_api 1.0.3
  opentelemetry_exporter 1.0.4
  opentelemetry_zipkin 1.0.0
  p1_utils 1.0.23
  parse_trans 3.3.1
  phoenix 1.6.16
  phoenix_html 3.3.1
  phoenix_inline_svg 1.4.0
  phoenix_live_reload 1.4.1
  phoenix_live_view 0.17.14
  phoenix_pubsub 2.1.2
  phoenix_template 1.0.1
  phoenix_view 2.0.2
  plug 1.14.2
  plug_cowboy 2.6.1
  plug_crypto 1.2.5
  poison 5.0.0
  postgrex 0.17.1
  qex 0.5.1
  ranch 1.8.0
  ratio 2.4.2
  secure_random 0.5.1
  shmex 0.5.0
  ssl_verify_fun 1.1.6
  statistics 0.6.2
  telemetry 1.2.1
  telemetry_metrics 0.6.1
  tls_certificate_check 1.19.0
  ts_chatterbox 0.13.0
  unicode_util_compat 0.7.0
  unifex 1.1.0
  uuid 1.1.8

17:08:54.673 [error] GenServer Hex.Registry.Server terminating
** (Mix.Error) Package hexpm/heap not prefetched, please report this issue
    (mix 1.14.2) lib/mix.ex:513: Mix.raise/2
    (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
    (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.432.0>): {:outer_checksum, "hexpm", "heap", "2.0.2"}
State: %{closing_fun: nil, ets: nil, fetched: MapSet.new([]), path: nil, pending: MapSet.new([]), waiting: %{}}
Client #PID<0.432.0> is alive

    (stdlib 4.1.1) gen.erl:256: :gen.do_call/4
    (elixir 1.14.2) lib/gen_server.ex:1035: GenServer.call/3
    (hex 2.0.6) lib/hex/scm.ex:397: Hex.SCM.fetch/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

17:08:54.679 [error] Task #PID<0.438.0> started from :hex_fetcher terminating
** (stop) exited in: GenServer.call(Hex.Registry.Server, {:outer_checksum, "hexpm", "plug_crypto", "1.2.5"}, 60000)
    ** (EXIT) an exception was raised:
        ** (Mix.Error) Package hexpm/heap not prefetched, please report this issue
            (mix 1.14.2) lib/mix.ex:513: Mix.raise/2
            (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (hex 2.0.6) lib/hex/scm.ex:397: Hex.SCM.fetch/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<8.5041617/0 in Hex.SCM.prefetch/1>
    Args: []

17:08:54.679 [error] Task #PID<0.433.0> started from :hex_fetcher terminating
** (stop) exited in: GenServer.call(Hex.Registry.Server, {:outer_checksum, "hexpm", "bimap", "1.3.0"}, 60000)
    ** (EXIT) an exception was raised:
        ** (Mix.Error) Package hexpm/heap not prefetched, please report this issue
            (mix 1.14.2) lib/mix.ex:513: Mix.raise/2
            (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (hex 2.0.6) lib/hex/scm.ex:397: Hex.SCM.fetch/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<8.5041617/0 in Hex.SCM.prefetch/1>
    Args: []

17:08:54.679 [error] Task #PID<0.432.0> started from :hex_fetcher terminating
** (stop) exited in: GenServer.call(Hex.Registry.Server, {:outer_checksum, "hexpm", "heap", "2.0.2"}, 60000)
    ** (EXIT) an exception was raised:
        ** (Mix.Error) Package hexpm/heap not prefetched, please report this issue
            (mix 1.14.2) lib/mix.ex:513: Mix.raise/2
            (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (hex 2.0.6) lib/hex/scm.ex:397: Hex.SCM.fetch/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<8.5041617/0 in Hex.SCM.prefetch/1>
    Args: []

17:08:54.679 [error] Task #PID<0.435.0> started from :hex_fetcher terminating
** (stop) exited in: GenServer.call(Hex.Registry.Server, {:outer_checksum, "hexpm", "metrics", "1.0.1"}, 60000)
    ** (EXIT) an exception was raised:
        ** (Mix.Error) Package hexpm/heap not prefetched, please report this issue
            (mix 1.14.2) lib/mix.ex:513: Mix.raise/2
            (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (hex 2.0.6) lib/hex/scm.ex:397: Hex.SCM.fetch/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<8.5041617/0 in Hex.SCM.prefetch/1>
    Args: []

17:08:54.679 [error] Task #PID<0.434.0> started from :hex_fetcher terminating
** (stop) exited in: GenServer.call(Hex.Registry.Server, {:outer_checksum, "hexpm", "mime", "2.0.5"}, 60000)
    ** (EXIT) an exception was raised:
        ** (Mix.Error) Package hexpm/heap not prefetched, please report this issue
            (mix 1.14.2) lib/mix.ex:513: Mix.raise/2
            (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (hex 2.0.6) lib/hex/scm.ex:397: Hex.SCM.fetch/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<8.5041617/0 in Hex.SCM.prefetch/1>
    Args: []

17:08:54.679 [error] Task #PID<0.436.0> started from :hex_fetcher terminating
** (stop) exited in: GenServer.call(Hex.Registry.Server, {:outer_checksum, "hexpm", "jason", "1.4.0"}, 60000)
    ** (EXIT) an exception was raised:
        ** (Mix.Error) Package hexpm/heap not prefetched, please report this issue
            (mix 1.14.2) lib/mix.ex:513: Mix.raise/2
            (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (hex 2.0.6) lib/hex/scm.ex:397: Hex.SCM.fetch/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<8.5041617/0 in Hex.SCM.prefetch/1>
    Args: []

17:08:54.679 [error] Task #PID<0.441.0> started from :hex_fetcher terminating
** (stop) exited in: GenServer.call(Hex.Registry.Server, {:outer_checksum, "hexpm", "poison", "5.0.0"}, 60000)
    ** (EXIT) an exception was raised:
        ** (Mix.Error) Package hexpm/heap not prefetched, please report this issue
            (mix 1.14.2) lib/mix.ex:513: Mix.raise/2
            (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (hex 2.0.6) lib/hex/scm.ex:397: Hex.SCM.fetch/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<8.5041617/0 in Hex.SCM.prefetch/1>
    Args: []

17:08:54.679 [error] Task #PID<0.437.0> started from :hex_fetcher terminating
** (stop) exited in: GenServer.call(Hex.Registry.Server, {:outer_checksum, "hexpm", "unicode_util_compat", "0.7.0"}, 60000)
    ** (EXIT) an exception was raised:
        ** (Mix.Error) Package hexpm/heap not prefetched, please report this issue
            (mix 1.14.2) lib/mix.ex:513: Mix.raise/2
            (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (hex 2.0.6) lib/hex/scm.ex:397: Hex.SCM.fetch/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<8.5041617/0 in Hex.SCM.prefetch/1>
    Args: []
```    

### Expected behavior

Deps are updated correctly

**Comment by josevalim** [comment]
Can you please file this in hex? Perhaps even send them a PR to link to the Hex issues tracker in the error message. :)
