### ISSUE TITLE
Formatter not loading plugins in subdirectory consistently when run from umbrella root

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12880]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 25)

### Operating system

macOS, linux

### Current behavior

Repro:
1. git clone git@github.com:lukaszsamson/elixir_bug_formatter_plugin.git
2. cd elixir_bug_formatter_plugin
3. mix deps.get
4. mix format --check-formatted
```
** (Mix) mix format failed due to --check-formatted.
The following files are not formatted:

/dir/elixir_bug_formatter_plugin/apps/backoffice/lib/backoffice/templates/some/index.html.heex
```
5. mix clean
6. mix format --check-formatted
no error
7. cd apps/backoffice
8. mix format --check-formatted
```
** (Mix) mix format failed due to --check-formatted.
The following files are not formatted:

/dir/elixir_bug_formatter_plugin/apps/backoffice/lib/backoffice/templates/some/index.html.heex
```

It works consistently if I add
```
plugins: [Phoenix.LiveView.HTMLFormatter],
```
to root `.formatter.exs`

### Expected behavior

https://hexdocs.pm/mix/main/Mix.Tasks.Format.html#module-formatting-options state about subdirectories:
> Configuration between .formatter.exs are not shared nor inherited.

Nothing about interaction between subdirectories and plugins is stated in plugins section.

My expectation is that running formatter in a subdirectory should be equivalent with running it in root. Moreover, it should behave consistently and not depend on wether `mix clean` has been run.

**Comment by josevalim** [comment]
I am afraid you have not push the reproduction repo yet. :)

**Comment by lukaszsamson** [comment]
oh, I accidentally made it private. Should work now

**Comment by lukaszsamson** [comment]
Possibly another manifestation of the problem. When running from the root
```
mix format
mix format failed for file: apps/backend/lib/backend/components/core_components.ex
** (UndefinedFunctionError) function Phoenix.LiveView.HTMLFormatter.format/2 is undefined (module Phoenix.LiveView.HTMLFormatter is not available)
    Phoenix.LiveView.HTMLFormatter.format("<div>...</div>\n", [file: "/myapp/apps/backend/lib/backend/components/core_components.ex", line: 9, sigil: :H, modifiers: [], opening_delimiter: "\"\"\"", import_deps: [:ecto, :ecto_sql, :phoenix, :absinthe], plugins: [Phoenix.LiveView.HTMLFormatter, Absinthe.Formatter], inputs: ["*.{heex,ex,exs}", "{config,lib,test}/**/*.{heex,ex,exs}", "{lib,priv}/**/*.{gql,graphql}"]])
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.15.4) lib/code/formatter.ex:1356: Code.Formatter.maybe_sigil_to_algebra/4
    (elixir 1.15.4) lib/code/formatter.ex:490: Code.Formatter.quoted_to_algebra/3
    (elixir 1.15.4) lib/code/formatter.ex:579: anonymous fn/3 in Code.Formatter.block_args_to_algebra/4
    (elixir 1.15.4) lib/code/formatter.ex:1987: Code.Formatter.each_quoted_to_algebra_without_comments/4
    (elixir 1.15.4) lib/code/formatter.ex:1973: Code.Formatter.quoted_to_algebra_with_comments/6
    (elixir 1.15.4) lib/code/formatter.ex:584: Code.Formatter.block_args_to_algebra/4
```
when running from app/backend it works

root .formatter
```
[
  inputs: ["mix.exs", "config/*.exs", "rel/*.exs", ".formatter.exs", ".dialyzer_ignore.exs"],
  subdirectories: ["apps/*"]
]
```
umbrella child .formatter
```
[
  import_deps: [:ecto, :ecto_sql, :phoenix, :absinthe],
  plugins: [Phoenix.LiveView.HTMLFormatter, Absinthe.Formatter],
  inputs: [
    "*.{heex,ex,exs}",
    "{config,lib,test}/**/*.{heex,ex,exs}",
    "{lib,priv}/**/*.{gql,graphql}"
  ]
]
```

**Comment by josevalim** [comment]
That makes sense. We cannot cache anonymous functions. :( I will take another look.
