### ISSUE TITLE
Make test is failing on Arch Linux

### ISSUE THREAD

**Issue by Antiz96** [elixir-lang/elixir#12975]
### Elixir and Erlang/OTP versions

Elixir version 1.15.6
Erlang version 26.1.1

### Operating system

Arch Linux

### Current behavior

When trying to build Elixir on Arch Linux (using a clean chroot), tests are failing with [these errors](https://gist.githubusercontent.com/Antiz96/a13f3fe7c733e8fbe08b8a5001f53a25/raw/cb974e25313699e82dcf92d1e63855b445aba142/Test%2520logs) (using `make test`):

```
==> elixir (eunit)
  All 132 tests passed.

==> elixir (ex_unit)
Excluding tags: [windows: true]

.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Finished in 27.1 seconds (10.3s on load, 10.8s async, 5.9s sync)
1975 doctests, 4259 tests, 0 failures, 13 excluded

Randomized with seed 713238
==> ex_unit (ex_unit)
.......................................

  1) test starts a supervised process with ID checks (ExUnit.SupervisedTest)
     test/ex_unit/supervised_test.exs:74
     match (=) failed
     The following variables were pinned:
       pid = #PID<0.453.0>
     code:  assert {:error, {{:already_started, ^pid}, _}} = start_supervised({MyAgent, 0}, id: :another)
     left:  {:error, {{:already_started, ^pid}, _}}
     right: {:error, {:duplicate_child_name, :another}}
     stacktrace:
       test/ex_unit/supervised_test.exs:80: (test)

..........................................................................................................................................................................................................................................

  2) test inspect failure (ExUnit.FormatterTest)
     test/ex_unit/formatter_test.exs:491
     Assertion with =~ failed
     code:  assert format_test_failure(test(), failure, 1, 80, &formatter/2) =~ "  1) world (Hello)
                 test/ex_unit/formatter_test.exs:1
                 Assertion with == failed
                 code:  assert :will_fail == %BadInspect{}
                 left:  :will_fail
                 right: #Inspect.Error<
            #{message}"
     left:  "  1) world (Hello)\n     test/ex_unit/formatter_test.exs:1\n     Assertion with == failed\n     code:  assert :will_fail == %BadInspect{}\n     left:  :will_fail\n     right: #Inspect.Error<\n  got FunctionClauseError with message:\n\n      \"\"\"\n      no function clause matching in Inspect.ExUnit.FormatterTest.BadInspect.inspect/2\n      \"\"\"\n\n  while inspecting:\n\n      %{key: 0, __struct__: ExUnit.FormatterTest.BadInspect}\n\n  Stacktrace:\n\n    test/ex_unit/formatter_test.exs:485: Inspect.ExUnit.FormatterTest.BadInspect.inspect(%{key: 0, __struct__: ExUnit.FormatterTest.BadInspect}, %Inspect.Opts{base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, custom_options: [], inspect_fun: &Inspect.inspect/2, limit: 50, pretty: false, printable_limit: 4096, safe: true, structs: true, syntax_colors: [], width: 68})\n    (elixir 1.15.6) lib/inspect/algebra.ex:348: Inspect.Algebra.to_doc/2\n    (ex_unit 1.15.6) lib/ex_unit/formatter.ex:502: ExUnit.Formatter.inspect_multiline/3\n    (ex_unit 1.15.6) lib/ex_unit/formatter.ex:343: ExUnit.Formatter.format_sides/6\n    (ex_unit 1.15.6) lib/ex_unit/formatter.ex:318: ExUnit.Formatter.format_assertion_diff/4\n    (ex_unit 1.15.6) lib/ex_unit/formatter.ex:247: ExUnit.Formatter.format_exception/6\n    (ex_unit 1.15.6) lib/ex_unit/formatter.ex:161: anonymous fn/7 in ExUnit.Formatter.format_test_failure/5\n    (elixir 1.15.6) lib/enum.ex:1794: anonymous fn/2 in Enum.map_join/3\n    (elixir 1.15.6) lib/enum.ex:4369: Enum.map_intersperse_list/3\n    (elixir 1.15.6) lib/enum.ex:1794: Enum.map_join/3\n    (ex_unit 1.15.6) lib/ex_unit/formatter.ex:160: ExUnit.Formatter.format_test_failure/5\n    test/ex_unit/formatter_test.exs:508: ExUnit.FormatterTest.\"test inspect failure\"/1\n    (ex_unit 1.15.6) lib/ex_unit/runner.ex:463: ExUnit.Runner.exec_test/2\n    (stdlib 5.1) timer.erl:270: :timer.tc/2\n    (ex_unit 1.15.6) lib/ex_unit/runner.ex:385: anonymous fn/5 in ExUnit.Runner.spawn_test_monitor/4\n\n>\n"
     right: "  1) world (Hello)\n     test/ex_unit/formatter_test.exs:1\n     Assertion with == failed\n     code:  assert :will_fail == %BadInspect{}\n     left:  :will_fail\n     right: #Inspect.Error<\n  got FunctionClauseError with message:\n\n      \"\"\"\n      no function clause matching in Inspect.ExUnit.FormatterTest.BadInspect.inspect/2\n      \"\"\"\n\n  while inspecting:\n\n      %{__struct__: ExUnit.FormatterTest.BadInspect, key: 0}\n\n  Stacktrace:\n"
     stacktrace:
       test/ex_unit/formatter_test.exs:508: (test)

.............................................................................................................................................
Finished in 3.1 seconds (1.4s on load, 0.2s async, 1.4s sync)
44 doctests, 372 tests, 2 failures

Randomized with seed 498823
make: *** [Makefile:113: test_ex_unit] Error 2
[1m[31m==> ERROR:[m[1m A failure occurred in check().[m
[1m    Aborting...[m
```
Here's the [PKGBUILD used to compile/package Elixir](https://gist.githubusercontent.com/Antiz96/a13f3fe7c733e8fbe08b8a5001f53a25/raw/cb974e25313699e82dcf92d1e63855b445aba142/PKGBUILD):
```
# Maintainer: Johannes Löthberg <johannes@kyriasis.com>
# Maintainer: Robin Candau <antiz@archlinux.org>
# Contributor: Sergej Pupykin <arch+pub@sergej.pp.ru>
# Contributor: Gilbert Kennen <gilbert firewatcher org>

pkgname=elixir
pkgver=1.15.6
pkgrel=1

pkgdesc="a functional meta-programming aware language built on top of the Erlang VM"
url="https://elixir-lang.org"
license=('Apache' 'custom:EPL')

arch=('any')

depends=('erlang-nox')
checkdepends=('git')

source=("$pkgname-$pkgver.tar.gz::https://github.com/elixir-lang/elixir/archive/v$pkgver.tar.gz")
sha256sums=('385fc1958bcf9023a748acf8c42179a0c6123c89744396840bdcd661ee130177')

build() {
  cd elixir-"$pkgver"
  make
}

check() {
  cd elixir-"$pkgver"
  ERL_EPMD_PORT=5369 make test

  # The elixir test suite starts up epmd and then doesn't kill it again afterwards.
  epmd -port 5369 -kill
}

package() {
  cd elixir-"$pkgver"
  mkdir -p "$pkgdir"/usr/share/licenses/"$pkgname"
  install -Dm644 LICENSE "$pkgdir"/usr/share/licenses/"$pkgname"
  make DESTDIR="$pkgdir" PREFIX=/usr install
}
```

I'm facing this issue trying to build older versions of Elixir too (I tried until v1.15.0). I also tried to build Elixir against both Erlang v26.1 and v26.1.1 and encountered the same behavior. So I'm doubting the issue comes from a specific version of Elixir/Erlang?

Instructions to reproduce this issue (requires an Arch Linux environment):
```
sudo pacman -S devtools
curl https://gist.githubusercontent.com/Antiz96/a13f3fe7c733e8fbe08b8a5001f53a25/raw/cb974e25313699e82dcf92d1e63855b445aba142/PKGBUILD -O
pkgctl build
```

### Expected behavior

Working tests.

I'm a bit clueless about what is causing this issue at the moment, but I remain available if you need any additional information!  
Thanks in advance! :smile:

**Comment by josevalim** [comment]
I can reproduce both of them on Erlang OTP 26.1, I will push a fix shortly. :) But those are failures only in the tests I beleive.

**Comment by Antiz96** [comment]
> I can reproduce both of them on Erlang OTP 26.1, I will push a fix shortly. :) But those are failures only in the tests I beleive.

Yes, those failures seems to only be about the tests indeed, but it would be nice to have them working for our Elixir package.
Thanks for your quick reply though! I'll wait for the fix :)

**Comment by Antiz96** [comment]
I confirm that https://github.com/elixir-lang/elixir/commit/60efbf751d3bedbe1851ac8c701a807d66fe340d fixes the issue!
Thanks for your quick actions! :)
