### ISSUE TITLE
Crash in ixe when getting info about dynamic() type

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#13005]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.6 (compiled with Erlang/OTP 26)

### Operating system

macOS

### Current behavior

```
iex(1)> t :erlang.term()   
@type term() :: any()

All possible Erlang terms. Synonym for any().

iex(2)> t :erlang.terms()
No type information for :erlang.terms was found or :erlang.terms is private

iex(3)> t :erlang.nonempty_binary()
@type nonempty_binary() :: <<_::8, _::_*8>>

A binary() (erts:erlang#binary) that contains some data.

iex(4)> t :erlang.dynamic()        
** (MatchError) no match of right hand side value: nil
    (iex 1.15.6) lib/iex/introspection.ex:739: IEx.Introspection.type_doc/4
    (iex 1.15.6) lib/iex/introspection.ex:694: anonymous fn/3 in IEx.Introspection.t/1
    (elixir 1.15.6) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (iex 1.15.6) lib/iex/introspection.ex:692: IEx.Introspection.t/1
    iex:12: (file)
```

It seems dynamic type is not rendered into EEP48 OTP docs

```
1> ht(erlang, any).

  -type any() :: any().

  All possible Erlang terms. Synonym for term().
ok
2> ht(erlang, dynamic).
{error,type_missing}
```

### Expected behavior

no crash?

**Comment by josevalim** [comment]
Thank you, this is addressed in main. :)

```
iex(2)> t :erlang.dynamic
No type information for :erlang.dynamic was found or :erlang.dynamic is private
```
