### ISSUE TITLE
Restarting server failed

### ISSUE THREAD

**Issue by formingform** [elixir-lang/elixir#13152]
### Elixir and Erlang/OTP versions

Elixir & Erlang versions (elixir --version): 1.14.5 (compiled with Erlang/OTP 25)

### Operating system

Ubuntu 22.04 in WINDOWS 11 WLS2

### Current behavior

VsCode prompt: - Restarting server failed. 
VsCode output:

```
Running /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/launch.sh
Preferred shell is bash, relaunching
Looking for ASDF install
ASDF install found in /home/joey/.asdf/asdf.sh, sourcing
Installing ElixirLS release v0.17.10
Running in /home/joey/github.com/formingform/blockscout
* Updating elixir_ls (https://github.com/elixir-lsp/elixir-ls.git - v0.17.10)
==> language_server
Could not find Hex, which is needed to build dependency :stream_data
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
Mix.install failed with ** (Mix.Error) request timed out after 60000ms

Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.

Alternatively, you can compile and install Hex directly with this command:

    mix archive.install github hexpm/hex branch latest

    (mix 1.14.5) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.5) lib/mix/local.ex:145: Mix.Local.find_matching_versions_from_signed_csv!/3
    (mix 1.14.5) lib/mix/tasks/local.hex.ex:72: Mix.Tasks.Local.Hex.run_install/2
    (mix 1.14.5) lib/mix/dep/loader.ex:187: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.14.5) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.14.5) lib/mix/dep/loader.ex:358: Mix.Dep.Loader.mix_children/2

Retrying Mix.install with force: true
Installing ElixirLS release v0.17.10
Running in /home/joey/github.com/formingform/blockscout
* Getting elixir_ls (https://github.com/elixir-lsp/elixir-ls.git - v0.17.10)
==> language_server
Could not find Hex, which is needed to build dependency :stream_data
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
** (EXIT from #PID<0.96.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.178.0>}}
        (mix 1.14.5) lib/mix/utils.ex:652: Mix.Utils.read_httpc/1
        (mix 1.14.5) lib/mix/utils.ex:579: anonymous fn/2 in Mix.Utils.read_path/2
        (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
        (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
        (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

[Error - 6:10:00 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:10:00 PM] Connection to server got closed. Server will restart.
true
[Error - 6:10:00 PM] ElixirLS - blockscout client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Running /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/launch.sh
Preferred shell is bash, relaunching
Looking for ASDF install
ASDF install found in /home/joey/.asdf/asdf.sh, sourcing
Installing ElixirLS release v0.17.10
Running in /home/joey/github.com/formingform/blockscout
* Updating elixir_ls (https://github.com/elixir-lsp/elixir-ls.git - v0.17.10)
```

And I tried to install Hex by different ways:
I tryed to install Hex by this line
```
mix archive.install github hexpm/hex branch latest
```
and got below logs

```
I tryed 3 ways to install Hex:

run cmd "mix local.hex --force"
run cmd: mix archive.install github hexpm/hex branch latest
download ./hex-2.0.6.ez, and run cmd: mix archive.install ./hex-2.0.6.ez.
```

### Expected behavior

vscode-elixir-ls is OK

**Comment by josevalim** [comment]
We are not doing a new v1.14.x release, so I suggest to update to v1.15 then.

**Comment by josevalim** [comment]
Btw, the reason why we didn't backport it is because doing a change to the dependency converger/resolver in a release candidate is a very risky change. It was not intended to be backported and we wouldn't apply it on a patch release most likely either.

The script can either try to install Hex explicitly before hand or require v1.15 :)
