### ISSUE TITLE
Test fails (test/elixir/exception_test.exs:598) when installing via asdf from ref

### ISSUE THREAD

**Issue by pertsevds** [elixir-lang/elixir#13206]
### Elixir and Erlang/OTP versions

```
# asdf current | grep erlang
erlang 26.2.1

# erl -V
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
```

### Operating system

macOS 14.2.1

### Current behavior

To reproduce:
```
asdf install elixir ref:38ddc98fef7faf6f4666703dcd9c99105e6388d2
```

When you use asdf in that way it downloads ref from Github and compiles Elixir from source.

After successful compilation it fails on test stage with this error:
```
20:33:33.996 [error] beam/beam_load.c(180): Error loading module 'Elixir.ENUM':
  module name in object code is 'Elixir.Enum'
...
  1) test blaming annotates undefined function error with module suggestions (ExceptionTest)
     test/elixir/exception_test.exs:598
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:

       1. per test by setting "@tag timeout: x" (accepts :infinity)
       2. per test module by setting "@moduletag timeout: x" (accepts :infinity)
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. by running "mix test --timeout x" which sets timeout
       5. or by running "mix test --trace" which sets timeout to infinity
          (useful when using IEx.pry/0)

     where "x" is the timeout given as integer in milliseconds (defaults to 60_000).

     code: assert blame_message(ENUM, & &1.not_a_function(&1, 1)) ==
     stacktrace:
       (kernel 9.2) code_server.erl:150: :code_server.call/1
       (kernel 9.2) code.erl:190: :code.ensure_loaded/1
       (kernel 9.2) error_handler.erl:40: :error_handler.undefined_function/3
       test/elixir/exception_test.exs:818: ExceptionTest.blame_message/2
       test/elixir/exception_test.exs:624: (test)
       (ex_unit 1.16.0) lib/ex_unit/runner.ex:472: ExUnit.Runner.exec_test/2
       (stdlib 5.2) timer.erl:270: :timer.tc/2
       (ex_unit 1.16.0) lib/ex_unit/runner.ex:394: anonymous fn/6 in ExUnit.Runner.spawn_test_monitor/4
```

I don't know if it's an asdf plugin problem or an Elixir one.

### Expected behavior

Elixir 1.16.0 installed.

**Comment by josevalim** [comment]
That's a regression in Erlang 26.1/26.2 but it has been fixed in https://github.com/erlang/otp/pull/7755.
