### ISSUE TITLE
Can't clear the warnings on yecc and leex, even if added them to compilers in project with credo and dialyxir

### ISSUE THREAD

**Issue by zacky1972** [elixir-lang/elixir#13213]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.16.0 (compiled with Erlang/OTP 26)
```

### Operating system

macOS Sonoma 14.2.1

### Current behavior

I tested the following `mix.exs` after `mix new test_credo && cd test_credo`:

```elixir:mix.exs
defmodule TestCredo.MixProject do
  use Mix.Project

  def project do
    [
      app: :test_credo,
      version: "0.1.0",
      elixir: "~> 1.16",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
      {:credo, "~> 1.7", only: [:dev, :test], runtime: false},
      {:dialyxir, "~> 1.4", only: [:dev, :test], runtime: false}
    ]
  end
end
```

After `mix deps.get` and `mix test`, then I got the warnings:

```elixir
warning: in order to compile .yrl files, you must add "compilers: [:yecc] ++ Mix.compilers()" to the "def project" section of your mix.exs
  (mix 1.16.0) lib/mix/tasks/compile.yecc.ex:70: Mix.Tasks.Compile.Yecc.preload/1
  (mix 1.16.0) lib/mix/compilers/erlang.ex:66: Mix.Compilers.Erlang.compile/6
  (mix 1.16.0) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
  (mix 1.16.0) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
  (mix 1.16.0) lib/mix/tasks/compile.all.ex:104: Mix.Tasks.Compile.All.compile/4
  (mix 1.16.0) lib/mix/tasks/compile.all.ex:93: Mix.Tasks.Compile.All.with_logger_app/2

warning: in order to compile .xrl files, you must add "compilers: [:leex] ++ Mix.compilers()" to the "def project" section of your mix.exs
  (mix 1.16.0) lib/mix/tasks/compile.leex.ex:69: Mix.Tasks.Compile.Leex.preload/1
  (mix 1.16.0) lib/mix/compilers/erlang.ex:66: Mix.Compilers.Erlang.compile/6
  (mix 1.16.0) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
  (mix 1.16.0) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
  (mix 1.16.0) lib/mix/tasks/compile.all.ex:104: Mix.Tasks.Compile.All.compile/4
  (mix 1.16.0) lib/mix/tasks/compile.all.ex:93: Mix.Tasks.Compile.All.with_logger_app/2
```

Then, I edited `mix.exs` as follows:

```elixir:mix.exs
defmodule TestCredo.MixProject do
  use Mix.Project

  def project do
    [
      app: :test_credo,
      version: "0.1.0",
      elixir: "~> 1.16",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      compilers: [:yecc, :leex] ++ Mix.compilers()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
      {:credo, "~> 1.7", only: [:dev, :test], runtime: false},
      {:dialyxir, "~> 1.4", only: [:dev, :test], runtime: false}
    ]
  end
end
```

However, even after editing as above, I still got the warnings after I executed the following commands:

```zsh
mix deps.clean --all
mix deps.get
mix test
```

### Expected behavior

After `mix.exs` is edited as follows,

```elixir:mix.exs
defmodule TestCredo.MixProject do
  use Mix.Project

  def project do
    [
      app: :test_credo,
      version: "0.1.0",
      elixir: "~> 1.16",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      compilers: [:yecc, :leex] ++ Mix.compilers()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
      {:credo, "~> 1.7", only: [:dev, :test], runtime: false},
      {:dialyxir, "~> 1.4", only: [:dev, :test], runtime: false}
    ]
  end
end
```

And then I executed the following commands:

```zsh
mix deps.clean --all
mix deps.get
mix test
```

Then I expected to get no warnings.

**Comment by wojtekmach** [comment]
The warning is most likely coming from not your app but from your dependencies and it needs to be resolved there:

```
iex(1)> Mix.install [:dialyxir]
Resolving Hex dependencies...
Resolution completed in 0.073s
New:
  dialyxir 1.4.2
  erlex 0.2.6
* Getting dialyxir (Hex package)
* Getting erlex (Hex package)
warning: in order to compile .yrl files, you must add "compilers: [:yecc] ++ Mix.compilers()" to the "def project" section of your mix.exs
  (mix 1.17.0-dev) lib/mix/tasks/compile.yecc.ex:70: Mix.Tasks.Compile.Yecc.preload/1
  (mix 1.17.0-dev) lib/mix/compilers/erlang.ex:66: Mix.Compilers.Erlang.compile/6
  (mix 1.17.0-dev) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
  (mix 1.17.0-dev) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
  (mix 1.17.0-dev) lib/mix/tasks/compile.all.ex:104: Mix.Tasks.Compile.All.compile/4
  (mix 1.17.0-dev) lib/mix/tasks/compile.all.ex:93: Mix.Tasks.Compile.All.with_logger_app/2
```

**Comment by josevalim** [comment]
@wojtekmach is correct on this one. :) I will improve the warning to mention the app.

**Comment by sabiwara** [comment]
For those reaching this issue, here is the related dialyxir issue: https://github.com/jeremyjh/dialyxir/issues/534
