### ISSUE TITLE
String.capitalize/1 fails with a string containing only a number 

### ISSUE THREAD

**Issue by nicklayb** [elixir-lang/elixir#13267]
### Elixir and Erlang/OTP versions

Elixir 1.16.0 (asdf build `1.16.0-otp-24`)
Erlang/OTP 24.3.4.15

### Operating system

macOS 14.1.1

### Current behavior

When calling `String.capitalize/1` with only `0` to `9` as string, it raises with the following error:
```
iex(1)> String.capitalize("1")
** (FunctionClauseError) no function clause matching in String.downcase/2

    The following arguments were given to String.downcase/2:

        # 1
        []

        # 2
        :default

    Attempted function clauses (showing 4 out of 4):

        def downcase("", _mode)
        def downcase(string, :default) when is_binary(string)
        def downcase(string, :ascii) when is_binary(string)
        def downcase(string, mode) when is_binary(string) and (mode === :greek or mode === :turkic)

    (elixir 1.16.0) lib/string.ex:902: String.downcase/2
    (elixir 1.16.0) lib/string.ex:970: String.capitalize/2
```

### Expected behavior

It should just return `"1"` if it receives `"1"`

**Comment by whatyouhide** [comment]
This is not failing on OTP 26 though

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Interactive Elixir (1.16.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> String.capitalize("1")
"1"
```

**Comment by nicklayb** [comment]
It doesn't fail either with `elixir 1.15.0` and `OTP 24` or `elixir 1.16.0` and `OTP 25`.

Seems like a probleme specifically for 1.16.0 and OTP 24
