### ISSUE TITLE
String.capitalize broken for single character on Elixir 1.16.0(Erlang 24.0)

### ISSUE THREAD

**Issue by goodhamgupta** [elixir-lang/elixir#13273]
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.3.2.6] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.16.0 (compiled with Erlang/OTP 24)

### Operating system

ProductName: macOS, ProductVersion: 14.2.1 BuildVersion: 23C71

### Current behavior

In Elixir 1.16.0, `String.capitalize` fails for a single character.

Eg:

```ex
iex(1)> String.capitalize("elixir") # Correct output
"Elixir"

iex(2)> String.capitalize("e") # Incorrect output
** (FunctionClauseError) no function clause matching in String.downcase/2

    The following arguments were given to String.downcase/2:

        # 1
        []

        # 2
        :default

    Attempted function clauses (showing 4 out of 4):

        def downcase("", _mode)
        def downcase(string, :default) when is_binary(string)
        def downcase(string, :ascii) when is_binary(string)
        def downcase(string, mode) when is_binary(string) and (mode === :greek or mode === :turkic)

    (elixir 1.16.0) lib/string.ex:902: String.downcase/2
    (elixir 1.16.0) lib/string.ex:970: String.capitalize/2
```

Elixir version was installed using asdf:

```sh
asdf install erlang 24.0
asdf install elixir 1.16.0
```

### Expected behavior

The function works as expected on Elixir 1.15.

```ex
iex(1)> String.capitalize("e")
"E"
```

**Comment by josevalim** [comment]
This has been fixed in main and v1.16 branches already. :) Thank you.
