### ISSUE TITLE
Elixir script always crash when using with Mix.install

### ISSUE THREAD

**Issue by wingyplus** [elixir-lang/elixir#13347]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.16.1 (compiled with Erlang/OTP 26)

### Operating system

macOS 14.3

### Current behavior

I have a script.

```elixir
# date_diff.exs
Mix.install([:sourceror], verbose: true)

defmodule Main do
  def run() do
    Path.wildcard("apps/**/{lib,test}/**/*.{ex,exs}")
    |> Enum.reject(&String.contains?(&1, "deps"))
    |> Enum.reject(&String.contains?(&1, "_build"))
    |> Enum.map(&{&1, parse_file!(&1)})
    |> Enum.map(&do_refactor/1)
    |> Enum.map(&write_file/1)
  end

  def parse_file!(file) do
    file
    |> File.read!()
    |> Sourceror.parse_string!()
  end

  def write_file({file, source}) do
    File.write!(file, source)
  end

  def do_refactor({file, source}) do
    new_source =
      Macro.postwalk(source, fn
        {{:., dot_meta,
          [
            {:__aliases__, aliases_meta, [:Timex]},
            :diff
          ]}, meta, [v1, v2, _]} ->
          {{:., dot_meta,
            [
              {:__aliases__, aliases_meta, [:Date]},
              :diff
            ]}, meta, [v1, v2]}

        ast ->
          ast
      end)

    {file, Sourceror.to_string(new_source)}
  end
end

Main.run()
```

When running `elixir date_diff.exs`. I got the following error:

```
Mix.install/2 using /Users/thanabodee/Library/Caches/mix/installs/elixir-1.16.1-erts-14.2.1/e8c83a324e5ad6e12dc4e2bd0c488496
Resolving Hex dependencies...
Resolution completed in 0.009s
New:
  sourceror 1.0.1
* Getting sourceror (Hex package)
==> sourceror
Compiling 11 files (.ex)
Generated sourceror app
** (exit) exited in: GenServer.call(Hex.UpdateChecker, :check, 120000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.16.1) lib/gen_server.ex:1103: GenServer.call/3
    (hex 2.0.6) lib/hex/update_checker.ex:26: Hex.UpdateChecker.check/0
    (hex 2.0.6) lib/hex/remote_converger.ex:9: Hex.RemoteConverger.post_converge/0
    (mix 1.16.1) lib/mix/dep/converger.ex:90: Mix.Dep.Converger.converge/4
    (mix 1.16.1) lib/mix/dep/converger.ex:72: Mix.Dep.Converger.converge/1
    (mix 1.16.1) lib/mix/dep.ex:156: Mix.Dep.converge_and_load/1
    (mix 1.16.1) lib/mix/project.ex:570: Mix.Project.traverse_deps/2
    (mix 1.16.1) lib/mix/tasks/format.ex:412: Mix.Tasks.Format.eval_deps_opts/1
```

### Expected behavior

The script should work fine and not raise exception like this.

**Comment by josevalim** [comment]
Does it raise immediately or does it raise after some time (after roughly 2 minutes)? Can you run `mix local.hex` before?

**Comment by josevalim** [comment]
Thank you, I was able to reproduce it after adding a fake file to the directory you are running sourceror. I am trying to isolate it.

**Comment by josevalim** [comment]
Here is a minimal repro:

```
Mix.install([:sourceror], verbose: true)

Mix.Tasks.Format.run([__ENV__.file])
```

**Comment by wingyplus** [comment]
@josevalim Got the same error 👍 

```
$ cat try.exs
Mix.install([:sourceror], verbose: true)

Mix.Tasks.Format.run([__ENV__.file])
$ elixir try.exs
Mix.install/2 using /Users/thanabodee/Library/Caches/mix/installs/elixir-1.16.1-erts-14.2.1/e8c83a324e5ad6e12dc4e2bd0c488496
** (exit) exited in: GenServer.call(Hex.UpdateChecker, :check, 120000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.16.1) lib/gen_server.ex:1103: GenServer.call/3
    (hex 2.0.6) lib/hex/update_checker.ex:26: Hex.UpdateChecker.check/0
    (hex 2.0.6) lib/hex/remote_converger.ex:9: Hex.RemoteConverger.post_converge/0
    (mix 1.16.1) lib/mix/dep/converger.ex:90: Mix.Dep.Converger.converge/4
    (mix 1.16.1) lib/mix/dep/converger.ex:72: Mix.Dep.Converger.converge/1
    (mix 1.16.1) lib/mix/dep.ex:156: Mix.Dep.converge_and_load/1
    (mix 1.16.1) lib/mix/project.ex:570: Mix.Project.traverse_deps/2
    (mix 1.16.1) lib/mix/tasks/format.ex:412: Mix.Tasks.Format.eval_deps_opts/1
```

**Comment by josevalim** [comment]
Fixed here: https://github.com/hexpm/hex/pull/1015

Meanwhile you can add this to fix it:

```
Mix.install([:sourceror], verbose: true)
Mix.RemoteConverger.register(nil)
```

**Comment by josevalim** [comment]
Please follow up on the Hex PR. :)

**Comment by wingyplus** [comment]
Thank you
