### ISSUE TITLE
IEx not able to connect to EPMD

### ISSUE THREAD

**Issue by rauann** [elixir-lang/elixir#13971]
### Elixir and Erlang/OTP versions

Tested on both:
```shell
❯ elixir --version
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:11:11] [ds:11:11:10] [async-threads:1] [jit]

Elixir 1.16.0 (compiled with Erlang/OTP 26)
```

```shell
 elixir --version
Erlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:11:11] [ds:11:11:10] [async-threads:1]

Elixir 1.17.2 (compiled with Erlang/OTP 27)
```

### Operating system

macOS

### Current behavior

I have [epmd](https://www.erlang.org/docs/26/man/epmd) running locally and Livebook is able to connect to it:
```
❯ epmd -d
epmd: Wed Nov  6 09:01:39 2024: epmd running - daemon = 0
epmd: Wed Nov  6 09:02:00 2024: ** got ALIVE2_REQ
epmd: Wed Nov  6 09:02:00 2024: registering 'livebook_wx2vp6xi:1730894521', port 50658
epmd: Wed Nov  6 09:02:00 2024: type 77 proto 0 highvsn 6 lowvsn 5
epmd: Wed Nov  6 09:02:00 2024: ** sent ALIVE2_RESP for "livebook_wx2vp6xi"

❯ epmd -names
epmd: up and running on port 4369 with data:
name livebook_wx2vp6xi at port 50658
```

But other IEx sessions stopped being able to connect to `epmd`:
```
iex(1)> :erl_epmd.names
{:error, :address}
```

### Expected behavior

IEx should be able to connect to EPMD when EPMD is running.

**Comment by josevalim** [comment]
Can you please provide step by step to reproduce it? Which steps are you using to start IEx?

**Comment by rauann** [comment]
> Can you please provide step by step to reproduce it? Which steps are you using to start IEx?

I am starting IEx normally under a project with `iex -S mix` or with `iex --sname foo -S mix phx.server` to try starting epmd.

Worth mention that one of my apps is using [libcluster local epmd](https://github.com/bitwalker/libcluster/blob/main/lib/strategy/local_epmd.ex) strategy and the first time I noticed this issue was when an attempt to start the app with `iex -S mix` resulted in this error:
```
** (Mix) Could not start application core: BoFH.Core.Application.start(:normal, []) returned an error: shutdown: failed to start child: Cluster.Supervisor
    ** (EXIT) shutdown: failed to start child: :local
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, :address}
                (libcluster 3.3.3) lib/strategy/local_epmd.ex:34: Cluster.Strategy.LocalEpmd.discover_nodes/0
                (libcluster 3.3.3) lib/strategy/local_epmd.ex:25: Cluster.Strategy.LocalEpmd.start_link/1
                (stdlib 5.2) supervisor.erl:420: :supervisor.do_start_child_i/3
                (stdlib 5.2) supervisor.erl:406: :supervisor.do_start_child/2
                (stdlib 5.2) supervisor.erl:390: anonymous fn/3 in :supervisor.start_children/2
                (stdlib 5.2) supervisor.erl:1258: :supervisor.children_map/4
                (stdlib 5.2) supervisor.erl:350: :supervisor.init_children/2
                (stdlib 5.2) gen_server.erl:980: :gen_server.init_it/2
                (stdlib 5.2) gen_server.erl:935: :gen_server.init_it/6
                (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
make: *** [debug] Error 1
```

I am able to "fix" the issue after restarting my machine but some time later it happens again.

**Comment by rauann** [comment]
I figured out that it is related to a SDP gateway tool I have to use. When it is running epmd can't be reached locally.

Thank you for the help @josevalim.
