### ISSUE TITLE
ExUnit crash with erlang 27.2: "the device has terminated"

### ISSUE THREAD

**Issue by MrYawe** [elixir-lang/elixir#14106]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 27 [erts-15.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.18.0 (compiled with Erlang/OTP 27)
```

### Operating system

macOS Sonoma 14.7 (23H124)

### Current behavior

In my Phoenix app, a simple test with `dbg()` run with `mix test test/parrot/simple_test.exs` always crash:

The test:
```elixir
defmodule Parrot.SimpleTest do
  use Parrot.DataCase, async: true

  test "simple test" do
    dbg("Hello World")
  end
end
```

The error:
```
15:23:44.246 [error] GenServer #PID<0.805.0> terminating
** (stop) exited in: GenServer.stop(#PID<0.808.0>, :normal, :infinity)
    ** (EXIT) exited in: :sys.terminate(#PID<0.808.0>, :normal, :infinity)
        ** (EXIT) an exception was raised:
            ** (ErlangError) Erlang error: :terminated:

  * 1st argument: the device has terminated

                (stdlib 6.2) io.erl:198: :io.put_chars(:standard_io, ["\n", 10])
                (ex_unit 1.18.0) lib/ex_unit/cli_formatter.ex:381: ExUnit.CLIFormatter.print_failure/2
                (ex_unit 1.18.0) lib/ex_unit/cli_formatter.ex:130: ExUnit.CLIFormatter.handle_cast/2
                (stdlib 6.2) gen_server.erl:2371: :gen_server.try_handle_cast/3
                (stdlib 6.2) gen_server.erl:2433: :gen_server.handle_msg/6
                (stdlib 6.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.801.0>, {{{:terminated, [{:io, :put_chars, [:standard_io, ["\n", 10]], [file: ~c"io.erl", line: 198, error_info: %{cause: {:io, :terminated}, module: :erl_stdlib_errors}]}, {ExUnit.CLIFormatter, :print_failure, 2, [file: ~c"lib/ex_unit/cli_formatter.ex", line: 381]}, {ExUnit.CLIFormatter, :handle_cast, 2, [file: ~c"lib/ex_unit/cli_formatter.ex", line: 130]}, {:gen_server, :try_handle_cast, 3, [file: ~c"gen_server.erl", line: 2371]}, {:gen_server, :handle_msg, 6, [file: ~c"gen_server.erl", line: 2433]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 329]}]}, {:sys, :terminate, [#PID<0.808.0>, :normal, :infinity]}}, {GenServer, :stop, [#PID<0.808.0>, :normal, :infinity]}}}
```

ExUnit is started with:
```elixir
ExUnit.start(capture_log: true, exclude: [:skip, :slow])
```

Everything works fine:
* If I run all tests with `mix test`
* If I replace `dbg("Hello World")` with `IO.inspect("Hello World")`
* If I run exact same test in elixir 1.7.x with `mix test test/parrot/simple_test.exs`

I'm currently trying to reproduce it in a new elixir app to share it here.

### Expected behavior

The test doesn't crash.

**Comment by josevalim** [comment]
Hi @MrYawe, thanks for the report!

Unfortunately I cannot reproduce it. Here is what I did:

1. mix new sample
2. Added this to `test/sample_test.exs`:

```
defmodule SampleTest do
  use ExUnit.Case, async: true

  test "simple test" do
    dbg("Hello World")
  end
end
```

3. Added this to `test/test_helper.exs`: `ExUnit.start(capture_log: true, exclude: [:skip, :slow])`
4. Ran `mix test`

Can you reproduce it with the above? If not, can you try to provide a minimum case? Thank you!

**Comment by MrYawe** [comment]
@josevalim When starting my phoenix project with `iex -S mix` with `erlang 27.2`

```elixir
iex(4)> dbg("Hello")
*** ERROR: Shell process terminated! (^G to start new job) ***
17:46:42.324 [error] Process #PID<0.70.0> raised an exception
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, :livebook_get_evaluation_file)
    (kernel 10.2) group.erl:1281: :group.type/1
    (kernel 10.2) group.erl:1271: :group.log_io_request/3
    (kernel 10.2) group.erl:227: :group.io_request/6
    (kernel 10.2) group.erl:153: :group.server_loop/3
```

Something weird is happening here with livebook. Note that livebook is not a dependency of my application.

**Comment by MrYawe** [comment]
@josevalim Ok the issue comes from [kino](https://github.com/livebook-dev/kino), both of my issues are solved by removing it from my deps.

I will create an issue there. Thanks for the help!
