### ISSUE TITLE
Language Server Crash

### ISSUE THREAD

**Issue by guessthepw** [elixir-lang/elixir#14110]
### Elixir and Erlang/OTP versions

Elixir 1.18.0 (compiled with Erlang/OTP 27)

### Operating system

Mac OS 15.2

### Current behavior

# Summary

I am using Zed as my editor (confirmed the same in VS Code), it starts to compile my project, but raises an exception and terminates. I confirmed the language server is being built and run with the same elixir version I have installed.

```
Terminating Elixir.ElixirLS.LanguageServer.Server: an exception was raised:
    ** (KeyError) key :meta not found in: %{
  line: 57,
  file: "<file path redacted>",
  column: 37,
  formatted_type: "dynamic({:error, %{..., id: term(), reason: term()}})",
  formatted_expr: "{:error, %{id: _, reason: _}} = http_error",
  hints: []
}
        (language_server 0.25.0) lib/language_server/diagnostics.ex:475: anonymous fn/5 in ElixirLS.LanguageServer.Diagnostics.build_related_information/3
        (elixir 1.18.0) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
        (language_server 0.25.0) lib/language_server/diagnostics.ex:472: ElixirLS.LanguageServer.Diagnostics.build_related_information/3
        (language_server 0.25.0) lib/language_server/diagnostics.ex:343: anonymous fn/4 in ElixirLS.LanguageServer.Diagnostics.publish_file_diagnostics/4
        (elixir 1.18.0) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
        (language_server 0.25.0) lib/language_server/diagnostics.ex:315: ElixirLS.LanguageServer.Diagnostics.publish_file_diagnostics/4
        (language_server 0.25.0) lib/language_server/server.ex:1709: anonymous fn/5 in ElixirLS.LanguageServer.Server.publish_diagnostics/1
        (elixir 1.18.0) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
        (language_server 0.25.0) lib/language_server/server.ex:1665: ElixirLS.LanguageServer.Server.publish_diagnostics/1
        (language_server 0.25.0) lib/language_server/server.ex:1544: ElixirLS.LanguageServer.Server.handle_build_result/3
        (language_server 0.25.0) lib/language_server/server.ex:283: ElixirLS.LanguageServer.Server.handle_cast/2
        (stdlib 6.2) gen_server.erl:2371: :gen_server.try_handle_cast/3
        (stdlib 6.2) gen_server.erl:2433: :gen_server.handle_msg/6
        (stdlib 6.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
        
  ```

### Expected behavior

# Summary

The language server doesn't raise an exception and terminate.

**Comment by josevalim** [comment]
This has been fixed on v1.18 branch and should be fixed in the release coming out tomorrow.

**Comment by guessthepw** [comment]
Awesome, thanks for the quick response.

**Comment by lukaszsamson** [comment]
@guessthepw Please note that elixir 1.18 is not yet supported by ElixirLS. Official support is coming up in ElixirLS v0.26
