### ISSUE TITLE
No function clause matching in Logger.Utils.truncate_n/2

### ISSUE THREAD

**Issue by jeregrine** [elixir-lang/elixir#2675]
``` elixir
Logger.debug ['Sent', 32, 404, 32, 'in', [-7, [181, 115]]]

** (FunctionClauseError) no function clause matching in Logger.Utils.truncate_n/2
     stacktrace:
       (logger) lib/logger/utils.ex:17: Logger.Utils.truncate_n(-7, 8086)
       (logger) lib/logger/utils.ex:46: Logger.Utils.truncate_n_list/3
       (logger) lib/logger/utils.ex:46: Logger.Utils.truncate_n_list/3
       (logger) lib/logger/utils.ex:13: Logger.Utils.truncate/2
       (logger) lib/logger.ex:404: Logger.log/3
       (plug) lib/plug/logger.ex:42: anonymous fn/3 in Plug.Logger.call/2
       (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
       (plug) lib/plug/conn.ex:559: Plug.Conn.run_before_send/2
```

**Comment by mpoeter** [comment]
I just wanted to open a similar issue, but GitHub referred me to this one.

I think `truncate` should handle invalid log data more gracefully - similar to the console logger:
https://github.com/elixir-lang/elixir/blob/43a4c850c4568684aee5f311c358275b15f2df35/lib/logger/lib/logger/backends/console.ex#L237-L242

How about something like this:
```elixir
def truncate(chardata, n) when n >= 0 do
    {chardata, n} = truncate_n(chardata, n)
    if n >= 0, do: chardata, else: [chardata, " (truncated)"]
rescue
  ArgumentError ->
    ["failure while trying to log malformed data: ", inspect(chardata)] |> truncate_n(n)
end
```
