### ISSUE TITLE
Make clean test fails - unexpected error compiling src/elixir_parser.yrl

### ISSUE THREAD

**Issue by kgish** [elixir-lang/elixir#3035]
Tried to run the tests after git clone but get the following error:
```
$ make clean test
cd lib/elixir && ../../rebar clean
==> elixir (clean)
rm -rf ebin
rm -rf lib/*/ebin
rm -rf lib/elixir/test/ebin
rm -rf lib/*/tmp
rm -rf lib/mix/test/fixtures/git_repo
rm -rf lib/mix/test/fixtures/deps_on_git_repo
rm -rf lib/mix/test/fixtures/git_rebar
rm -rf lib/elixir/src/elixir.app.src
==> elixir (compile)
unexpected error compiling src/elixir_parser.yrl
{'EXIT',{undef,[{yecc,file,
                      ["src/elixir_parser.yrl",
                       [{parserfile,"src/elixir_parser.erl"},
                        {report,true},
                        {verbose,false},
                        {return,true}]],
                      []},
                {rebar_erlc_compiler,compile_xrl_yrl,5,
                                     [{file,"src/rebar_erlc_compiler.erl"},
                                      {line,429}]},
                {rebar_base_compiler,compile,3,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,121}]},
                {rebar_base_compiler,compile_worker,3,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,194}]}]}}
ERROR: compile failed while processing /home/kiffin/projects/elixir/github/lib/elixir: rebar_abort
make: *** [erlang] Error 1
```
This is the version of erlang:
```
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
```

**Comment by josevalim** [comment]
How have you installed Erlang? Some Erlang installations split it into many applications, so you need to install them all. Try looking for Erlanger syntax or parser tools package.

**Comment by kgish** [comment]
I installed it on ubuntu 14.04 like this:
```
$ sudo apt-get install erlang erlang-inets erlang-ssl
```
But perhaps that is not enough. Will try downloading from the official erlang download and install.

**Comment by kgish** [comment]
I have the following installed:
```
erlang-base
erlang-crypto
erlang-mode
erlang-solutions
erlang-syntax-tools
```
Doing the make with --debug:
```
Reading makefiles...
Updating goal targets....
 File `default' does not exist.
   File `compile' does not exist.
     File `erlang' does not exist.
    Must remake target `erlang'.
==> elixir (compile)
unexpected error compiling src/elixir_parser.yrl
{'EXIT',{undef,[{yecc,file,
                      ["src/elixir_parser.yrl",
                       [{parserfile,"src/elixir_parser.erl"},
                        {report,true},
                        {verbose,false},
                        {return,true}]],
                      []},
                {rebar_erlc_compiler,compile_xrl_yrl,5,
                                     [{file,"src/rebar_erlc_compiler.erl"},
                                      {line,429}]},
                {rebar_base_compiler,compile,3,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,121}]},
                {rebar_base_compiler,compile_worker,3,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,194}]}]}}
ERROR: compile failed while processing /home/kiffin/projects/elixir/github/lib/elixir: rebar_abort
make: *** [erlang] Error 1
```
Please help.

**Comment by kgish** [comment]
Installed `erlang-parsetools` which helps a little but then this:
```
$ make clean test
cd lib/elixir && ../../rebar clean
==> elixir (clean)
rm -rf ebin
rm -rf lib/*/ebin
rm -rf lib/elixir/test/ebin
rm -rf lib/*/tmp
rm -rf lib/mix/test/fixtures/git_repo
rm -rf lib/mix/test/fixtures/deps_on_git_repo
rm -rf lib/mix/test/fixtures/git_rebar
rm -rf lib/elixir/src/elixir.app.src
==> elixir (compile)
/usr/lib/erlang/lib/parsetools-2.0.12/include/yeccpre.hrl: no such file or directory
/usr/lib/erlang/lib/parsetools-2.0.12/include/yeccpre.hrl:none: no such file or directory
ERROR: compile failed while processing /home/kiffin/projects/elixir/github/lib/elixir: rebar_abort
make: *** [erlang] Error 1
```
I suspect that the default ubuntu erlang packages installed via `sudo apt-get install erlang-xxx` are not compatible with the stuff provided in `erlang-solutions_1.0_all.deb` (ouch).

Can this deb-package be updated to include everything, of course first testing it on ubuntu 14.04.

Am assuming you do test ubuntu also?

**Comment by josevalim** [comment]
This seems to still be a debian package issue. Maybe it is not including source files? Do you have some sort of erlang-dev in there?

**Comment by kgish** [comment]
Thanks for the tip, installed `erlang-dev` as you suggested. Now my list is:
```
erlang-asn1
erlang-base
erlang-crypto
erlang-dev
erlang-inets
erlang-mnesia
erlang-mode
erlang-parsetools
erlang-public-key
erlang-runtime-tools
erlang-solutions
erlang-ssl
erlang-syntax-tools
```


Now I get this far before bailing out:
```
==> iex (compile)
Compiled lib/iex/app.ex
Compiled lib/iex/cli.ex
Compiled lib/iex.ex
Compiled lib/iex/autocomplete.ex
Compiled lib/iex/config.ex
Compiled lib/iex/remsh.ex
Compiled lib/iex/history.ex
Compiled lib/iex/helpers.ex
Compiled lib/iex/evaluator.ex
Compiled lib/iex/server.ex
Compiled lib/iex/introspection.ex
Generated iex.app
lib/elixir/test/erlang/atom_test.erl: undefined parse transform 'eunit_autoexport'
make: *** [lib/elixir/test/ebin/atom_test.beam] Error 1
```
Will keep looking and provide a complete list of required packages when/if I ever succeed.

**Comment by josevalim** [comment]
I am betting you now need something like erlang-eunit. :S

**Comment by kgish** [comment]
Yep you read my mind, that's exactly what I tried ...
```
$ sudo apt-get install erlang-dev erlang-edoc erlang-eunit
```
Getting close, no I make it here:
```
==> elixir (exunit)
...
Randomized with seed 578053
==> ex_unit (exunit)
...

Finished in 2.0 seconds (1.2s on load, 0.7s on tests)
142 tests, 0 failures

Randomized with seed 933965
==> logger (exunit)
...

Finished in 0.8 seconds (0.7s on load, 0.1s on tests)
78 tests, 0 failures

Randomized with seed 743459
==> doctest (exunit)
...

Finished in 5.8 seconds (5.5s on load, 0.2s on tests)
807 tests, 0 failures

Randomized with seed 840644
==> mix (exunit)
.....................................................................................................................................................

  1) test new with tests (Mix.CLITest)
     test/mix/cli_test.exs:124
     Assertion with =~ failed
     code: output =~ "1 tests, 0 failures"
     lhs:  "Compiled lib/new_with_tests.ex\nGenerated new_with_tests.app\nCover compiling modules ... \n** (UndefinedFunctionError) undefined function: :cover.start/0 (module :cover is not available)\n    :cover.start()\n    (mix) lib/mix/tasks/test.ex:7: Mix.Tasks.Test.Cover.start/2\n    (mix) lib/mix/tasks/test.ex:159: Mix.Tasks.Test.run/1\n    (mix) lib/mix/cli.ex:54: Mix.CLI.run_task/2\n    (elixir) lib/code.ex:314: Code.require_file/2\n\n"
     rhs:  "1 tests, 0 failures"
     stacktrace:
       test/mix/cli_test.exs:131: anonymous fn/0 in Mix.CLITest.test new with tests/1
       (elixir) lib/file.ex:1111: File.cd!/2
       test/mix/cli_test.exs:125

..........................................................................................

Finished in 23.3 seconds (3.0s on load, 20.3s on tests)
240 tests, 1 failures

Randomized with seed 549975
make: *** [test_mix] Error 1
```

**Comment by josevalim** [comment]
`erlang-tools` seems to be missing (it is the one that contains cover).

**Comment by rambocoder** [comment]
@kgish good rule of thumb is that anytime you see this in erlang error log:
```
undefined function:
```
that means that an erlang module is not loaded, either because it does not exist in ERL_LIB or the path to it was not passed to iex.

It's too bad in ubuntu you cannot just do:
``` 
sudo apt-get install erlang*
```
due to confilcts, but as @josevalim said, you are missing:
```
sudo apt-get install erlang-common-test erlang-tools
```

**Comment by kgish** [comment]
Good news, all tests finally pass.

The following should be documented for other users wanting to install it on Ubuntu 14.04 LTS.
```
$ sudo apt-get install erlang-dev erlang-ssl erlang-inets erlang-dev \
    erlang-edoc erlang-eunit erlang-tools erlang-common-test
```

**Comment by josevalim** [comment]
@kgish great! As far as I know most people are just rolling with the full erlang install or the erlang solutions one! Thanks for documenting the process!

**Comment by kgish** [comment]
:) Now you've opened up the contributors market to include all the ubuntu enthusiasts.

Will you include it in the documentation or am I allowed to do that directly?

**Comment by rambocoder** [comment]
@kgish check out kerl https://github.com/yrashk/kerl using it you can always use the latest and greates erlang if you decide to get the master or you can easily flip between different erlang releases. It's very handy.

**Comment by kgish** [comment]
Nice tool `kern` however it's just a wrapper around the builds, so if the build fails as in my case even the fanciest tool like `kern` will still not help.

Just curious, is there a nightly build for ubuntu which verifies that there are no errors?

This does not seem to be the case.

**Comment by mahalakshme** [comment]
On running test, I got the following error,
(UndefinedFunctionError) undefined function: :cover.is_compiled/1 (module :cover is not available)

Running the below command stated by kgish to install more erlang packages worked for me.
sudo apt-get install erlang-dev erlang-ssl erlang-inets erlang-dev \
    erlang-edoc erlang-eunit erlang-tools erlang-common-test

Thanks kgish!!!

**Comment by kgish** [comment]
You're welcome.
