### ISSUE TITLE
difficult to debug error on .beam being read only

### ISSUE THREAD

**Issue by Willyfrog** [elixir-lang/elixir#3164]
Compiling a module into a .beam where the file already exists but the user has no writing access results in a difficult to debug error:

```
iex(7)> c "asciionly.exs"
asciionly.exs:1: warning: redefining module AsciiOnly

== Compilation error on file asciionly.exs ==
** (MatchError) no match of right hand side value: {:error, :eacces}
    (elixir) lib/kernel/parallel_compiler.ex:95: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

** (exit) shutdown: 1
    (elixir) lib/kernel/parallel_compiler.ex:199: Kernel.ParallelCompiler.handle_failure/5
    (elixir) lib/kernel/parallel_compiler.ex:182: Kernel.ParallelCompiler.wait_for_messages/8
    (elixir) lib/kernel/parallel_compiler.ex:55: Kernel.ParallelCompiler.spawn_compilers/3
       (iex) lib/iex/helpers.ex:94: IEx.Helpers.c/2
iex(7)> c "asciionly.exs"
asciionly.exs:1: warning: redefining module AsciiOnly
[AsciiOnly]
iex(8)> 
```

To give some context: I share my elixir excercises codebase between my work and home user and forgot to give write permissions to the .beam file.

**Comment by Willyfrog** [comment]
thank you!
