### ISSUE TITLE
Task.await timeouts when a receive block that consumes all messages in the mailbox is in between Task.async and Task.await

### ISSUE THREAD

**Issue by bjhaid** [elixir-lang/elixir#3234]
Example:

```elixir
task = Task.async(fn -> 2 end)

fn ->
  a = fn(f) -> receive do
      message -> IO.inspect(message); f.(f)
    after
      500 -> :ok
    end
  end
  a.(a)
end.()

IO.inspect(Task.await(task) + 1)
```

output:

```elixir
{:EXIT, #PID<0.48.0>, :normal}                                                            
{#Reference<0.0.0.73>, 2}                                                                 
{:EXIT, #PID<0.51.0>, :normal}                                                            
{:DOWN, #Reference<0.0.0.73>, :process, #PID<0.51.0>, :normal}                            
** (exit) exited in: Task.await(%Task{pid: #PID<0.51.0>, ref: #Reference<0.0.0.73>}, 5000)
    ** (EXIT) time out                                                                    
    (elixir) lib/task.ex:207: Task.await/2                                                
    task_example.exs:15: (file)                                                           
    (elixir) lib/code.ex:316: Code.require_file/2                                         
```

If the calling process also traps exit it would receive messages it did not subscribe to in its mailbox, e.g:

```elixir
Process.flag(:trap_exit, true)
task = Task.async(fn -> 2 end)
Process.exit(self, :normal)

IO.inspect(Task.await(task) + 1)

fn ->
  a = fn(f) -> receive do
      message -> IO.inspect(message); f.(f)
    after
      500 -> :ok
    end
  end
  a.(a)
end.()
```

output:

```elixir
3                             
{:EXIT, #PID<0.48.0>, :normal}
{:EXIT, #PID<0.51.0>, :normal}
```

See: http://erlang.org/pipermail/erlang-questions/2015-April/084123.html

**Comment by bjhaid** [comment]
I would be willing to take this on, if it is a would fix

**Comment by josevalim** [comment]
There is no fix. It is documented that a Task sends a message back, if you
consume it, then it will timeout.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by bjhaid** [comment]
@josevalim how about the second case where you have messages left in the mailbox of the caller?

**Comment by josevalim** [comment]
I have replied there. Same issue happens in GenServer and elsewhere. The
answer is don't catch exits.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by bjhaid** [comment]
thanks!

**Comment by fishcakez** [comment]
I think almost a reverse bug exists. It should be explicit when `Task.await/2` and `Task.find/2` demonitor otherwise expected messages do not occur.
