### ISSUE TITLE
Compiling went fine but 7 tests failed.

### ISSUE THREAD

**Issue by laapsaap** [elixir-lang/elixir#3312]
Hi, I am having so much trouble compiling elixir. First 1.0.3 wasnt working with 17.5, so I got 1.0.4 and still errors. For me the test errors are just gibberish, no idea what it wants from me. Sorry for the long paste.

```
Randomized with seed 665241
==> mix (exunit)
................................................

  1) test updates the lock when the repo updates (Mix.Tasks.DepsGitTest)
     /home/admin/rpmbuild/BUILD/elixir-1.0.4/lib/mix/test/mix/tasks/deps.git_test.exs:181
     ** (ExUnit.TimeoutError) test timed out after 30000ms (you can change the test timeout by setting "@tag timeout: x" where x is an integer in miliseconds)
     stacktrace:
       (mix) lib/mix/shell.ex:76: Mix.Shell.do_cmd/2
       (mix) lib/mix/scm/git.ex:159: Mix.SCM.Git.run_cmd_or_raise/1
       (mix) lib/mix/scm/git.ex:110: Mix.SCM.Git.do_checkout/1
       (elixir) lib/file.ex:1061: File.cd!/2
       (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
       (mix) lib/mix/dep/converger.ex:154: Mix.Dep.Converger.all/8
       (mix) lib/mix/dep/converger.ex:62: Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4

mix.exs:2: warning: redefining module GitRepo.Mix
.mix.exs:2: warning: redefining module GitRepo.Mix
.

  2) test updates the repo when the lock updates (Mix.Tasks.DepsGitTest)
     /home/admin/rpmbuild/BUILD/elixir-1.0.4/lib/mix/test/mix/tasks/deps.git_test.exs:209
     ** (ExUnit.TimeoutError) test timed out after 30000ms (you can change the test timeout by setting "@tag timeout: x" where x is an integer in miliseconds)
     stacktrace:
       (mix) lib/mix/shell.ex:76: Mix.Shell.do_cmd/2
       (mix) lib/mix/scm/git.ex:159: Mix.SCM.Git.run_cmd_or_raise/1
       (mix) lib/mix/scm/git.ex:110: Mix.SCM.Git.do_checkout/1
       (elixir) lib/file.ex:1061: File.cd!/2
       (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
       (mix) lib/mix/dep/converger.ex:154: Mix.Dep.Converger.all/8
       (mix) lib/mix/dep/converger.ex:62: Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4



  3) test gets and updates many levels deep dependencies (Mix.Tasks.DepsGitTest)
     /home/admin/rpmbuild/BUILD/elixir-1.0.4/lib/mix/test/mix/tasks/deps.git_test.exs:86
     ** (ExUnit.TimeoutError) test timed out after 30000ms (you can change the test timeout by setting "@tag timeout: x" where x is an integer in miliseconds)
     stacktrace:
       (mix) lib/mix/shell.ex:76: Mix.Shell.do_cmd/2
       (mix) lib/mix/scm/git.ex:159: Mix.SCM.Git.run_cmd_or_raise/1
       (mix) lib/mix/scm/git.ex:79: Mix.SCM.Git.checkout/1
       (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
       (mix) lib/mix/dep/converger.ex:154: Mix.Dep.Converger.all/8
       (mix) lib/mix/dep/converger.ex:62: Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4
       (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3

mix.exs:2: warning: redefining module GitRepo.Mix


  4) test updates the repo and the lock when the mixfile updates (Mix.Tasks.DepsGitTest)
     /home/admin/rpmbuild/BUILD/elixir-1.0.4/lib/mix/test/mix/tasks/deps.git_test.exs:245
     ** (ExUnit.TimeoutError) test timed out after 30000ms (you can change the test timeout by setting "@tag timeout: x" where x is an integer in miliseconds)
     stacktrace:
       (mix) lib/mix/shell.ex:76: Mix.Shell.do_cmd/2
       (mix) lib/mix/scm/git.ex:159: Mix.SCM.Git.run_cmd_or_raise/1
       (mix) lib/mix/scm/git.ex:110: Mix.SCM.Git.do_checkout/1
       (elixir) lib/file.ex:1061: File.cd!/2
       (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
       (mix) lib/mix/dep/converger.ex:154: Mix.Dep.Converger.all/8
       (mix) lib/mix/dep/converger.ex:62: Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4

.mix.exs:2: warning: redefining module GitRepo.Mix
.

  5) test does not load bad mixfiles on get (Mix.Tasks.DepsGitTest)
     /home/admin/rpmbuild/BUILD/elixir-1.0.4/lib/mix/test/mix/tasks/deps.git_test.exs:288
     ** (ExUnit.TimeoutError) test timed out after 30000ms (you can change the test timeout by setting "@tag timeout: x" where x is an integer in miliseconds)
     stacktrace:
       (mix) lib/mix/shell.ex:76: Mix.Shell.do_cmd/2
       (mix) lib/mix/scm/git.ex:159: Mix.SCM.Git.run_cmd_or_raise/1
       (mix) lib/mix/scm/git.ex:110: Mix.SCM.Git.do_checkout/1
       (elixir) lib/file.ex:1061: File.cd!/2
       (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
       (mix) lib/mix/dep/converger.ex:154: Mix.Dep.Converger.all/8
       (mix) lib/mix/dep/converger.ex:62: Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4



  6) test does not load bad mixfiles on update (Mix.Tasks.DepsGitTest)
     /home/admin/rpmbuild/BUILD/elixir-1.0.4/lib/mix/test/mix/tasks/deps.git_test.exs:304
     ** (ExUnit.TimeoutError) test timed out after 30000ms (you can change the test timeout by setting "@tag timeout: x" where x is an integer in miliseconds)
     stacktrace:
       (mix) lib/mix/shell.ex:76: Mix.Shell.do_cmd/2
       (mix) lib/mix/scm/git.ex:159: Mix.SCM.Git.run_cmd_or_raise/1
       (mix) lib/mix/scm/git.ex:110: Mix.SCM.Git.do_checkout/1
       (elixir) lib/file.ex:1061: File.cd!/2
       (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
       (mix) lib/mix/dep/converger.ex:154: Mix.Dep.Converger.all/8
       (mix) lib/mix/dep/converger.ex:62: Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4

.......................................................mix.exs:2: warning: redefining module GitRepo.Mix
..mix.exs:2: warning: redefining module GitRepo.Mix
...........................................................................

  7) test get and compile dependencies for rebar (Mix.RebarTest)
     /home/admin/rpmbuild/BUILD/elixir-1.0.4/lib/mix/test/mix/rebar_test.exs:101
     ** (ExUnit.TimeoutError) test timed out after 30000ms (you can change the test timeout by setting "@tag timeout: x" where x is an integer in miliseconds)
     stacktrace:
       (mix) lib/mix/shell.ex:76: Mix.Shell.do_cmd/2
       (mix) lib/mix/tasks/deps.compile.ex:161: anonymous fn/5 in Mix.Tasks.Deps.Compile.do_command/4
       (mix) lib/mix/project.ex:196: Mix.Project.in_project/4
       (elixir) lib/file.ex:1061: File.cd!/2
       (mix) lib/mix/dep.ex:137: Mix.Dep.in_dependency/3
       (mix) lib/mix/tasks/deps.compile.ex:160: Mix.Tasks.Deps.Compile.do_command/4
       (mix) lib/mix/tasks/deps.compile.ex:59: anonymous fn/3 in Mix.Tasks.Deps.Compile.compile/1
       (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2

.................................................

Finished in 559.7 seconds (3.7s on load, 556.0s on tests)
240 tests, 7 failures
```

**Comment by ericmj** [comment]
Seems to fail when shelling out to call git and rebar. What OS are you using?

**Comment by laapsaap** [comment]
CentOS 7 and erlang 17.5 from official repo

**Comment by josevalim** [comment]
I think they are just timeouts due to the machine being slow. 7 tests failed with 30 seconds each, which is about 210 seconds, the whole suite still took 550 seconds. @laapsaap, if you change this line:

https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/test_helper.exs#L4

to:

    ExUnit.start [trace: "--trace" in System.argv, timeout: 60_000]

Does everything pass? If so, I will push a bigger timeout to the repo. Maybe 60_000 should be our defaults. Thoughts?

**Comment by laapsaap** [comment]
hmm I changed the line you mentioned, but somehow I still see 30 seconds.

```
  7) test updates the repo when the lock updates (Mix.Tasks.DepsGitTest)                                                                                      
     /home/admin/rpmbuild/BUILD/elixir-1.0.4/lib/mix/test/mix/tasks/deps.git_test.exs:209                                                                     
     ** (ExUnit.TimeoutError) test timed out after 30000ms (you can change the test timeout by setting "@tag timeout: x" where x is an integer in miliseconds)
     stacktrace:                                                                                                                                              
       (mix) lib/mix/shell.ex:76: Mix.Shell.do_cmd/2                                                                                                          
       (mix) lib/mix/scm/git.ex:159: Mix.SCM.Git.run_cmd_or_raise/1                                                                                           
       (mix) lib/mix/scm/git.ex:110: Mix.SCM.Git.do_checkout/1                                                                                                
       (elixir) lib/file.ex:1061: File.cd!/2                                                                                                                  
       (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3                                                                                            
       (mix) lib/mix/dep/converger.ex:154: Mix.Dep.Converger.all/8                                                                                            
       (mix) lib/mix/dep/converger.ex:62: Mix.Dep.Converger.all/4                                                                                             
       (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4                                                                                        
                                                                                                                                                              
.................................................                                                                                                             
                                                                                                                                                              
Finished in 558.5 seconds (3.3s on load, 555.1s on tests)                                                                                                     
240 tests, 7 failures                                                                                                                                         
```

The CPU is not the quickest but definately nothing slow. 5th generation Intel® Core™ i3-5010U processor (2.1GHz Dual Core, 3MB Cache) 4GB mem / SSD disk. With nothing much running, minimal installation.

**Comment by ericmj** [comment]
I think there is something else going wrong causing the shell commands to be slow.

@laapsaap Can you start `iex`, run the following command: `:timer.tc fn -> Mix.Shell.cmd("echo 123", &IO.write/1) end` and paste the output here.

**Comment by laapsaap** [comment]
$ ./iex 
Erlang/OTP 17 [erts-6.4] [source-2e19e2f] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :timer.tc fn -> Mix.Shell.cmd("echo 123", &IO.write/1) end
123
{3825, 0}
iex(2)>

**Comment by laapsaap** [comment]
Hmm I tried it today on a server also CentOS7/official erlang 17.5/Elixir1.0.4 and it successfully went through all the tests. Although now I have a successful built rpm, its quite confusing why it didnt on the pc and laptop. :(

**Comment by josevalim** [comment]
Would that affect communication in the same machine? Elixir nodes do connect with something called epmd running locally and if that is affecting all communications maybe that was the issue? Anyway, I am glad you figured it out.

**Comment by laapsaap** [comment]
No, the pc and laptop are both in two different environments (home/work) where hundred of users are working with the same config. And even if `search` is wrongly configured, it shouldnt have an impact like this.  But I dont think its an Elixir problem, erlang compile tests fails because of this too ;)  So I will be closing this issue, but definitely interesting why tests fails due config in the dns.  Thank you for your help.
