### ISSUE TITLE
Unclear Error Message on missing curly brackets

### ISSUE THREAD

**Issue by mitchellhenke** [elixir-lang/elixir#3319]
```bash
$ mix compile                                                                                                                    [14:18:46]

== Compilation error on file web/models/item.ex ==
** (SyntaxError) web/models/item.ex:54: syntax error before: eol
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```
For context, the first line is line 51, and the last is 55
```elixir
def changeset(:create, params) do
  %Item
  |> cast(params, [:title], ~w(type)
  |> validate_unique(:title, on: Repo)
end
```

The fix was the missing curly brackets on `Item{}` were missing, but the error was pointing to the last line of the function.

**Comment by josevalim** [comment]
Unfortunately there isn't much we can do here. The error is coming from deep within the parser. :(
