### ISSUE TITLE
Range parsing

### ISSUE THREAD

**Issue by arpunk** [elixir-lang/elixir#3461]
Hello,

Today while working with ranges I found the following parsing error:

```
Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1): 1..10..30
1..10..30
iex(2): Range.range? 1..10..30
true
iex(3): 1..10..30 |> Stream.map(fn item -> IO.inspect item end)
#Stream<[enum: 1..10..30, funs: [#Function<41.120947663/1 in Stream.map/2>]]>
iex(4): 1..10..30 |> Stream.map(fn item -> IO.inspect item end) |> Enum.to_list
** (FunctionClauseError) no function clause matching in Range.Iterator.Integer.next/2
    (elixir) lib/range.ex:102: Range.Iterator.Integer.next(1, 1..10..30)
    (elixir) lib/range.ex:65: Enumerable.Range.reduce/3
    (elixir) lib/stream.ex:1177: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:1265: Enum.reduce/3
    (elixir) lib/enum.ex:1807: Enum.to_list/1
iex(4):                                                                  
```
My guess is that we should raise in case the range is composed by 3 or more parts, but I just found this and I'm not totally sure if this is the correct approach.

**Comment by josevalim** [comment]
@arpunk we already have open issues to make ranges valid only for integers, so this will automatically be fixed once we tackled those. Thanks!

**Comment by arpunk** [comment]
Oh shoot, sorry, my fault for not checking if already reported. Cheers.
