### ISSUE TITLE
:backtrace_depth system flag should be bigger for tests

### ISSUE THREAD

**Issue by flupke** [elixir-lang/elixir#3705]
I had this strange stacktrace in my tests after upgrading HTTPoison:
```elixir
  1) test simple download then open (StashexDownloadTest)
     test/stashex/download_test.exs:18
     ** (Poison.EncodeError) unable to encode value: {"content-type", "application/json"}
     stacktrace:
       (poison) lib/poison/encoder.ex:339: Poison.Encoder.Any.encode/2
       (poison) lib/poison/encoder.ex:232: anonymous fn/3 in Poison.Encoder.List.encode/3
       (poison) lib/poison/encoder.ex:233: Poison.Encoder.List."-encode/3-lists^foldr/2-1-"/3
       (poison) lib/poison/encoder.ex:233: Poison.Encoder.List.encode/3
       (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
       (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
       (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
       (poison) lib/poison.ex:41: Poison.encode!/2
```
Where does this error come from? why isn't there any reference to my code?

Then someone on IRC suggested to add `:erlang.system_flag(:backtrace_depth, 50)` in my test, which gave me a complete stacktrace:
```elixir
  1) test simple download then open (StashexDownloadTest)
     test/stashex/download_test.exs:18
     ** (Poison.EncodeError) unable to encode value: {"content-type", "application/json"}
     stacktrace:
       (poison) lib/poison/encoder.ex:339: Poison.Encoder.Any.encode/2
       (poison) lib/poison/encoder.ex:232: anonymous fn/3 in Poison.Encoder.List.encode/3
       (poison) lib/poison/encoder.ex:233: Poison.Encoder.List."-encode/3-lists^foldr/2-1-"/3
       (poison) lib/poison/encoder.ex:233: Poison.Encoder.List.encode/3
       (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
       (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
       (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
       (poison) lib/poison.ex:41: Poison.encode!/2
       (stashex) lib/stashex/download.ex:188: anonymous fn/4 in Stashex.Download.download/4
       (elixir) lib/file.ex:950: File.open/3
       (elixir) lib/file.ex:981: File.open!/3
       (stashex) lib/stashex/download.ex:138: Stashex.Download.try_download/7
       test/stashex/download_test.exs:24
```
That someone said `:backtrace_depth` had performance implications (I couldn't find anything about it though), but, at least for tests, I think it should be set to something higher than the default to avoid confusing stacks like this.

**Comment by josevalim** [comment]
We should probably add configuration for ExUnit.configure and default it to 20 once ExUnit.configure is called. @fishcakez are you ok with this?

**Comment by fishcakez** [comment]
We already discussed this here: https://github.com/phoenixframework/phoenix/issues/1111 and it was added in https://github.com/phoenixframework/phoenix/commit/7692aef141f6eab5ad9a0e88875f42c8b02b117d. If this has been good in phoenix lets do it.
