### ISSUE TITLE
Invalid conversions String.to_atom(<atom>) in Mix

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#3734]
One error is [here](https://github.com/elixir-lang/elixir/blob/62baed24a87938087352804dea51ef7de5fb7b1f/lib/mix/lib/mix/tasks/deps.compile.ex#L161):

```
==> edown (compile)
Compiled src/edown_lib.erl
Compiled src/edown_make.erl
Compiled src/edown_xmerl.erl
Compiling src/edown_doclet.erl failed:
src/edown_doclet.erl:116: field packages undefined in record doclet_gen
src/edown_doclet.erl:118: field filemap undefined in record doclet_gen
ERROR: compile failed while processing [...]/deps/edown: rebar_abort
** (ArgumentError) argument error
    :erlang.binary_to_atom(:edown, :utf8)
    (mix) lib/mix/tasks/deps.compile.ex:161: anonymous fn/6 in Mix.Tasks.Deps.Compile.do_command/5
    (mix) lib/mix/project.ex:196: Mix.Project.in_project/4
    (elixir) lib/file.ex:1137: File.cd!/2
    (mix) lib/mix/dep.ex:140: Mix.Dep.in_dependency/3
    (mix) lib/mix/tasks/deps.compile.ex:158: Mix.Tasks.Deps.Compile.do_command/5
    (mix) lib/mix/tasks/deps.compile.ex:62: anonymous fn/3 in Mix.Tasks.Deps.Compile.compile/1
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
```

Another error is [here](https://github.com/elixir-lang/elixir/blob/62baed24a87938087352804dea51ef7de5fb7b1f/lib/mix/lib/mix/tasks/deps.compile.ex#L128):

```
$ mix compile
** (ArgumentError) argument error
    :erlang.binary_to_atom(:neotoma, :utf8)
    (mix) lib/mix/tasks/deps.compile.ex:128: Mix.Tasks.Deps.Compile.handle_rebar_not_found/1
    (mix) lib/mix/tasks/deps.compile.ex:118: Mix.Tasks.Deps.Compile.do_rebar/2
    (mix) lib/mix/tasks/deps.compile.ex:62: anonymous fn/3 in Mix.Tasks.Deps.Compile.compile/1
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    (mix) lib/mix/tasks/deps.compile.ex:53: Mix.Tasks.Deps.Compile.compile/1
```

The last one was fixed by installing rebar with `mix local.rebar`.

**Comment by josevalim** [comment]
Which Elixir version? Have you tried -beta and 1.0.5?

**Comment by alco** [comment]
It is master, the links to source above have commit SHA in them. Tried removing `rebar` and compiling with Elixir v1.0.5 – it prints the error correctly.

**Comment by ericmj** [comment]
Fixed in master.
