### ISSUE TITLE
mix run fails with upgrade to elixir 1.1

### ISSUE THREAD

**Issue by erlanger** [elixir-lang/elixir#3799]
`mix run` now fails because of the changes to Access. It works ok with 1.0
```
$ mix run
** (UndefinedFunctionError) undefined function: Access.List.get/2 (module Access.List is not available)
    Access.List.get([app: :bitbox, version: "0.0.1", elixir: "~> 1.1", deps: [], escript: [main_module: BitboxCli, emu_args: "+t 3048576"], aliases: [c: "compile", es: "escript.build"], build_per_environment: true, build_embedded: false, default_task: "run", deps_path: "deps", elixirc_paths: ["lib"], erlc_paths: ["src"], erlc_include_path: "include", erlc_options: [:debug_info], lockfile: "mix.lock", preferred_cli_env: [], start_permanent: false], :apps_path)
    (mix) lib/mix/project.ex:171: Mix.Project.umbrella?/1
    (mix) lib/mix/tasks/app.start.ex:78: Mix.Tasks.App.Start.start/2
    (mix) lib/mix/tasks/app.start.ex:68: Mix.Tasks.App.Start.run/1
    (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
```

**Comment by erlanger** [comment]
hmm.....just needed a *`mix clean`*

everything works fine now.
