### ISSUE TITLE
doctest is not printing the line causing the error in stacktrace

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3917]
lib/doctest_line_no_missing.ex
```elixir
defmodule DocTestLineNumberMissing do
  @doc """
      iex> :this_should_fail
    :this_should_fail
  """
  def this_should_fail, do: :this_should_fail
end
```

test/doc_test_line_no_missing_test.exs
```elixir
Code.require_file "test_helper.exs", __DIR__

defmodule DocTestLineNumberMissingTest do
  use ExUnit.Case, async: true
  doctest DocTestLineNumberMissing, import: true
end
```

```sh
$ mix test test/doc_test_line_no_missing_test.exs 
** (ExUnit.DocTest.Error) indentation level mismatch: "  :this_should_fail", should have been 4 spaces
    (ex_unit) lib/ex_unit/doc_test.ex:441: ExUnit.DocTest.adjust_indent/5
    (ex_unit) lib/ex_unit/doc_test.ex:410: ExUnit.DocTest.extract_tests/2
    (ex_unit) lib/ex_unit/doc_test.ex:403: ExUnit.DocTest.extract_from_doc/1
    (ex_unit) lib/ex_unit/doc_test.ex:386: anonymous fn/2 in ExUnit.DocTest.extract/1
    (elixir) lib/enum.ex:1470: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_unit) lib/ex_unit/doc_test.ex:385: ExUnit.DocTest.extract/1
    (ex_unit) lib/ex_unit/doc_test.ex:202: ExUnit.DocTest.__doctests__/2
    test/doc_test_line_no_missing_test.exs:5: (module)
```

`lib/doctest_line_no_missing.ex:4` is the line causing trouble but it doesn't show up anywhere.

You can download the coder here: https://github.com/eksperimental/elixir_bugs/tree/doctest_line_number_missing

**Comment by josevalim** [comment]
Which Elixir version?

**Comment by eksperimental** [comment]
master

**Comment by milmazz** [comment]
@eksperimental So, you just want to see the line in the stacktrace?, Something like this:

```
(ExUnit.DocTest.Error) indentation level mismatch: "  :this_should_fail" at line 4, should have been 4 spaces
    (ex_unit) lib/ex_unit/doc_test.ex:441: ExUnit.DocTest.adjust_indent/5
```

Working on this.
