### ISSUE TITLE
Cryptic error for an invalid map key type definition

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#4068]
Trying to compile this code

```elixir
@type content :: {atom | String.t => term}
```

results in the following error

```
== Compilation error on file lib/typ.ex ==
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Kernel.Typespec.typespec/3
    (elixir) lib/kernel/typespec.ex:896: anonymous fn({:|, [line: 2], [{:atom, [line: 2], nil}, [{{{:., [line: 2], [{:__aliases__, [counter: 0, line: 2], [:String]}, :t]}, [line: 2], []}, {:term, [line: 2], nil}}]]}) in Kernel.Typespec.typespec/3
    (stdlib) lists.erl:1238: :lists.map/2
    (elixir) lib/kernel/typespec.ex:896: Kernel.Typespec.typespec/3
    (elixir) lib/kernel/typespec.ex:552: Kernel.Typespec.translate_type/3
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

**Comment by josevalim** [comment]
Yeah, the precedence is biting you here.

**Comment by danielberkompas** [comment]
@josevalim The error message just needs to be made more clear here, right?

**Comment by josevalim** [comment]
Yes. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
I am tackling this so we can ship a new RC today. :)
