### ISSUE TITLE
Code.eval_string fails on strings with escaped quote mark

### ISSUE THREAD

**Issue by Mugimaru** [elixir-lang/elixir#4080]
Trying to run in iex

```
iex(1)> ~s/"a\""/
"\"a\"\""
iex(2)> Code.eval_string ~s/"a\""/
```
and expecting to see
```
{"a\"", []}
```

but it fails with 

```
** (TokenMissingError) nofile:1: missing terminator: " (for string starting at line 1)
    (elixir) lib/code.ex:168: Code.eval_string/3
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
       (iex) lib/iex/evaluator.ex:135: IEx.Evaluator.handle_eval/6
       (iex) lib/iex/evaluator.ex:128: IEx.Evaluator.do_eval/4
```

Couple of code samples that might be helpful:

```
iex(2)> to_char_list ~s/"a\""/    
'"a""'
iex(3)> '\'a\'\''
'\'a\'\''
iex(4)> :elixir.eval '\'a\'\'', [], []
** (TokenMissingError) nofile:1: missing terminator: ' (for string starting at line 1)
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
       (iex) lib/iex/evaluator.ex:135: IEx.Evaluator.handle_eval/6
       (iex) lib/iex/evaluator.ex:128: IEx.Evaluator.do_eval/4
       (iex) lib/iex/evaluator.ex:108: IEx.Evaluator.eval/4
iex(4)> Code.eval_string ~s/"\""/     
** (SyntaxError) nofile:1: heredoc start must be followed by a new line after """
    (elixir) lib/code.ex:168: Code.eval_string/3
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
       (iex) lib/iex/evaluator.ex:135: IEx.Evaluator.handle_eval/6
       (iex) lib/iex/evaluator.ex:128: IEx.Evaluator.do_eval/4
```

Tested with 1.1 and 1.2rc0

**Comment by lexmag** [comment]
`"\"a\"\""` is evaluating as `"a""` what is actually a broken code and rightfully raises `TokenMissingError`.
To get `"a\""` output you need to escape `\`, for example:
```elixir
iex> Code.eval_string "\"a\\\"\"" 
{"a\"", []}
```

**Comment by Mugimaru** [comment]
My mistake, thank you for the clarification, @lexmag.
