### ISSUE TITLE
UnicodeConversionError should not return invalid codepoints

### ISSUE THREAD

**Issue by dabaer** [elixir-lang/elixir#4081]
When a UnicodeConversionError is caused, the message contains invalid codepoints:

```
[error] GenServer #PID<0.331.0> terminating
** (ArgumentError) argument error
    (stdlib) :io.put_chars(:user, :unicode, [[[] | "\e[31m"], ["[", "error", "] ", ["#PID<0.473.0>", " running ", "Class.Endpoint", " terminated\n", [["Server: ", "0.0.0.0", ":", "4000", 32, 40, "http", 41, 10], ["Request: ", "GET", 32, "/", 10]] | <<42, 42, 32, 40, 101, 120, 105, 116, 41, 32, 97, 110, 32, 101, 120, 99, 101, 112, 116, 105, 111, 110, 32, 119, 97, 115, 32, 114, 97, 105, 115, 101, 100, 58, 10, 32, 32, 32, 32, ...>>], "\n"] | "\e[0m"])
    (logger) lib/logger/backends/console.ex:29: Logger.Backends.Console.handle_event/2
    (elixir) lib/gen_event.ex:1101: GenEvent.do_handler/3
    (elixir) lib/gen_event.ex:942: GenEvent.server_update/5
    (elixir) lib/gen_event.ex:927: GenEvent.server_notify/7
    (elixir) lib/gen_event.ex:900: GenEvent.server_event/4
    (elixir) lib/gen_event.ex:696: GenEvent.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:gen_event_EXIT, Logger.Backends.Console, {:badarg, [{:io, :put_chars, [:user, :unicode, [[[] | "\e[31m"], ["[", "error", "] ", ["#PID<0.473.0>", " running ", "Class.Endpoint", " terminated\n", [["Server: ", "0.0.0.0", ":", "4000", 32, 40, "http", 41, 10], ["Request: ", "GET", 32, "/", 10]] | <<42, 42, 32, 40, 101, 120, 105, 116, 41, 32, 97, 110, 32, 101, 120, 99, 101, 112, 116, 105, 111, 110, 32, 119, 97, 115, 32, 114, 97, 105, ...>>], "\n"] | "\e[0m"]], []}, {Logger.Backends.Console, :handle_event, 2, [file: 'lib/logger/backends/console.ex', line: 29]}, {GenEvent, :do_handler, 3, [file: 'lib/gen_event.ex', line: 1101]}, {GenEvent, :server_update, 5, [file: 'lib/gen_event.ex', line: 942]}, {GenEvent, :server_notify, 7, [file: 'lib/gen_event.ex', line: 927]}, {GenEvent, :server_event, 4, [file: 'lib/gen_event.ex', line: 900]}, {GenEvent, :handle_msg, 5, [file: 'lib/gen_event.ex', line: 696]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
State: {Logger, Logger.Backends.Console, #Reference<0.0.2.1940>}
```

```
** gen_event handler 'Elixir.Logger.Backends.Console' crashed.
** Was installed in 'Elixir.Logger'
** Last event was: {error,<0.25.0>,
                       {'Elixir.Logger',
                           [<<"#PID<0.940.0>">>,<<" running ">>,
                            <<"Class.Endpoint">>,<<" terminated\n">>,
                            [[<<"Server: ">>,<<"0.0.0.0">>,<<":">>,
                              <<"4000">>,32,40,<<"http">>,41,10],
                             [<<"Request: ">>,<<"GET">>,32,<<"/">>,10]]|
                            <<"** (exit) an exception was raised:\n    ** (UnicodeConversionError) invalid code point þ\n        (elixir) lib/list.ex:630: List.to_string/1\n        (plug) lib/plug/templates/debugger.eex:126: Plug.Debugger.template/1\n        (plug) lib/plug/debugger.ex:138: Plug.Debugger.render/5\n        (plug) lib/plug/debugger.ex:118: Plug.Debugger.__catch__/5\n        (class) lib/phoenix/endpoint/render_errors.ex:34: Class.Endpoint.call/2\n        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4\n        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4">>],
                           {{2015,12,15},{15,36,35,210}},
                           [{pid,<0.206.0>},{error_logger,format}]}}
** When handler state == #{colors => #{debug => cyan,
                             enabled => true,
                             error => red,
                             info => normal,
                             warn => yellow},
                           device => user,
                           format => [<<"[">>,level,<<"] ">>,message,<<"\n">>],
                           level => nil,
                           metadata => [request_id]}
** Reason == {badarg,
                 [{io,put_chars,
                      [user,unicode,
                       [[[]|<<"\e[31m">>],
                        [<<"[">>,<<"error">>,<<"] ">>,
                         [<<"#PID<0.940.0>">>,<<" running ">>,
                          <<"Class.Endpoint">>,<<" terminated\n">>,
                          [[<<"Server: ">>,<<"0.0.0.0">>,<<":">>,
                            <<"4000">>,32,40,<<"http">>,41,10],
                           [<<"Request: ">>,<<"GET">>,32,<<"/">>,10]]|
                          <<"** (exit) an exception was raised:\n    ** (UnicodeConversionError) invalid code point þ\n        (elixir) lib/list.ex:630: List.to_string/1\n        (plug) lib/plug/templates/debugger.eex:126: Plug.Debugger.template/1\n        (plug) lib/plug/debugger.ex:138: Plug.Debugger.render/5\n        (plug) lib/plug/debugger.ex:118: Plug.Debugger.__catch__/5\n        (class) lib/phoenix/endpoint/render_errors.ex:34: Class.Endpoint.call/2\n        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4\n        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4">>],
                         <<"\n">>]|
                        <<"\e[0m">>]],
                      []},
                  {'Elixir.Logger.Backends.Console',handle_event,2,
                      [{file,"lib/logger/backends/console.ex"},{line,29}]},
                  {'Elixir.GenEvent',do_handler,3,
                      [{file,"lib/gen_event.ex"},{line,1101}]},
                  {'Elixir.GenEvent',server_update,5,
                      [{file,"lib/gen_event.ex"},{line,942}]},
                  {'Elixir.GenEvent',server_notify,7,
                      [{file,"lib/gen_event.ex"},{line,927}]},
                  {'Elixir.GenEvent',server_event,4,
                      [{file,"lib/gen_event.ex"},{line,900}]},
                  {'Elixir.GenEvent',handle_msg,5,
                      [{file,"lib/gen_event.ex"},{line,696}]},
                  {proc_lib,init_p_do_apply,3,
                      [{file,"proc_lib.erl"},{line,240}]}]}
```

Where code point `þ` should be an integer.

Credit to @fishcakez  for understanding what exactly happened here.

**Comment by jisaacstone** [comment]
to clarify: the fix here is to change all instances of `þ` in the traceback to `254`? 

I think I could handle that ...

**Comment by josevalim** [comment]
The solution is to inspect the string we are going to show. Inspect takes care of showing only invalid bytes. Probably inspect it with `inspect(value, binaries: :as_strings)`

**Comment by fishcakez** [comment]
I thought the issue was we needed to unravel nested lists until we got a
binary or an integer at head?
