### ISSUE TITLE
Macro.to_string generates unparseable code for certain binary comprehensions

### ISSUE THREAD

**Issue by dazuma** [elixir-lang/elixir#4116]
```
iex(1)> ast = quote do: for <<a::4 <- <<1, 2>> >>, do: a
{:for, [],
 [{:<<>>, [],
   [{:<-, [], [{:::, [], [{:a, [], Elixir}, 4]}, {:<<>>, [], [1, 2]}]}]},
  [do: {:a, [], Elixir}]]}

iex(2)> Code.eval_quoted(ast)
{[0, 1, 0, 2], []}

iex(3)> source = Macro.to_string(ast)
"for(<<a :: 4 <- <<1, 2>>>>) do\n  a\nend"

iex(4)> Code.eval_string(source)
** (SyntaxError) nofile:1: unexpected token: ")". "<<" starting at line 1 is missing terminator ">>"
    (elixir) lib/code.ex:168: Code.eval_string/3
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
       (iex) lib/iex/evaluator.ex:117: IEx.Evaluator.handle_eval/5
       (iex) lib/iex/evaluator.ex:110: IEx.Evaluator.do_eval/3
```

Notice that the code generated by Macro.to_string has no space between the two ">>" delimiters. This seems to confuse the parser. See also related issue #2136.

**Comment by dazuma** [comment]
Forgot to mention, this is elixir 1.1.1, erlang 18.2, installed via homebrew on Mac OS 10.10.5

**Comment by josevalim** [comment]
Thank you! The bug still exists on master. :)
