### ISSUE TITLE
A random error in 'make test'

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#4130]
Happened to me out of the blue, doesn't reproduce. Could be a race condition? Putting it here just in case. [These](https://github.com/elixir-lang/elixir/pull/2974#issuecomment-168021428) might also warrant investigation.

https://github.com/alco/elixir/commit/16ca188894f14207e4bd8a075570ccadf129dd91

```
$ make test
==> elixir (compile)
==> elixir (eunit)
  All 196 tests passed.

==> elixir (exunit)
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

  1) test yield_many/2 returns results from multiple tasks (TaskTest)
     test/elixir/task_test.exs:276
     Assertion with == failed
     code: Task.yield_many([task1, task2, task3], 0) == [{task1, {:ok, :result}}, {task2, nil}, {task3, {:exit, :normal}}]
     lhs:  [{%Task{owner: #PID<0.7220.0>, pid: nil, ref: #Reference<0.0.3.17063>}, {:ok, :result}}, {%Task{owner: #PID<0.7220.0>, pid: nil, ref: #Reference<0.0.3.17064>}, nil},
            {%Task{owner: #PID<0.7220.0>, pid: #PID<0.7221.0>, ref: #Reference<0.0.3.17065>}, nil}]
     rhs:  [{%Task{owner: #PID<0.7220.0>, pid: nil, ref: #Reference<0.0.3.17063>}, {:ok, :result}}, {%Task{owner: #PID<0.7220.0>, pid: nil, ref: #Reference<0.0.3.17064>}, nil},
            {%Task{owner: #PID<0.7220.0>, pid: #PID<0.7221.0>, ref: #Reference<0.0.3.17065>}, {:exit, :normal}}]
     stacktrace:
       test/elixir/task_test.exs:283

..........................................................................

Finished in 17.5 seconds (8.7s on load, 8.8s on tests)
2752 tests, 1 failure
```

**Comment by alco** [comment]
And the one from the comment happened again [on Travis](https://travis-ci.org/elixir-lang/elixir/builds/99471785):

```
  1) test get and compile dependencies for rebar3 (Mix.RebarTest)
     /home/travis/build/elixir-lang/elixir/lib/mix/test/mix/rebar_test.exs:179
     ** (RuntimeError) no shell process input given for yes?/1
     stacktrace:
       (mix) lib/mix/shell/process.ex:155: Mix.Shell.Process.yes?/1
       (mix) lib/mix/tasks/deps.compile.ex:146: Mix.Tasks.Deps.Compile.handle_rebar_not_found/1
       (mix) lib/mix/tasks/deps.compile.ex:130: Mix.Tasks.Deps.Compile.do_rebar3/2
       (mix) lib/mix/tasks/deps.compile.ex:66: anonymous fn/3 in Mix.Tasks.Deps.Compile.compile/1
       (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
       (mix) lib/mix/tasks/deps.compile.ex:53: Mix.Tasks.Deps.Compile.compile/1
       test/mix/rebar_test.exs:186: anonymous fn/0 in Mix.RebarTest.test get and compile dependencies for rebar3/1
       (elixir) lib/file.ex:1138: File.cd!/2
       test/mix/rebar_test.exs:182
```
