### ISSUE TITLE
Race condition in gen_event_test.exs

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#4131]
I can reproduce it by running `bin/elixir lib/elixir/test/elixir/gen_event_test.exs` in a loop, it happens every 30-40 iterations.

4a7e5411300379e3347452e09fec8d7d8e890b0b

```
15:52:44.469 [error] GenEvent handler GenEventTest.ReplyHandler installed in #PID<0.123.0> terminating
** (RuntimeError) oops
    lib/elixir/test/elixir/gen_event_test.exs:44: GenEventTest.ReplyHandler.handle_event/2
    (elixir) lib/gen_event.ex:1101: GenEvent.do_handler/3
    (elixir) lib/gen_event.ex:942: GenEvent.server_update/5
    (elixir) lib/gen_event.ex:927: GenEvent.server_notify/7
    (elixir) lib/gen_event.ex:900: GenEvent.server_event/4
    (elixir) lib/gen_event.ex:703: GenEvent.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :raise
State: #PID<0.122.0>
```

**Comment by josevalim** [comment]
Is a testing failing? If so, which test? The error message above does not say the test. :)

**Comment by alco** [comment]
All tests succeed:

```
.....
15:55:48.991 [error] GenEvent handler GenEventTest.ReplyHandler installed in #PID<0.91.0> terminating
** (RuntimeError) oops
    lib/elixir/test/elixir/gen_event_test.exs:44: GenEventTest.ReplyHandler.handle_event/2
    (elixir) lib/gen_event.ex:1101: GenEvent.do_handler/3
    (elixir) lib/gen_event.ex:942: GenEvent.server_update/5
    (elixir) lib/gen_event.ex:927: GenEvent.server_notify/7
    (elixir) lib/gen_event.ex:900: GenEvent.server_event/4
    (elixir) lib/gen_event.ex:703: GenEvent.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :raise
State: #PID<0.90.0>
..............

Finished in 0.4 seconds (0.4s on load, 0.01s on tests)
19 tests, 0 failures

Randomized with seed 978866
```

**Comment by alco** [comment]
Rerunning it using the same seed every time doesn't increase the frequency at which it appears.

**Comment by fishcakez** [comment]
It looks like a logging race condition here: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/gen_event_test.exs#L331. There is no guarantee the error logger message has been sent before flushing/adding. We can make this guarantee by call `which_handlers` on the `GenEvent` process after receiving the `:terminate` tuple.

**Comment by fishcakez** [comment]
It looks like we may need that in a few other places too, at least ack/sync_notify.
