### ISSUE TITLE
quote/2 examples not compiling

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#4325]
The quote examples are not compiling.
https://github.com/elixir-lang/elixir/blob/187f4f800bc708ce272c70fd2de92deba5010272/lib/elixir/lib/kernel/special_forms.ex#L1131-L1137
```elixir
defmodule Quote do
  defmacro defkv(kv) do
    Enum.map kv, fn {k, v} ->
      quote do
        def unquote(k)(), do: unquote(v)
      end
    end
  end
end

IO.inspect Quote.defkv [foo: 1, bar: 2]
IO.inspect Quote.foo
```

```shell
 ** (UndefinedFunctionError) undefined function Quote.defkv/1
    Quote.defkv([foo: 1, bar: 2])
    lib/quote_error2.exs:11: (file)
    (elixir) lib/code.ex:363: Code.require_file/2
```

neither this one
https://github.com/elixir-lang/elixir/blob/187f4f800bc708ce272c70fd2de92deba5010272/lib/elixir/lib/kernel/special_forms.ex#L1178-L1184

```elixir
defmodule Quote do
  defmacro defkv(kv) do
    quote bind_quoted: [kv: kv] do
      Enum.each kv, fn {k, v} ->
        def unquote(k)(), do: unquote(v)
      end
    end
  end
end

IO.inspect Quote.defkv [foo: 1, bar: 2]
IO.inspect Quote.foo
```

```shell
** (UndefinedFunctionError) undefined function Quote.defkv/1
    Quote.defkv([foo: 1, bar: 2])
    lib/quote_error3.exs:11: (file)
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by ericmj** [comment]
You can't use macros in the same context they are defined. A fix would be to put the module and the invocation of the macros in separate files.

**Comment by eksperimental** [comment]
thanks @ericmj 
Would it help to make it more clear the example?

```elixir
defmodule Quote do
  defmacro defkv(kv) do
    Enum.map kv, fn {k, v} ->
      quote do
        def unquote(k)(), do: unquote(v)
      end
    end
  end
end

defmodule Foo do
  require Quote
  Quote.defkv [foo: 1, bar: 2]
end

Foo.foo
#=> 1
```

**Comment by ericmj** [comment]
That could also be more confusion. Would appreciate input from others /cc @elixir-lang/elixir.
