### ISSUE TITLE
Hex 0.11.2 makes `mix compile` have a hard dependency on the internet?

### ISSUE THREAD

**Issue by folz** [elixir-lang/elixir#4380]
### Issue

After upgrading hex from 0.10.0 to 0.11.2, `mix compile` seem to have a hard dependency on an available internet connection. This issue was not present when using hex 0.10.0. I couldn't find similar bugs via Github or Google search.

### Environment

```
➜ elixir -v
Erlang/OTP 18 [erts-7.2] [source-e6dd627] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.3
```

```
➜ lsb_release -a    
Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa
```

### Current behavior

Mix with unstable internet:

```
➜ mix compile
Erlang/OTP 18 [erts-7.2] [source-e6dd627] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

# (this hangs forever)
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C%            
```

Mix with no internet:

```
➜ mix compile    
** (CaseClauseError) no case clause matching: {:http_error, {:failed_connect, [{:to_address, {'s3.hex.pm.global.prod.fastly.net', 80}}, {:inet, [:inet], :nxdomain}]}}
    (hex) lib/hex/utils.ex:61: Hex.Utils.update_registry/1
    (hex) lib/hex/utils.ex:22: Hex.Utils.ensure_registry!/1
    (hex) lib/hex/remote_converger.ex:52: Hex.RemoteConverger.deps/2
    (mix) lib/mix/dep/converger.ex:100: anonymous fn/4 in Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:167: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:111: Mix.Dep.Converger.all/7
    (mix) lib/mix/dep/converger.ex:96: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4
```

Mix with good internet:

```
➜ mix compile
➜ 
```

### Expected behavior

Mix compiles my project.

**Comment by enilsen16** [comment]
I get the same thing with elixir 1.3.0 and hex 0.11.2. I didn't have this issue with hex 0.11.1

```
~/Projects/elixir/feed(master ✗) mc
** (CaseClauseError) no case clause matching: {:http_error, {:failed_connect, [{:to_address, {'s3.hex.pm.global.prod.fastly.net', 80}}, {:inet, [:inet], :nxdomain}]}}
    (hex) lib/hex/utils.ex:61: Hex.Utils.update_registry/1
    (hex) lib/hex/utils.ex:22: Hex.Utils.ensure_registry!/1
    (hex) lib/hex/remote_converger.ex:52: Hex.RemoteConverger.deps/2
    (mix) lib/mix/dep/converger.ex:100: anonymous fn/4 in Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:167: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:111: Mix.Dep.Converger.all/7
    (mix) lib/mix/dep/converger.ex:96: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4
```

**Comment by ericmj** [comment]
Please reopen this at https://github.com/hexpm/hex

**Comment by josevalim** [comment]
Done: https://github.com/hexpm/hex/issues/213 :)
