### ISSUE TITLE
Test translates :proc_lib crashes with neighbour with name (Logger.TranslatorTest)

### ISSUE THREAD

**Issue by peteygao** [elixir-lang/elixir#4467]
### Stack trace

```
Randomized with seed 88794
==> logger (exunit)
.............................................................................

  1) test translates :proc_lib crashes with neighbour with name (Logger.TranslatorTest)
     test/logger/translator_test.exs:320
     Assertion with =~ failed
     code: capture_log(:info, fn ->
             ref = Process.monitor(pid)
             send(pid, :message)
             send(pid, :go)
             receive() do
               {:DOWN, ^ref, _, _, _} ->
                 :ok
             end
           end) =~ ~r"Ancestors: \\[#PID<\\d+\\.\\d+\\.\\d+>\\]\nNeighbours:\n    Logger.TranslatorTest \\(#PID<\\d+\\.\\d+\\.\\d+>\\)\n        Initial Call: :timer.sleep
/1\n        Current Call: :timer.sleep/1\n        Ancestors: \\[#PID<\\d+\\.\\d+\\.\\d+>, #PID<\\d+\\.\\d+\\.\\d+>\\]\n"
     lhs:  "\n20:36:38.811 [error] Task #PID<0.387.0> started from #PID<0.386.0> terminating\n** (RuntimeError) oops\n    test/logger/translator_test.exs:324: anonymous f
n/1 in Logger.TranslatorTest.test translates :proc_lib crashes with neighbour with name/1\n    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2\n    (stdlib
) proc_lib.erl:240: :proc_lib.init_p_do_apply/3\nFunction: &Logger.TranslatorTest.sub_task/2\n    Args: [#PID<0.386.0>, #Function<26.21255176/1 in Logger.TranslatorTest.t
est translates :proc_lib crashes with neighbour with name/1>]\n\n20:36:38.814 [error] Process #PID<0.387.0> terminating\n** (exit) an exception was raised:\n    ** (Runti
meError) oops\n        test/logger/translator_test.exs:324: anonymous fn/1 in Logger.TranslatorTest.test translates :proc_lib crashes with neighbour with name/1\n
(elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2\n        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3\n    (elixir) lib/task/supervised.ex:120: T
ask.Supervised.exit/4\n    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3\nInitial Call: Logger.TranslatorTest.sub_task/2\nAncestors: [#PID<0.386.0>]\nNeighbours:
\n    Logger.TranslatorTest (#PID<0.389.0>)\n        Initial Call: :proc_lib.init_p/5\n        Current Call: :proc_lib.init_p/5\n        Ancestors: []\n"
     rhs:  ~r/Ancestors: \[#PID<\d+\.\d+\.\d+>\]\nNeighbours:\n    Logger.TranslatorTest \(#PID<\d+\.\d+\.\d+>\)\n        Initial Call: :timer.sleep\/1\n        Current C
all: :timer.sleep\/1\n        Ancestors: \[#PID<\d+\.\d+\.\d+>, #PID<\d+\.\d+\.\d+>\]\n/
     stacktrace:
       test/logger/translator_test.exs:327

..........

Finished in 7.4 seconds (5.7s on load, 1.6s on tests)
88 tests, 1 failure

Randomized with seed 289732
Makefile:95: recipe for target 'test_logger' failed
make: *** [test_logger] Error 1
```

### Environment

* Elixir version (elixir -v): `master` branch, commit `9cbbf8a5803210b4fd40a867c3e26b79b20da8e6`
* Operating system: `Linux 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux` This is a Raspberry Pi 2 system (CPU is an Armv7, I believe)

### Current behavior

Repro steps:
```
$ git clone https://github.com/elixir-lang/elixir.git
$ cd elixir
$ make clean test
# The above test fails.
```

### Expected behavior

Tests should pass and Elixir builds.

**Comment by fishcakez** [comment]
Thanks for the report, it looks like a race condition in the test.

**Comment by peteygao** [comment]
No problem, glad to help :smile:.

**Comment by eksperimental** [comment]
I came to report the same issue
but different seed
> Randomized with seed 388455
https://gist.github.com/eksperimental/afc0d7395deca0463270c5cb3bf3cbe3

**Comment by fishcakez** [comment]
Fixed in https://github.com/elixir-lang/elixir/commit/d917f7f411c239cb52c37348d0cd3baedf1e4620

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
