### ISSUE TITLE
ExUnit assertion differ crashes on improper lists

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#4548]
GenEvent crash:

```
2016-04-23 15:40:17.340 [error] GenEvent handler ExUnit.CLIFormatter installed in #PID<0.451.0> terminating
** (FunctionClauseError) no function clause matching in ExUnit.Diff.format_list/5
    (ex_unit) lib/ex_unit/diff.ex:74: ExUnit.Diff.format_list([" because"], "\e[4m", #Function<3.116801188/2 in ExUnit.CLIFormatter.handle_event/2>, false, ["[\e[31m[[[[[[[[[] | \"\\e[4m\"], \"Failed to use \\\"\"], \"foo\"], \"\\\"\"], \" (versions \"], \"0.0.1\"], \" to \"], \"0.2.0\"]\e[0m, \e[31m\")\"\e[0m]"])
    (ex_unit) lib/ex_unit/diff.ex:205: ExUnit.Diff.format_inner/3
    (ex_unit) lib/ex_unit/diff.ex:107: ExUnit.Diff.format_list/5
    (ex_unit) lib/ex_unit/diff.ex:205: ExUnit.Diff.format_inner/3
    (ex_unit) lib/ex_unit/diff.ex:107: ExUnit.Diff.format_list/5
    (ex_unit) lib/ex_unit/diff.ex:205: ExUnit.Diff.format_inner/3
    (ex_unit) lib/ex_unit/diff.ex:107: ExUnit.Diff.format_list/5
    (ex_unit) lib/ex_unit/formatter.ex:228: anonymous fn/3 in ExUnit.Formatter.format_diff/2
```

/cc @lexmag

**Comment by lexmag** [comment]
Oops, fix is coming.
