### ISSUE TITLE
Failing SystemTests under Windows

### ISSUE THREAD

**Issue by robi-wan** [elixir-lang/elixir#4753]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 18 [erts-7.3] [64-bit] [smp:8:8] [async-threads:10]
Elixir 1.3.0-rc.0

* Operating system: Windows 7 Professional 64bit

### Current behavior

Running the tests under windows gets me this output: 
```
  4) test cmd/2 with absolute and relative paths (SystemTest)
     d:/home/docs/dev/git_repos/elixir/lib/elixir/test/elixir/system_test.exs:90
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:

       1. per test by setting "@tag timeout: x"
       2. per case by setting "@moduletag timeout: x"
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. or set it to infinity per run by calling "mix test --trace"
          (useful when using IEx.pry)

     Timeouts are given as integers in milliseconds.

     stacktrace:
       (elixir) lib/system.ex:564: System.do_cmd/3
       (elixir) lib/system.ex:552: System.cmd/3
       test/elixir/system_test.exs:103: anonymous fn/0 in SystemTest.test cmd/2 with absolute and relative paths/1
       (elixir) lib/file.ex:1145: File.cd!/2
       test/elixir/system_test.exs:95: (test)
       (ex_unit) lib/ex_unit/runner.ex:296: ExUnit.Runner.exec_test/1
       (stdlib) timer.erl:166: :timer.tc/1
       (ex_unit) lib/ex_unit/runner.ex:246: anonymous fn/3 in ExUnit.Runner.spawn_test/3

..........

  5) test cmd/2 (SystemTest)
     d:/home/docs/dev/git_repos/elixir/lib/elixir/test/elixir/system_test.exs:78
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:

       1. per test by setting "@tag timeout: x"
       2. per case by setting "@moduletag timeout: x"
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. or set it to infinity per run by calling "mix test --trace"
          (useful when using IEx.pry)

     Timeouts are given as integers in milliseconds.

     stacktrace:
       (elixir) lib/system.ex:564: System.do_cmd/3
       (elixir) lib/system.ex:552: System.cmd/3
       test/elixir/system_test.exs:79: (test)
       (ex_unit) lib/ex_unit/runner.ex:296: ExUnit.Runner.exec_test/1
       (stdlib) timer.erl:166: :timer.tc/1
       (ex_unit) lib/ex_unit/runner.ex:246: anonymous fn/3 in ExUnit.Runner.spawn_test/3
```

System.cmd/3 is tested by using the echo executable.

But: there is no native echo `executable` under windows. There does exist an echo `command` but is a builtin part of Windows' cmd.exe.

Nevertheless the tests find an executable `echo.exe` - from the [msys installation](https://github.com/elixir-lang/elixir/wiki/Windows#installing-mingw) (which I added to PATH).
Interestingly the test  named "cmd/3 (with options)"  also uses the echo executable to test System.cmd/3 but it does not fail.
I played with the options to System.cmd/3 and it seems `stderr_to_stdout: true` does the trick.
When I add this option to the tests they are not failing anymore:

```
D:\home\docs\dev\git_repos\elixir>bin\elixir lib\elixir\test\elixir\system_test.exs
..............

  1) test cmd/2 with absolute and relative paths (SystemTest)
     lib/elixir/test/elixir/system_test.exs:90
     ** (File.Error) could not remove files and directories recursively from "d:/home/docs/dev/git_repos/elixir/lib/elixir/tmp/echo-elixir-test": permission denied
     stacktrace:
       (elixir) lib/file.ex:919: File.rm_rf!/1
       lib/elixir/test/elixir/system_test.exs:90: (test)

......

Finished in 5.7 seconds (0.2s on load, 5.4s on tests)
21 tests, 1 failure

Randomized with seed 57000
```
This looks a little better (no failing assertion) but the cleanup of test `cmd/2 with absolute and relative paths` fails.

A differentiation of the tests depending on the os type would work: 
Under Windows the System.cmd/3 tests would use the command `cmd.exe /c echo hello`
This command starts a new shell - the switch /c carries out the command `echo hello` and then stops. (https://technet.microsoft.com/en-us/library/bb490880.aspx)

Tests for unix are not touched.

```elixir
 lib/elixir/test/elixir/system_test.exs | 82 +++++++++++++++++++++++++---------
 1 file changed, 60 insertions(+), 22 deletions(-)

diff --git a/lib/elixir/test/elixir/system_test.exs b/lib/elixir/test/elixir/system_test.exs
index d500119..7947349 100644
--- a/lib/elixir/test/elixir/system_test.exs
+++ b/lib/elixir/test/elixir/system_test.exs
@@ -75,37 +75,75 @@ defmodule SystemTest do
     assert System.get_env(@test_var) == "OTHER_SAMPLE"
   end
 
-  test "cmd/2" do
-    assert {"hello\n", 0} = System.cmd "echo", ["hello"]
-  end
 
-  test "cmd/3 (with options)" do
-    assert {["hello\n"], 0} = System.cmd "echo", ["hello"],
-                                into: [], cd: System.cwd!, env: %{"foo" => "bar", "baz" => nil},
-                                arg0: "echo", stderr_to_stdout: true, parallelism: true
-  end
+  if windows? do
+
+    test "cmd/2 win" do
+      assert {"hello\r\n", 0} = System.cmd "cmd", ~w[/c echo hello]
+    end
+
+    test "cmd/3 (with options) win" do
+      assert {["hello\r\n"], 0} = System.cmd "cmd", ~w[/c echo hello],
+                                  into: [], cd: System.cwd!, env: %{"foo" => "bar", "baz" => nil},
+                                  arg0: "echo", stderr_to_stdout: true, parallelism: true
+    end
+
+    @echo "echo-elixir-test"
 
-  @echo "echo-elixir-test"
+    test "cmd/2 with absolute and relative paths win" do
+      echo = tmp_path(@echo)
+      File.mkdir_p! Path.dirname(echo)
+      File.cp! System.find_executable("cmd"), echo
 
-  test "cmd/2 with absolute and relative paths" do
-    echo = tmp_path(@echo)
-    File.mkdir_p! Path.dirname(echo)
-    File.cp! System.find_executable("echo"), echo
+      File.cd! Path.dirname(echo), fn ->
+        # There is a bug in OTP where find_executable is finding
+        # entries on the current directory. If this is the case,
+        # we should avoid the assertion below.
+        unless System.find_executable(@echo) do
+          assert :enoent = catch_error(System.cmd(@echo, ~w[/c echo hello]))
+        end
 
-    File.cd! Path.dirname(echo), fn ->
-      # There is a bug in OTP where find_executable is finding
-      # entries on the current directory. If this is the case,
-      # we should avoid the assertion below.
-      unless System.find_executable(@echo) do
-        assert :enoent = catch_error(System.cmd(@echo, ["hello"]))
+        assert {"hello\r\n", 0} = System.cmd(Path.join(System.cwd!, @echo), ~w[/c echo hello], [{:arg0, "echo"}])
       end
+    after
+      File.rm_rf! tmp_path(@echo)
+    end
+
+  else
+    test "cmd/2 unix" do
+      assert {"hello\n", 0} = System.cmd "echo", ["hello"]
+    end
+
+    test "cmd/3 (with options) unix" do
+      assert {["hello\n"], 0} = System.cmd "echo", ["hello"],
+                                  into: [], cd: System.cwd!, env: %{"foo" => "bar", "baz" => nil},
+                                  arg0: "echo", stderr_to_stdout: true, parallelism: true
+    end
+
+    @echo "echo-elixir-test"
+
+    test "cmd/2 with absolute and relative paths unix" do
+      echo = tmp_path(@echo)
+      File.mkdir_p! Path.dirname(echo)
+      File.cp! System.find_executable("echo"), echo
 
-      assert {"hello\n", 0} = System.cmd(Path.join(System.cwd!, @echo), ["hello"], [{:arg0, "echo"}])
+      File.cd! Path.dirname(echo), fn ->
+        # There is a bug in OTP where find_executable is finding
+        # entries on the current directory. If this is the case,
+        # we should avoid the assertion below.
+        unless System.find_executable(@echo) do
+          assert :enoent = catch_error(System.cmd(@echo, ["hello"]))
+        end
+
+        assert {"hello\n", 0} = System.cmd(Path.join(System.cwd!, @echo), ["hello"], [{:arg0, "echo"}])
+      end
+    after
+      File.rm_rf! tmp_path(@echo)
     end
-  after
-    File.rm_rf! tmp_path(@echo)
+
   end
 
+
   test "find_executable/1" do
     assert System.find_executable("erl")
     assert is_binary System.find_executable("erl")
```

**Comment by josevalim** [comment]
@robi-wan thank you! can you please send a PR so we can further investigate?

**Comment by robi-wan** [comment]
I will send a PR (with different tests depending on os type). Later today.

**Comment by robi-wan** [comment]
Resolved with https://github.com/elixir-lang/elixir/pull/4760
