### ISSUE TITLE
make clean test fails at  mix (exunit)

### ISSUE THREAD

**Issue by vaibhi9** [elixir-lang/elixir#5601]
```log
  1) test recompiles after path dependency changes (Mix.UmbrellaTest)
     test/mix/umbrella_test.exs:308
     Assertion with == failed
     code:  Mix.Tasks.Compile.Elixir.run(["--verbose"]) == :ok
     left:  :noop
     right: :ok
     stacktrace:
       test/mix/umbrella_test.exs:333: anonymous fn/1 in Mix.UmbrellaTest.test recompiles after path dependency changes/1
       (mix) lib/mix/project.ex:329: Mix.Project.in_project/4
       (elixir) lib/file.ex:1186: File.cd!/2
       test/test_helper.exs:108: MixTest.Case.in_fixture/3
       test/mix/umbrella_test.exs:309: (test)
```

**Comment by josevalim** [comment]
Can you please fill in the issues template? We need information such as which branch and the operating system. Thank you.

**Comment by leifg** [comment]
Was able to reproduce this in a docker build on alpine linux

### Environment

* Elixir & Erlang versions (elixir --version):
  - Elixir 1.4.4 (tag v1.4.4 in repository)
  - Erlang/OPT 19.3.6
* Operating system: Alpine Linux 3.5
