### ISSUE TITLE
IEx crashes when autocompleting non-existent module

### ISSUE THREAD

**Issue by elbow-jason** [elixir-lang/elixir#5721]
## Environment

Elixir version (elixir -v): Elixir 1.4.0

Erlang version: 19

Operating system: OSX Yosemite 10.10.5

## Current behavior

The crash occured when I pressed tab to autocomplete a non-existent module's function `w = db.Worker.get_by <tab press>`.

In my source there is no `db.Worker` module (notice the lowercase `db`). I meant to type `Db.Worker.get_by_ident` which is a module and function that exists.

```
  Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
  Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
  iex(1)>  w = db.Worker.get_by*** ERROR: Shell process terminated! (^G to start new job) ***
  [error] Process #PID<0.50.0> raised an exception
  ** (FunctionClauseError) no function clause matching in :elixir_aliases.do_concat/2
      (elixir) src/elixir_aliases.erl:119: :elixir_aliases.do_concat([{:db, [line: 1], nil}], "Elixir")
      (elixir) src/elixir_aliases.erl:107: :elixir_aliases.concat/1
      (iex) lib/iex/autocomplete.ex:187: IEx.Autocomplete.expand_alias/2
      (iex) lib/iex/autocomplete.ex:118: IEx.Autocomplete.expand_call/3
      (kernel) group.erl:568: :group.get_line1/4
      (kernel) group.erl:462: :group.get_chars_loop/8
      (kernel) group.erl:181: :group.io_request/5
      (kernel) group.erl:117: :group.server_loop/3
```

## Expected behavior

It should not autocomplete. It should not suggest matching functions. It should not crash.

## Notes

This issue is very similar to another issue: https://github.com/elixir-lang/elixir/issues/5577

**Comment by elbow-jason** [comment]
also of note. This just popped up.

```
Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> DB.[error] Loading of /Users/elbow-jason/Prospace/bellshaped/az_pipeline/_build/dev/lib/db/ebin/Elixir.DB.beam failed: :badfile

[error] beam/beam_load.c(1376): Error loading module 'Elixir.DB':
  module name in object code is Elixir.Db



nil
iex(2)>

```

**Comment by elbow-jason** [comment]
wrt my previous post. It did not crash. It simply logged an error.
