### ISSUE TITLE
Unable to compose Stream.flat_map, Stream.take and Task.async_stream

### ISSUE THREAD

**Issue by mbuhot** [elixir-lang/elixir#5772]
### Environment

```bash
elixir --version
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.1
```

OSX 10.11.6

### Current behavior

```elixir
(1 .. 3) 
|> Stream.flat_map(fn _ -> [1, 2, 3] |> Stream.take(1) end) 
|> Task.async_stream(&IO.inspect/1) 
|> Stream.run()

** (TryClauseError) no try clause matching: {:halted, [1, 1, 1]}
    (elixir) lib/task/supervised.ex:215: Task.Supervised.stream_reduce/10
    (elixir) lib/stream.ex:570: Stream.run/1
```

### Expected behavior

This code should behave the same as when replacing `Task.async_stream` with `Stream.map`:

```elixir
(1 .. 3) 
|> Stream.flat_map(fn _ -> [1, 2, 3] |> Stream.take(1) end) 
|> Stream.map(&IO.inspect/1) 
|> Stream.run()

1
1
1
:ok
```

Using `Enum.take` inside the `Stream.flat_map` also works around the problem:

```elixir
(1 .. 3) 
|> Stream.flat_map(fn _ -> [1, 2, 3] |> Enum.take(1) end) 
|> Task.async_stream(&IO.inspect/1) 
|> Stream.run()

1
1
1
:ok
```

**Comment by mbuhot** [comment]
This may be another symptom of the same issue as #5763 ?
