### ISSUE TITLE
File.copy crashes with in-memory io-device as source

### ISSUE THREAD

**Issue by sickill** [elixir-lang/elixir#6163]
### Environment

* Elixir & Erlang versions (elixir --version): 

Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] 
Elixir 1.4.4 (also checked on 1.4.2)

* Operating system: 

macOS 10.12.4

### Current behavior

According to doc of `File.copy`, "Both parameters can be a filename or an IO device opened with open/2". However when you pass in-memory io-device opened with `File.open/2` as source it crashes:

```
iex(1)> {:ok, f} = File.open("Hello world!", [:read, :binary, :ram])
{:ok, {:file_descriptor, :ram_file, #Port<0.1177>}}
iex(2)> File.copy(f, "/tmp/abcd")
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir) lib/io.ex:445: IO.chardata_to_string({:file_descriptor, :ram_file, #Port<0.1177>})
    (elixir) lib/file.ex:435: File.copy/3
```

### Expected behavior

It successfully copies data from source io-device to destination path.

**Comment by sickill** [comment]
That was quick. Thanks!
