### ISSUE TITLE
`restart: :transient` supervisor does not restart async stream tasks

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#6247]
### Environment

* Elixir & Erlang versions (elixir --version): 

```
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.2
```

* Operating system: 

OS X 10.11.4

### Current behavior

``` elixir
defmodule AsyncStreamTest do
  use ExUnit.Case, async: true

  test "async stream tasks started under a `restart: :transient` supervisor should get retried" do
    {:ok, task_sup} = Task.Supervisor.start_link(restart: :transient)
    {:ok, failure_toggle} = Agent.start_link(fn -> true end)

    stream =
      Task.Supervisor.async_stream(task_sup, 1..2, fn i ->
        should_fail? = Agent.get_and_update(failure_toggle, fn fail? -> {fail?, !fail?} end)
        if should_fail?, do: raise "boom"
        i * 2
      end)

    assert Enum.to_list(stream) == [{:ok, 2}, {:ok, 4}]
  end
end
```

This test fails like so:

```
AsyncStreamTest
  * test async stream tasks started under a `restart: :transient` supervisor should get retried (0.00ms)

  1) test async stream tasks started under a `restart: :transient` supervisor should get retried (AsyncStreamTest)
     test/async_stream_test.exs:4
     ** (EXIT from #PID<0.264.0>) an exception was raised:
         ** (RuntimeError) boom
             test/async_stream_test.exs:11: anonymous fn/2 in AsyncStreamTest.test async stream tasks started under a `restart: :transient` supervisor should get retried/1
             (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

     The following output was logged:
     16:47:52.903 [error] Task #PID<0.268.0> started from #PID<0.267.0> terminating
     ** (RuntimeError) boom
         test/async_stream_test.exs:11: anonymous fn/2 in AsyncStreamTest.test async stream tasks started under a `restart: :transient` supervisor should get retried/1
         (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
         (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
         (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
     Function: &:erlang.apply/2
         Args: [#Function<1.41996171/1 in AsyncStreamTest.test async stream tasks started under a `restart: :transient` supervisor should get retried/1>, [1]]
     16:47:52.908 [error] GenServer #PID<0.265.0> terminating
     ** (RuntimeError) boom
         test/async_stream_test.exs:11: anonymous fn/2 in AsyncStreamTest.test async stream tasks started under a `restart: :transient` supervisor should get retried/1
         (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
         (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
         (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
     Last message: {:EXIT, #PID<0.264.0>, {%RuntimeError{message: "boom"}, [{AsyncStreamTest, :"-test async stream tasks started under a `restart: :transient` supervisor should get retried/1-fun-2-", 2, [file: 'test/async_stream_test.exs', line: 11]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 85]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 36]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
```

### Expected behavior

I'd expect the tasks to get retried by the supervisor.  Initially, I went looking at the docs for `Task.async_stream` to see if there is any kind of retry option, but did not find one.  Then I found `Task.Supervisor.async_stream`, and figured that supervisors are the idiomatic Elixir/OTP way to manage restarts/retries, so I expected to be able to compose a `restart: :transient` task supervisor with an async stream and get retries.

**Comment by myronmarston** [comment]
It looks like #4517 is related.  Apparently `restart: :transient` supervisors are only able to restart tasks started with `Task.Supervisor.start_child`.  I confess I've read the issue a few times and don't understand why :(.

**Comment by adelnizamutdinov** [comment]
I'm still getting this issue. What's the correct way of doing `async_stream` with `:transient` ?

**Comment by adelnizamutdinov** [comment]
I guess my question is: I'm looking for a pattern where I can leverage `Task.async_stream`'s `:max_concurrency`, and `Supervisor`'s `:transient`. Any help appreciated
