### ISSUE TITLE
error during streaming: bad file number for :ram_file binstream and Enum.map

### ISSUE THREAD

**Issue by dweinstein** [elixir-lang/elixir#6302]
### Environment

* Elixir & Erlang versions (elixir --version): 

$ elixir --version
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.5

* Operating system: MacOS 10.12.5

### Current behavior

```elixir
iex(5)> {:ok, io} = :file.open("/tmp/foobar", [:binary])
{:ok, #PID<0.494.0>}
iex(6)> io |> IO.binstream(5 * 1024 * 1024) |> Enum.map(&(IO.inspect(&1)))
"this is a test\n"
["this is a test\n"]

# ram file does not work

iex(7)> {:ok, io} = File.open("", [:ram, :write, :binary])
{:ok, {:file_descriptor, :ram_file, #Port<0.11448>}}
iex(8)> :file.write(io, "this is a test")
:ok
iex(9)> io |> IO.binstream(5 * 1024 * 1024) |> Enum.map(&(IO.inspect(&1)))
** (IO.StreamError) error during streaming: bad file number
    (elixir) lib/io.ex:519: IO.each_binstream/2
    (elixir) lib/stream.ex:1257: Stream.do_resource/5
    (elixir) lib/enum.ex:1767: Enum.map/2

```

### Expected behavior

I expected the `:ram_file` to work like a normal file and output the same. It's possible that I've just got totally the wrong idea here and I will accept that.

**Comment by dweinstein** [comment]
oh wow I'm dumb. I forgot `:read` in the `File.open` call for the `:ram_file`:

```elixir
{:ok, io} = File.open("", [:ram, :write, :binary, :read])
:file.write(io, "this is a test")
io |> IO.binstream(5 * 1024 * 1024) |> Enum.map(&(IO.inspect(&1)))
```

so the error message was not super helpful for me.

**Comment by dweinstein** [comment]
got it!

```elixir
iex(21)> {:ok, io} = File.open("", [:ram, :write, :binary, :read])
{:ok, {:file_descriptor, :ram_file, #Port<0.12646>}}
iex(22)> :file.write(io, "this is a test")
:ok
iex(23)> :file.position(io, 0) # move our position back to 0!
{:ok, 0}
iex(24)> io |> IO.binstream(5 * 1024 * 1024) |> Enum.map(&(IO.inspect(&1)))
"this is a test"
["this is a test"]

```
