### ISSUE TITLE
Old struct definitions seem to hang around after a module is recompiled

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#6409]
This may or may not be expected, but it is confusing some of my students.

Given mod.ex:

~~~ elixir
defmodule Mod do
  defstruct  a: 1 #, b: 2
  def new(), do: %Mod{}
end
~~~

Now wander into iex:

~~~
iex> c "mod.ex"
[Mod]
iex> Mod.new
%Mod{a: 1}            # this is expected

# now change mod.ex in another window, adding b: 2 to the defstruct

iex> c "mod.ex"         
warning: redefining module Mod (current version defined in memory)                                   
  mod.ex:1
[Mod]
iex> Mod.new            
%{__struct__: Mod, a: 1}      # no 'b' in the structure, and %{__struct__ visible in structure

iex> c "mod.ex"                   # recompile without changing
warning: redefining module Mod (current version defined in memory)                                   
  mod.ex:1
[Mod]
iex> Mod.new                     # voilà
%Mod{a: 1, b: 2}
~~~

**Comment by coreyhaines** [comment]
I actually get a compilation error.

Given `mod.ex`:
```
defmodule Mod do
  defstruct a: 1

  def new(), do: %Mod{}
end
```

Now wander into iex:
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.4.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> c "mod.ex"
[Mod]
iex(2)> Mod.new
%Mod{a: 1}
```
Now, change `mod.ex`, adding a key and setting it in `new()`
```
defmodule Mod do
  defstruct a: 1, b: 2

  def new(), do: %Mod{ b: 3 }
end
```
Go back to iex (same session as before, evidenced by the (3)) and try to recompile it. Get error.
```
iex(3)> c("mod.ex")
warning: redefining module Mod (current version defined in memory)
  mod.ex:1

== Compilation error on file mod.ex ==
** (KeyError) key :b not found in: %Mod{a: 1}
    (stdlib) :maps.update(:b, 3, %Mod{a: 1})
    mod.ex:2: anonymous fn/2 in Mod.__struct__/1
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding struct: Mod.__struct__/1
    mod.ex:4: Mod.new/0

** (CompileError)  compile error
    (iex) lib/iex/helpers.ex:173: IEx.Helpers.c/2
```

So, while @pragdave can change it and recompile it, I get a compilation error just trying to recompile it.

Of not, it appears we are on different versions. I'm on Erlang/OTP 20, and he's on 19. Also, I'm on iex (1.4.5), and I think Dave is on (1.4.2)

**Comment by coreyhaines** [comment]
NOTE: Just upgraded to Elixir 1.5 and still see the same result

**Comment by coreyhaines** [comment]
Also, just to make it even more minimal of a reproduction, I didn't even call `Mod.new` before trying to recompile. It fails without accessing anything at all.

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.5.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> c("mod.ex")
[Mod]
```
Go and change mod.ex and come back
```
iex(2)> c("mod.ex")
warning: redefining module Mod (current version defined in memory)
  mod.ex:1


== Compilation error in file mod.ex ==
** (KeyError) key :b not found in: %Mod{a: 1}
    (stdlib) :maps.update(:b, 3, %Mod{a: 1})
    mod.ex:2: anonymous fn/2 in Mod.__struct__/1
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding struct: Mod.__struct__/1
    mod.ex:4: Mod.new/0
** (CompileError)  compile error
    (iex) lib/iex/helpers.ex:178: IEx.Helpers.c/2
iex(2)> 
```

**Comment by josevalim** [comment]
That's a bug. Thank you both for the report!
