### ISSUE TITLE
Variables not in scope when PRY'ing a macro

### ISSUE THREAD

**Issue by ShaneWilton** [elixir-lang/elixir#6477]
### Environment

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.5

### Current behavior

When calling `IEx.pry` within a macro, variables from the macro's definition won't be in scope. Consider the following example:

```
defmodule MacroTest.Base do
  defmacro __using__(_opts) do
    quote do
      require IEx

      def foo(bar) do
        IEx.pry
        bar
      end

      defoverridable [foo: 1]
    end
  end
end

defmodule MacroTest do
  use MacroTest.Base

  def foo(bar) do
    super(bar)
  end
end
```

```
╰─$ iex -S mix      
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> MacroTest.foo(5)
Request to pry #PID<0.619.0> at apps/scanner/lib/macro_test.ex:17

    
    defmodule MacroTest do
      use MacroTest.Base
    
      def foo(bar) do

Allow? [Yn] Y

Interactive Elixir (1.4.5) - press Ctrl+C to exit (type h() ENTER for help)
pry(1)> foo
warning: variable "foo" does not exist and is being expanded to "foo()", please use parentheses to remove the ambiguity or change the variable name
  apps/scanner/lib/macro_test.ex:1

** (UndefinedFunctionError) function :erl_eval.foo/0 is undefined or private
     (stdlib) :erl_eval.foo/0
     (stdlib) :erl_eval.expr/3
        (iex) lib/iex/evaluator.ex:182: IEx.Evaluator.handle_eval/6
        (iex) lib/iex/evaluator.ex:175: IEx.Evaluator.do_eval/4
        (iex) lib/iex/evaluator.ex:155: IEx.Evaluator.eval/4
        (iex) lib/iex/evaluator.ex:61: IEx.Evaluator.loop/3
        (iex) lib/iex/evaluator.ex:21: IEx.Evaluator.init/4
        (iex) lib/iex.ex:471: IEx.pry/3
    (scanner) lib/macro_test.ex:17: MacroTest."foo (overridable 1)"/1
```

### Expected behavior

I'm assuming this is because of the way hygienic macros work, but it might come as a surprise. It might make sense to output a warning when calling `IEx.pry` from within a macro, or at least mentioning this case in the documentation for `IEx.pry`.

**Comment by josevalim** [comment]
To add to your report, even if we made it work, you would only be able to access the variables if you use `var!(bar, MacroTest)`. Maybe it even works as such, so I agree, it needs to be documented.

**Comment by ShaneWilton** [comment]
Thanks! This change is exactly what I was looking for :) ❤️ 💚 💙 💛 💜
