### ISSUE TITLE
Feature request: Better error reporting for ArithmeticError

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#6605]
Rationale:
It is rather hard to debug production stack traces like:
```
** (exit) an exception was raised:
    ** (ArithmeticError) bad argument in arithmetic expression
        (my_app) lib/my_app_web/controllers/page_controller.ex:5: MyAppWeb.PageController.index/2
```
or failing tests:
```
  2) test should work (MyApp.MyTest)
     test/my_app/my_test.exs:17
     ** (ArithmeticError) bad argument in arithmetic expression
     code: :ok = Module.function argument
     stacktrace:
       (decimal) lib/decimal.ex:862: Decimal.round/3
       (my_app) lib/my_app/module.ex:9: MyApp.Module.function/1
       test/my_app/my_test.exs:19: (test)
```
without knowing exactly which operation failed and what arguments were passed.

IEx does it right:
```
iex(1)> 32+"sdf"
** (ArithmeticError) bad argument in arithmetic expression
    :erlang.+(32, "sdf")
```
### Environment

* Elixir & Erlang versions (elixir --version): 1.5.1

**Comment by josevalim** [comment]
Thank you! This is fixed in a pull request that I have sent to OTP and it will be available on Erlang 21.
