### ISSUE TITLE
Make string split with an empty string consistent with replace

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7023]
The plan is to reopen #6566.

I am working on it as it also means we need to fix Regex.replace.

**Comment by whatyouhide** [comment]
@josevalim if you come up with good properties for this, hand them over and I'll add them to the few we have in stream_data so we'll not forget about them when we merge.

**Comment by josevalim** [comment]
```elixir
check all left <- string(),
          right <- string(),
          not String.contains?(left, right),
          not String.contains?(right, left) do
  assert String.split(left <> right, left) == ["", right]
  assert String.split(left <> right, right) == [left, ""]
end
```

**Comment by josevalim** [comment]
Here is another one that associates replace + split:

```elixir
check all string <- string(),
          pattern <- string(),
          replacement <- string() do
  assert String.replace(string, pattern, replacement) ==
         string |> String.split(pattern) |> Enum.join(replacement)
end
```

**Comment by whatyouhide** [comment]
Yep, the second one triggers fine:

```
  1) property String.replace/3 is equivalent to String.split/1 + Enum.join/2 (StdlibPropertiesTest)
     test/stdlib_properties_test.exs:17
     Failed with generated values (after 2 successful run(s)):

         string <- string(:printable)
         #=> ""

         pattern <- string(:printable)
         #=> ""

         replacement <- string(:printable)
         #=> "𕐒"

     Assertion with == failed
     code:  assert String.replace(string, pattern, replacement) == string |> String.split(pattern) |> Enum.join(replacement)
     left:  "𕐒"
     right: ""
     stacktrace:
       test/stdlib_properties_test.exs:21: anonymous fn/4 in StdlibPropertiesTest."property String.replace/3 is equivalent to String.split/1 + Enum.join/2"/1
       (stream_data) lib/stream_data.ex:1974: StreamData.shrink_failure/6
       (stream_data) lib/stream_data.ex:1938: StreamData.check_all/6
       test/stdlib_properties_test.exs:18: (test)
```

**Comment by josevalim** [comment]
@whatyouhide could we have shrunk replacement to something simpler? Maybe an alphanumeric character?

**Comment by whatyouhide** [comment]
@josevalim quite nasty to do if we don't special case things. Right now strings are lists of codepoints, and we use `string(:printable)` here and `:printable` means many codepoints.

**Comment by ggcampinho** [comment]
I think this is a nice property to achieve that involves only the `String.replace/3` and `String.split/2`:

```
check all string <- string(),
          pattern <- string(),
          replacement <- string() do
  assert String.replace(string, pattern, replacement) |> String.split(replacement) ==
         String.replace(string, replacement, pattern) |> String.split(pattern)
end
```

**Comment by josevalim** [comment]
@ggcampinho what happens if the pattern is in replacement or vice-versa though? Maybe it works fine but that's typically one of the issues in generalizing replace.

**Comment by ggcampinho** [comment]
@josevalim The nice thing about things property is that the generalization works:

```
iex(1)> string = "abcabcabc" 
"abcabcabc"
iex(2)> pattern = "b"
"b"
iex(3)> replacement = "-"
"-"
iex(4)> String.replace(string, pattern, replacement) |> String.split(replacement)
["a", "ca", "ca", "c"]
iex(5)> String.replace(string, replacement, pattern) |> String.split(pattern)
["a", "ca", "ca", "c"]
iex(6)> pattern = "b"
"b"
iex(7)> replacement = "c"
"c"
iex(8)> String.replace(string, pattern, replacement) |> String.split(replacement)
["a", "", "a", "", "a", "", ""]
iex(9)> String.replace(string, replacement, pattern) |> String.split(pattern)    
["a", "", "a", "", "a", "", ""]
iex(10)> pattern = "-"                                                            
"-"
iex(11)> replacement = "c"                                                        
"c"
iex(12)> String.replace(string, pattern, replacement) |> String.split(replacement)
["ab", "ab", "ab", ""]
iex(13)> String.replace(string, replacement, pattern) |> String.split(pattern)    
["ab", "ab", "ab", ""]
iex(14)> pattern = "-"                                                            
"-"
iex(15)> replacement = "d"                                                        
"d"
iex(16)> String.replace(string, pattern, replacement) |> String.split(replacement)
["abcabcabc"]
iex(17)> String.replace(string, replacement, pattern) |> String.split(pattern)    
["abcabcabc"]
iex(18)> pattern = "b"                                                            
"b"
iex(19)> replacement = "b"                                                        
"b"
iex(20)> String.replace(string, pattern, replacement) |> String.split(replacement)
["a", "ca", "ca", "c"]
iex(21)> String.replace(string, replacement, pattern) |> String.split(pattern)    
["a", "ca", "ca", "c"]
```

The general cases:
- `pattern` that exists inside of the string with `replacement` that doesn't
- `replacement` that exists inside of the string `pattern` with that doesn't
- `pattern` that exists inside of the string with `replacement` that also exists
- `pattern` that doesn't exist inside of the string with `replacement` that also doesn't
- `pattern` and `replacement` that are the same and exist inside of the string

Of course, the problem today is with `""` (but I'm surprised with the error):
```
iex(22)> pattern = "b"                                                            
"b"
iex(23)> replacement = ""                                                         
""
iex(24)> String.replace(string, pattern, replacement) |> String.split(replacement)
["a", "c", "a", "c", "a", "c", ""]
iex(25)> String.replace(string, replacement, pattern) |> String.split(pattern)    
** (ArgumentError) argument error
    (stdlib) binary.erl:275: :binary.replace/4
```

**Comment by ggcampinho** [comment]
Sorry, I've read it wrong. You're right, that causes a problem in some cases.

**Comment by ggcampinho** [comment]
I did a couple more tests and I don't know if it means much, but this works with substrings:

```
iex(54)> pattern = "ab"                                                                                                 
"ab"
iex(55)> replacement = "a"                                                                                              
"a"
iex(56)> String.replace(string, pattern, replacement) |> String.split(String.replace(replacement, pattern, replacement))
["", "c", "c", "c"]
iex(57)> String.replace(string, replacement, pattern) |> String.split(String.replace(pattern, replacement, pattern))    
["", "c", "c", "c"]
iex(62)> pattern = "a"                                                                                                   
"a"
iex(63)> replacement = "ab"                                                                                              
"ab"
iex(64)> String.replace(string, pattern, replacement) |> String.split(String.replace(replacement, pattern, replacement)) 
["", "c", "c", "c"]
iex(65)> String.replace(string, replacement, pattern) |> String.split(String.replace(pattern, replacement, pattern))     
["", "c", "c", "c"]
```
