### ISSUE TITLE
Stream.chunk_while results in error when enumerating with Enum.at

### ISSUE THREAD

**Issue by galina** [elixir-lang/elixir#7112]
As described in

https://elixirforum.com/t/stream-chunk-while-error-when-enumerating/10809

`Stream.chunk_while` enumerated with `Enum.at` results in error

(elixir version is 1.5.1)

the code:

```elixir
chunk_fun = fn
  i, [] ->
    {:cont, [i]}
  i, chunk ->
    if rem(i, 2) == 0 do
      {:cont, Enum.reverse(chunk), [i]}
    else
      {:cont, [i | chunk]}
    end
end
after_fun = fn
  [] -> {:cont, []}
  chunk -> {:cont, Enum.reverse(chunk), []}
end
stream = [1, 2, 3, 4, 5] |> Stream.chunk_while([], chunk_fun, after_fun)
```

calling `stream |> Enum.at(0)` gives this error:

```
** (ArithmeticError) bad argument in arithmetic expression
    (elixir) lib/enum.ex:793: anonymous fn/3 in Enum.fetch_enumerable/3
    (elixir) lib/stream.ex:1413: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir) lib/stream.ex:234: Stream.after_chunk_while/3
    (elixir) lib/stream.ex:1446: Enumerable.Stream.do_done/2
    (elixir) lib/enum.ex:789: Enum.fetch_enumerable/3
    (elixir) lib/enum.ex:311: Enum.at/3
```

**Comment by albertoalmagro** [comment]
Could be related to #7096 , if it is I could take a look after finishing it.

**Comment by albertoalmagro** [comment]
I have already finished with the other issue so I can take care of this.

**Comment by albertoalmagro** [comment]
HI @josevalim , this is still failing in version 1.5.3. What was the reason to close it? Thanks!

**Comment by albertoalmagro** [comment]
Ok, already saw the commit in the PC, sorry for the noise.
