### ISSUE TITLE
Elixir won't compile under WSL

### ISSUE THREAD

**Issue by cmeiklejohn** [elixir-lang/elixir#7200]
### Environment

* Elixir & Erlang versions (elixir --version): 19.3, Elixir HEAD@cbcdcb1623be11e1ff0bd0bd46cb812c563c3bbd
* Operating system: Ubuntu on Windows Subsystem for Linux for Windows 10

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

### Current behavior

Should compile, but fails because of possible line formatting issue with CRLF/LF.

```
$ make
==> elixir (compile)
==> eex (compile)
../../bin/elixirc: 34: ../../bin/elixirc: Syntax error: end of file unexpected (expecting "then")
Makefile:92: recipe for target 'lib/eex/ebin/Elixir.EEx.beam' failed
make: *** [lib/eex/ebin/Elixir.EEx.beam] Error 2
```

### Expected behavior

Should compile.

**Comment by josevalim** [comment]
Thanks for the report.

The line endings are by default LF but Git often does the converting to CRLF automatically on Windows systems depending on the autocrlf configuration. I am suspecting the conversion is happening and bash for Ubuntu is not enjoying the line endings.

You can try to validate this by running the command below and let us know if you see CRLF in there:

```erl
1> file:read_file("bin/elixirc").
{ok,<<"#!/bin/sh\r\nif [ $# -eq 0 ] || [ \"$1\" = \"--help\" ] || [ \"$1\" = \"-h\" ]; then\r\n  echo \"Usage: `basename $0` [el"...>>}
```

If so, setting autocrlf in git may help fix it.

**Comment by josevalim** [comment]
Yeah, so that looks like the root cause. Bash also gets very unhappy when I use CRLF as line endings on my machine. If you remove CRLF by disabling autocrlf or by running dos2unix, does it work?

**Comment by cmeiklejohn** [comment]
Switching the autocrlf setting for the repository didn't seem to fix anything for me, however, running dos2unix on the bin/elixirc file seemed to have done the trick.

However, now it's failing somewhere else.

```
cmeiklejohn@LAPTOP-SE7JB8LF:~/elixir$ dos2unix bin/elixirc
dos2unix: converting file bin/elixirc to Unix format ...
cmeiklejohn@LAPTOP-SE7JB8LF:~/elixir$ dos2unix bin/elixir
dos2unix: converting file bin/elixir to Unix format ...
cmeiklejohn@LAPTOP-SE7JB8LF:~/elixir$ make
==> elixir (compile)
==> eex (compile)
warning: module Exception is not a behaviour (in module EEx.SyntaxError)
  lib/eex.ex:1

==> mix (compile)
warning: module Exception is not a behaviour (in module Mix.Config.LoadError)
  lib/mix/config.ex:33

warning: module Exception is not a behaviour (in module Mix.NoTaskError)
  lib/mix/exceptions.ex:1

warning: module Exception is not a behaviour (in module Mix.InvalidTaskError)
  lib/mix/exceptions.ex:45

warning: module Exception is not a behaviour (in module Mix.ElixirVersionError)
  lib/mix/exceptions.ex:54

warning: module Exception is not a behaviour (in module Mix.NoProjectError)
  lib/mix/exceptions.ex:70

warning: module Exception is not a behaviour (in module Mix.Error)
  lib/mix/exceptions.ex:77


== Compilation error in file lib/mix/tasks/new.ex ==
** (UndefinedFunctionError) function Access.get/3 is undefined (module Access is not available)
    Access.get([file: "/home/cmeiklejohn/elixir/lib/mix/lib/mix/tasks/new.ex", line: 224], :line, nil)
    lib/mix/tasks/new.ex:224: anonymous fn/2 in :elixir_compiler_34.__MODULE__/1
    (elixir) /home/cmeiklejohn/elixir/lib/elixir/lib/enum.ex:1296: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/new.ex:224: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
** (UndefinedFunctionError) function List.Chars.to_charlist/1 is undefined (module List.Chars is not avai
lable)
    List.Chars.to_charlist("lib/mix/tasks/new.ex")
    (elixir) /home/cmeiklejohn/elixir/lib/elixir/lib/kernel/parallel_compiler.ex:468: Kernel.ParallelComp
iler.get_line/3
    (elixir) /home/cmeiklejohn/elixir/lib/elixir/lib/kernel/parallel_compiler.ex:457: Kernel.ParallelComp
iler.to_error/4
    (elixir) /home/cmeiklejohn/elixir/lib/elixir/lib/kernel/parallel_compiler.ex:360: Kernel.ParallelComp
iler.wait_for_messages/6
    (elixir) /home/cmeiklejohn/elixir/lib/elixir/lib/kernel/parallel_compiler.ex:129: Kernel.ParallelComp
iler.spawn_workers/3
    (elixir) /home/cmeiklejohn/elixir/lib/elixir/lib/kernel/cli.ex:470: anonymous fn/2 in Kernel.CLI.proc
ess_command/2
Makefile:93: recipe for target 'lib/mix/ebin/Elixir.Mix.beam' failed
make: *** [lib/mix/ebin/Elixir.Mix.beam] Error 1
cmeiklejohn@LAPTOP-SE7JB8LF:~/elixir$
```

**Comment by cmeiklejohn** [comment]
It looks like what I needed to do was the following:

```
find . -type f | xargs dos2unix
```

**Comment by cmeiklejohn** [comment]
Resulting test failures from `make test` 

```
 1) test binread all (IOTest)
     test/elixir/io_test.exs:28
     Assertion with == failed
     code:  assert "LF\nCR\rCRLF\r\nLFCR\n\r" == IO.binread(file, :all)
     left:  "LF\nCR\rCRLF\r\nLFCR\n\r"
     right: "LF\nCR\rCRLF\nLFCR\n\r"
     stacktrace:
       test/elixir/io_test.exs:30: (test)

.........................................................

  2) test stream keeps BOM (FileTest)
     test/elixir/file_test.exs:1449
     Assertion with == failed
     code:  assert [<<239, 187, 191>> <> "Русский\n"] == bom_line
     left:  ["\uFEFFРусский\n"]
     right: ["Русский\n"]
     stacktrace:
       test/elixir/file_test.exs:1457: (test)

.........................................................................................................
............................

Finished in 43.4 seconds (20.4s on load, 22.9s on tests)
1367 doctests, 2842 tests, 2 failures

Randomized with seed 280425
Makefile:214: recipe for target 'test_stdlib' failed
make: *** [test_stdlib] Error 1
```

**Comment by josevalim** [comment]
I am curious, what do you get for os:type?

```erlang
$ erl
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
1> os:type().
{unix,darwin}
```

?

If it returns Windows... then our tests are expecting CRLF in there.

Note those particular tests pass on [appveyor - Windows CI](https://ci.appveyor.com/project/josevalim/elixir/build/1-jv-remove-load+1949#L98).

**Comment by josevalim** [comment]
Actually, I see what happened. We had some files with literal CRLF in them but dos2unix removed them and stripped the BOMs, which broke the tests!

**Comment by cmeiklejohn** [comment]
It's a full Ubuntu instance running inside of the Linux subsystem, so it reports as Linux.

```
cmeiklejohn@LAPTOP:/mnt/c/Users/chris$ erl
osErlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V8.3  (abort with ^G)
1> os:type().
{unix,linux}
2>
```

**Comment by josevalim** [comment]
Ah, that's better!

Given that those files originally had CRLF and BOM in them and they were stripped away by dos2unix, you can try fix them by hand or by reverting them on Git explicitly. Then all of your tests should pass.

Is there anything else we can do on our side to close this issue?

**Comment by cmeiklejohn** [comment]
No, thanks for all of your help!
