### ISSUE TITLE
Handle nested bitstring pattern matching failure in a better way

### ISSUE THREAD

**Issue by lexmag** [elixir-lang/elixir#7368]
```elixir
<<?-, (<<next, _::binary>> = rest)::binary>> = "-abc"
```

**Comment by OvermindDL1** [comment]
Doesn't the example above not replicate an issue as it looks like it works?

Testing:

```elixir
╰─➤  iex
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.6.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> <<?-, (<<next, _::binary>> = rest)::binary>> = "-abc"
"-abc"
iex(2)> next
97
```

**Comment by lexmag** [comment]
@OvermindDL1 it does work when evaluated in IEx, but fails when it gets compiled (and properly linted).

**Comment by OvermindDL1** [comment]
Ah, for documentative purposes, here's the error when compiled:

```elixir
╰─➤  elixir tester.exs
** (CompileError) tester.exs:1: illegal pattern
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) lib/code.ex:677: Code.require_file/2
