### ISSUE TITLE
No line number on error when using invalid struct key

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#7752]
### Environment

Erlang/OTP 20 [erts-9.3.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.5 (compiled with OTP 20)

### Current behavior

When compiling `lib/my_app/my_module.ex`
```
defmodule MyApp.MyModule do
  def my_function do
    %MyApp.MyStruct{not_existing_key: 1}
  end
end
```
the compiler crashes and outputs no line number 
```
== Compilation error in file lib/my_app/my_module.ex ==
** (KeyError) key : not_existing_key not found in: %MyApp.MyStruct{key: nil}
    (stdlib) :maps.update(:modifier, 1.1, %MyApp.MyStruct{key: nil})
    lib/my_app/my_struct.ex:6: anonymous fn/2 in MyApp.MyStruct.__struct__/1
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
```

It works for similar code

```
defmodule MyApp.MyModule do
  def my_function(%MyApp.MyStruct{not_existing_key: 1}) do
    :ok
  end
end
```

```
== Compilation error in file lib/my_app/my_module.ex ==
** (CompileError) lib/my_app/my_module.ex:2: unknown key : not_existing_key for struct MyApp.MyStruct
    lib/my_app/my_module.ex:2: (module)
```

```
defmodule MyApp.MyModule do
  def my_function(param) do
    %MyApp.MyStruct{not_existing_key: a} = param
    a
  end
end
```

```
== Compilation error in file lib/my_app/my_module.ex ==
** (CompileError) lib/my_app/my_module.ex:3: unknown key : not_existing_key for struct MyApp.MyStruct
    lib/my_app/my_module.ex:3: (module)
```
### Expected behavior
Explicit line number in error message

**Comment by Tuxified** [comment]
Has this been claimed? If not ... 😁

**Comment by josevalim** [comment]
Closing in favor of #7778.
