### ISSUE TITLE
`mix docs` fails on https://github.com/elixir-lang/elixir/commit/17e819d

### ISSUE THREAD

**Issue by mindreframer** [elixir-lang/elixir#7884]
Hello, 
yesterday I updated my Elixir dev installation and now publishing to Hex is broken, because docs generation fails.  

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
elixir --version
Erlang/OTP 21 [erts-10.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.0-dev (17e819d) (compiled with Erlang/OTP 21)
```
* Operating system:  OSX 

### Current behavior
```bash 
$ mix docs
** (RuntimeError) module Bam was not compiled with flag --docs
    (ex_doc) lib/ex_doc/retriever.ex:154: ExDoc.Retriever.export_docs?/1
    (ex_doc) lib/ex_doc/retriever.ex:138: ExDoc.Retriever.get_module/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc) lib/ex_doc/retriever.ex:116: ExDoc.Retriever.docs_from_modules/2
    (ex_doc) lib/ex_doc.ex:107: ExDoc.generate_docs/3
    (ex_doc) lib/mix/tasks/docs.ex:202: anonymous fn/6 in Mix.Tasks.Docs.run/3
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc) lib/mix/tasks/docs.ex:201: Mix.Tasks.Docs.run/3
```

### Expected behavior (on Elixir 1.6.6 in docker)

```bash 
$ mix docs
==> earmark
Compiling 3 files (.erl)
Compiling 24 files (.ex)
Generated earmark app
==> ex_doc
Compiling 15 files (.ex)
Generated ex_doc app
==> bam
Compiling 1 file (.ex)
Generated bam app
Docs successfully generated.
View them at "doc/index.html".
```

### Steps to reproduce

```
$ mix new bam
... edit mix.exs to include `{:ex_doc, ">= 0.0.0", only: :dev}`
$ mix docs
```

**Comment by josevalim** [comment]
Yes, this is expected. You need to use ex_doc master (soon to be released too).

**Comment by mindreframer** [comment]
wow, that was quick... 💨 thanks a lot!
