### ISSUE TITLE
Credo exiting in our CI environment in load_validate_source_files.ex due to time-out.

### ISSUE THREAD

**Issue by jeremyowensboggs** [elixir-lang/elixir#8081]
Credo in our CI environment has been timing out in load_and_validate_source_files.ex.  Here is what is displayed:
```
** (exit) exited in: Task.await(%Task{owner: #PID<0.74.0>, pid: #PID<0.406.0>, ref: #Reference<0.2449986766.523763713.102619>}, 5000)
    ** (EXIT) time out
    (elixir) lib/task.ex:501: Task.await/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    lib/credo/cli/task/load_and_validate_source_files.ex:11: anonymous fn/1 in Credo.CLI.Task.LoadAndValidateSourceFiles.call/2
    (stdlib) timer.erl:166: :timer.tc/1
    lib/credo/cli/task/load_and_validate_source_files.ex:9: Credo.CLI.Task.LoadAndValidateSourceFiles.call/2
    lib/credo/cli/command/suggest/suggest_command.ex:15: Credo.CLI.Command.Suggest.SuggestCommand.call/2
    lib/credo/execution/task.ex:45: Credo.Execution.Task.do_run/3
```

Tracing through the code, it looks like the problem part is here: 
https://github.com/rrrene/credo/blob/b457ef46a21d97b5aa84f65d4de28c8da02f0829/lib/credo/sources.ex#L30
What I think is happening is that the awaiting is happening in a serial fashion, so that it is possible the particular process that is being awaited on is not completing within the allotted 5 seconds, when other are?

**Comment by jeremyowensboggs** [comment]
No, I am not in the correct repo sorry about that.
