### ISSUE TITLE
Stream.cycle constructed with range appears not to repeat through Stream.zip

### ISSUE THREAD

**Issue by epiccoleman** [elixir-lang/elixir#8209]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.7.3
* Operating system: macOS High Sierra 10.13.4

### Current behavior
This line works: 
`Stream.zip(1..255, Stream.cycle(1..5)) |> Enum.take(5)`
and produces this output: 
`[{1, 1}, {2, 2}, {3, 3}, {4, 4}, {5, 5}]`

However, this line: 
`Stream.zip(1..255, Stream.cycle(1..5)) |> Enum.take(6)`
fails, and throws this error:
`(ArgumentError) cannot cycle over empty enumerable`

This line, on the other hand
`Stream.zip(1..255, Stream.cycle([1, 2, 3, 4, 5]) |> Enum.take(6)`
produces the expected output: 
`[{1, 1}, {2, 2}, {3, 3}, {4, 4}, {5, 5}, {6, 1}`

### Expected behavior
We expect that this line of code:
`Stream.zip(1..255, Stream.cycle(1..5)) |> Enum.take(6)`
should have returned: 
`[{1, 1}, {2, 2}, {3, 3}, {4, 4}, {5, 5}, {6, 1}`

It appears that the problem has something to do with the use of a range in `Stream.cycle` / `Stream.zip`, since using a list as the argument to `Stream.cycle` works as expected (as in the third example in the Current Behavior section).

**Comment by aerosol** [comment]
I'm having trouble getting a meaningful conclusion from the following trace fragment:

```
** (Dbg) #PID<0.153.0> calls Enumerable.reduce/3 with arguments:
    [1..2, {:cont, []}, #Function<89.66371359/2 in Stream.cycle/1>]

** (Dbg) #PID<0.153.0> calls Enum.split_with/2 with arguments:
    [
      [message: "cannot cycle over empty enumerable"],
      #Function<1.92806469/1 in ArgumentError.exception/1>
    ]
```

What is exactly the lambda being passed there? Is there any way to trace any details about it?

Here's to the hope that this will be helpful in pursuit of a minimal test-case:

```
iex(5)> Stream.zip(1..3, Stream.cycle(1..2)) |> Enum.into([])
** (ArgumentError) cannot cycle over empty enumerable
    (elixir) lib/stream.ex:1264: Stream.do_cycle/3
    (elixir) lib/stream.ex:1174: Stream.do_zip_next_tuple/5
    (elixir) lib/stream.ex:1151: Stream.do_zip/3
    (elixir) lib/enum.ex:2979: Enum.reverse/1
    (elixir) lib/enum.ex:2613: Enum.to_list/1
    (elixir) lib/enum.ex:1184: Enum.into/2
```

```
iex(10)> Stream.zip(1..3, Stream.cycle(1..2)) |> Enum.into([])

** (Dbg) #PID<0.153.0> calls Enum.__info__/1 with arguments:
    [:deprecated]

** (Dbg) #PID<0.153.0> calls Enum.__info__/1 with arguments:
    [:macros]

** (Dbg) #PID<0.153.0> calls Stream.__info__/1 with arguments:
    [:deprecated]

** (Dbg) #PID<0.153.0> calls Stream.__info__/1 with arguments:
    [:macros]

** (Dbg) #PID<0.153.0> calls Stream.__info__/1 with arguments:
    [:deprecated]

** (Dbg) #PID<0.153.0> calls Stream.__info__/1 with arguments:
    [:macros]

** (Dbg) #PID<0.153.0> calls Stream.cycle/1 with arguments:
    [1..2]

** (Dbg) #PID<0.153.0> calls Stream.zip/2 with arguments:
    [1..3, #Function<9.66371359/2 in Stream.cycle/1>]

** (Dbg) #PID<0.153.0> calls Enum.into/2 with arguments:
    [#Function<68.66371359/2 in Stream.zip/1>, []]

** (Dbg) #PID<0.153.0> calls Enumerable.reduce/3 with arguments:
    [
      #Function<68.66371359/2 in Stream.zip/1>,
      {:cont, []},
      #Function<133.23002632/2 in Enum.reverse/1>
    ]

** (Dbg) #PID<0.153.0> calls Enum.map/2 with arguments:
    [
      [1..3, #Function<9.66371359/2 in Stream.cycle/1>],
      #Function<51.66371359/1 in Stream.prepare_zip/3>
    ]

** (Dbg) #PID<0.153.0> calls Enumerable.reduce/3 with arguments:
    [1..3, {:cont, []}, #Function<50.66371359/2 in Stream.prepare_zip/3>]

** (Dbg) #PID<0.153.0> calls Enumerable.reduce/3 with arguments:
    [
      #Function<9.66371359/2 in Stream.cycle/1>,
      {:cont, []},
      #Function<50.66371359/2 in Stream.prepare_zip/3>
    ]

** (Dbg) #PID<0.153.0> calls Enumerable.reduce/3 with arguments:
    [1..2, {:cont, []}, #Function<89.66371359/2 in Stream.cycle/1>]

** (Dbg) #PID<0.153.0> calls Enum.split_with/2 with arguments:
    [
      [message: "cannot cycle over empty enumerable"],
      #Function<1.92806469/1 in ArgumentError.exception/1>
    ]

** (Dbg) #PID<0.153.0> calls Enum.reduce/3 with arguments:
    [
      [message: "cannot cycle over empty enumerable"],
      %ArgumentError{message: "argument error"},
      #Function<18.42554235/2 in Kernel.struct!/2>
    ]

** (Dbg) #PID<0.153.0> calls Enum.reverse/1 with arguments:
    [
      [
        {Stream, :do_cycle, 3, [file: 'lib/stream.ex', line: 1264]},
        {Stream, :do_zip_next_tuple, 5, [file: 'lib/stream.ex', line: 1174]},
        {Stream, :do_zip, 3, [file: 'lib/stream.ex', line: 1151]},
        {Enum, :reverse, 1, [file: 'lib/enum.ex', line: 2979]},
        {Enum, :to_list, 1, [file: 'lib/enum.ex', line: 2613]},
        {Enum, :into, 2, [file: 'lib/enum.ex', line: 1184]},
        {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 670]},
        {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 265]}
      ]
    ]

** (Dbg) #PID<0.153.0> calls Enum.drop_while/2 with arguments:
    [
      [
        {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 265]},
        {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 670]},
        {Enum, :into, 2, [file: 'lib/enum.ex', line: 1184]},
        {Enum, :to_list, 1, [file: 'lib/enum.ex', line: 2613]},
        {Enum, :reverse, 1, [file: 'lib/enum.ex', line: 2979]},
        {Stream, :do_zip, 3, [file: 'lib/stream.ex', line: 1151]},
        {Stream, :do_zip_next_tuple, 5, [file: 'lib/stream.ex', line: 1174]},
        {Stream, :do_cycle, 3, [file: 'lib/stream.ex', line: 1264]}
      ],
      #Function<4.71522130/1 in IEx.Evaluator.prune_stacktrace/1>
    ]

** (Dbg) #PID<0.153.0> calls Enum.drop_while/2 with arguments:
    [
      [
        {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 265]},
        {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 670]},
        {Enum, :into, 2, [file: 'lib/enum.ex', line: 1184]},
        {Enum, :to_list, 1, [file: 'lib/enum.ex', line: 2613]},
        {Enum, :reverse, 1, [file: 'lib/enum.ex', line: 2979]},
        {Stream, :do_zip, 3, [file: 'lib/stream.ex', line: 1151]},
        {Stream, :do_zip_next_tuple, 5, [file: 'lib/stream.ex', line: 1174]},
        {Stream, :do_cycle, 3, [file: 'lib/stream.ex', line: 1264]}
      ],
      #Function<5.71522130/1 in IEx.Evaluator.prune_stacktrace/1>
    ]

** (Dbg) #PID<0.153.0> calls Enum.drop_while/2 with arguments:
    [
      [
        {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 265]},
        {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 670]},
        {Enum, :into, 2, [file: 'lib/enum.ex', line: 1184]},
        {Enum, :to_list, 1, [file: 'lib/enum.ex', line: 2613]},
        {Enum, :reverse, 1, [file: 'lib/enum.ex', line: 2979]},
        {Stream, :do_zip, 3, [file: 'lib/stream.ex', line: 1151]},
        {Stream, :do_zip_next_tuple, 5, [file: 'lib/stream.ex', line: 1174]},
        {Stream, :do_cycle, 3, [file: 'lib/stream.ex', line: 1264]}
      ],
      #Function<6.71522130/1 in IEx.Evaluator.prune_stacktrace/1>
    ]

** (Dbg) #PID<0.153.0> calls Enum.drop_while/2 with arguments:
    [
      [
        {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 670]},
        {Enum, :into, 2, [file: 'lib/enum.ex', line: 1184]},
        {Enum, :to_list, 1, [file: 'lib/enum.ex', line: 2613]},
        {Enum, :reverse, 1, [file: 'lib/enum.ex', line: 2979]},
        {Stream, :do_zip, 3, [file: 'lib/stream.ex', line: 1151]},
        {Stream, :do_zip_next_tuple, 5, [file: 'lib/stream.ex', line: 1174]},
        {Stream, :do_cycle, 3, [file: 'lib/stream.ex', line: 1264]}
      ],
      #Function<7.71522130/1 in IEx.Evaluator.prune_stacktrace/1>
    ]

** (Dbg) #PID<0.153.0> calls Enum.reverse/1 with arguments:
    [
      [
        {Enum, :into, 2, [file: 'lib/enum.ex', line: 1184]},
        {Enum, :to_list, 1, [file: 'lib/enum.ex', line: 2613]},
        {Enum, :reverse, 1, [file: 'lib/enum.ex', line: 2979]},
        {Stream, :do_zip, 3, [file: 'lib/stream.ex', line: 1151]},
        {Stream, :do_zip_next_tuple, 5, [file: 'lib/stream.ex', line: 1174]},
        {Stream, :do_cycle, 3, [file: 'lib/stream.ex', line: 1264]}
      ]
    ]

** (Dbg) #PID<0.153.0> calls Enum.reject/2 with arguments:
    [
      [
        {Stream, :do_cycle, 3, [file: 'lib/stream.ex', line: 1264]},
        {Stream, :do_zip_next_tuple, 5, [file: 'lib/stream.ex', line: 1174]},
        {Stream, :do_zip, 3, [file: 'lib/stream.ex', line: 1151]},
        {Enum, :reverse, 1, [file: 'lib/enum.ex', line: 2979]},
        {Enum, :to_list, 1, [file: 'lib/enum.ex', line: 2613]},
        {Enum, :into, 2, [file: 'lib/enum.ex', line: 1184]}
      ],
      #Function<8.71522130/1 in IEx.Evaluator.prune_stacktrace/1>
    ]

** (Dbg) #PID<0.153.0> calls Enum.map_join/3 with arguments:
    [
      [
        {Stream, :do_cycle, 3, [file: 'lib/stream.ex', line: 1264]},
        {Stream, :do_zip_next_tuple, 5, [file: 'lib/stream.ex', line: 1174]},
        {Stream, :do_zip, 3, [file: 'lib/stream.ex', line: 1151]},
        {Enum, :reverse, 1, [file: 'lib/enum.ex', line: 2979]},
        {Enum, :to_list, 1, [file: 'lib/enum.ex', line: 2613]},
        {Enum, :into, 2, [file: 'lib/enum.ex', line: 1184]}
      ],
      "\n    ",
      #Function<3.10053414/1 in Exception.format_stacktrace/1>
    ]
** (ArgumentError) cannot cycle over empty enumerable
    (elixir) lib/stream.ex:1264: Stream.do_cycle/3
    (elixir) lib/stream.ex:1174: Stream.do_zip_next_tuple/5
    (elixir) lib/stream.ex:1151: Stream.do_zip/3
    (elixir) lib/enum.ex:2979: Enum.reverse/1
    (elixir) lib/enum.ex:2613: Enum.to_list/1
    (elixir) lib/enum.ex:1184: Enum.into/2
```

**Comment by ggcampinho** [comment]
Hey @aerosol, are you working on this? I believe I have a fix for the issue

**Comment by aerosol** [comment]
@ggcampinho excellent, go for it :ok_hand:
