### ISSUE TITLE
Undefined typespec error on invalid type annotations (involving pipe operator)

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#8235]
Follow up of the discussion on https://github.com/elixir-lang/elixir/pull/8234#discussion_r221400922

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
  ```
   Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

  Elixir 1.8.0-dev (25cf841c2) (compiled with Erlang/OTP 21)
  ```
* Operating system: Mac OS X 10.13.6 

### Current behavior

Before the changes on #8163 and #8202 , this code didn't raise any errors:

```elixir
$ iex
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.7.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule Foo do
...(1)>   @type dest :: pid | port | registered_name :: atom
...(1)> end
{:module, Foo,
 <<70, 79, 82, 49, 0, 0, 3, 140, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 117,
   0, 0, 0, 12, 10, 69, 108, 105, 120, 105, 114, 46, 70, 111, 111, 8, 95, 95,
   105, 110, 102, 111, 95, 95, 7, 99, 111, ...>>, :ok}
```

After the changes on #8163 and #8202:

```elixir
 $ bin/iex
 Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

 Interactive Elixir (1.8.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
 iex(1)> defmodule Foo do
 ...(1)>   @type dest :: pid | port | registered_name :: atom
 ...(1)> end
 warning: invalid type annotation. When using the | operator to represent the union of types, make sure to wrap type annotations in parentheses: pid | port | registered_name :: atom
   iex:2

 ** (CompileError) iex:2: type registered_name/0 undefined
     (elixir) lib/kernel/typespec.ex:847: Kernel.Typespec.compile_error/2
     (elixir) lib/kernel/typespec.ex:788: Kernel.Typespec.typespec/4
     (elixir) lib/enum.ex:1430: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
     (elixir) lib/enum.ex:1430: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
     (elixir) lib/kernel/typespec.ex:420: Kernel.Typespec.typespec/4
     (elixir) lib/kernel/typespec.ex:639: Kernel.Typespec.typespec/4
     (elixir) lib/kernel/typespec.ex:265: Kernel.Typespec.translate_type/2
     (elixir) lib/enum.ex:1430: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

### Expected behavior

It should not raise a `CompileError`.

### Proposal

In https://github.com/elixir-lang/elixir/pull/8234#discussion_r221400922, @josevalim suggested:

> The undefined_type check made the warning obsolete. I think what erlang is doing is that it is considering everything on the left-side of `::` to be "defined". Maybe we can do the same change here temporarily? We could do this by storing a flag on the state that says that we are on the left side of a `::`.

**Note:** I'm currently working on this one

**Comment by fertapric** [comment]
@josevalim should we backport the warning  `invalid type annotation. When using the | operator to represent the union of types, make sure to wrap type annotations in parentheses` to v1.7, so after a new release people can start fixing the invalid type expression? And then, in v1.9, raise the `CompileError`?

Right now the comments for that warning say `TODO: make this an error in elixir 2.0 and remove code below`

**Comment by josevalim** [comment]
Yes, let’s backport the warning!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fertapric** [comment]
Sounds good to me! 

I also thought about cases like `@type dest :: pid | doesnt_exist | ann_type :: atom`, in which the undefined type `doesnt_exist` would be masquerade by the warning. But, once the user fixes the warning, the code will raise a `CompileError` on `doesnt_exist`, so I guess we are good!
