### ISSUE TITLE
Compile issue in case of `compile_time_purge_matching` logger option

### ISSUE THREAD

**Issue by van-mronov** [elixir-lang/elixir#8389]
### Precheck

Adding logger compile_time_purge_matching option is causing ecto compilation fail.

### Environment

* Elixir version (elixir -v): 1.7.4
* Ecto version (mix deps): 3.0.1
* Operating system: Mac OS X

### Current behavior

[Here](https://github.com/van-mronov/ecto_demo) is an example of application.

```elixir
config :logger,
  compile_time_purge_matching: [
    [application: :ecto_demo, level_lower_than: :info]
  ]
```

```sh
$ mix deps.compile ecto
==> ecto
Compiling 1 file (.ex)

== Compilation error in file lib/ecto/log_entry.ex ==
** (FunctionClauseError) no function clause matching in Keyword.fetch/2

    The following arguments were given to Keyword.fetch/2:

        # 1
        {:metadata, [line: 50], nil}

        # 2
        :application

    Attempted function clauses (showing 1 out of 1):

        def fetch(keywords, key) when is_list(keywords) and is_atom(key)

    (elixir) lib/keyword.ex:362: Keyword.fetch/2
    (logger) lib/logger.ex:829: anonymous fn/4 in Logger.compile_time_purge_matching?/2
    (elixir) lib/enum.ex:2850: Enum.all_list/2
    (elixir) lib/enum.ex:2864: Enum.any_list/2
    (logger) lib/logger.ex:800: Logger.macro_log/4
    (logger) expanding macro: Logger.log/3
    lib/ecto/log_entry.ex:50: Ecto.LogEntry.log/3
could not compile dependency :ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile ecto", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

### Expected behavior

It is compiled.

**Comment by van-mronov** [comment]
@josevalim I'm able to reproduce this with following test:
```elixir
test "remove unused calls at compile time based on matched application" do
  Logger.configure(
    compile_time_application: nil,
    compile_time_purge_matching: [
      [application: :sample_app, level_lower_than: :info]
    ]
  )

  defmodule SampleNoApp do
    def log(level, metadata \\ []) do
      Logger.log(level, "ok", metadata)
    end
  end

  assert capture_log(fn ->
           assert SampleNoApp.log(:info) == :ok
         end) =~ msg("module=LoggerTest.SampleNoApp [info]  ok")

  Logger.configure(
    compile_time_application: :sample_app,
    compile_time_purge_matching: [
      [application: :sample_app, level_lower_than: :info]
    ]
  )

  defmodule SampleNoApp do
    def log(level, metadata \\ []) do
      Logger.log(level, "ok", metadata)
    end
  end

  assert capture_log(fn ->
           assert SampleNoApp.log(:info) == :ok
         end) =~ msg("application=sample_app module=LoggerTest.SampleApp [info]  ok")

  assert capture_log(fn ->
           assert SampleNoApp.log(:debug) == :ok
         end) == ""
end
```

Is it ok or it's better to update some existing test (e.g., `remove unused calls at compile time based on matching metadata`)?

**Comment by josevalim** [comment]
We can augment the existing test to consider more scenarios, yes. For example by adding more function calls. That's totally fine.
