### ISSUE TITLE
Compile error when using unquote on a module

### ISSUE THREAD

**Issue by andrewtimberlake** [elixir-lang/elixir#8588]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.8.0-rc.0 and Erlang 21.2.2
* Operating system: MacOS latest

### Current behavior
compile_test.ex
```elixir
defmodule Other do
  def foo do
    :foo
  end

  def bar do
    :bar
  end
end

defmodule CompileTest do
  [:foo, :bar]
  |> Enum.each(fn name ->
    def unquote(name)() do
      Other.unquote(name)()
    end
  end)
end
```

compile_test_test.exs
```elixir
defmodule CompileTestTest do
  use ExUnit.Case
  doctest CompileTest

  test "it works" do
    assert CompileTest.foo() == :foo
    assert CompileTest.bar() == :bar
  end
end
```

Results in
```bash
Compiling 1 file (.ex)

== Compilation error in file lib/compile_test.ex ==
** (CompileError) lib/compile_test.ex:15: invalid call Other.unquote(name)()
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    lib/compile_test.ex:13: (module)
```

### Expected behavior

`CompileTest.foo()` should call `Other.foo()` and return `:foo`

**Comment by michalmuskala** [comment]
As a clarification - this used to work correctly, it's a regression in 1.8 and current master.

**Comment by josevalim** [comment]
I have a fix which I will push soon. :)
