### ISSUE TITLE
Compliation error when using case inside with

### ISSUE THREAD

**Issue by michaelm244** [elixir-lang/elixir#8717]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.8.0 (compiled with Erlang/OTP 20)
```

* Operating system: OS-X

### Current behavior

If you execute:
```
with :ok <- case :ok do
      :ok -> :ok
    end
do
  :ok
end
```

You get:
```
** (SyntaxError) test.exs:4: syntax error before: do
    (elixir) lib/code.ex:767: Code.require_file/2
```

### Expected behavior

I expect this to compile. I have found that if I add parentheses around the `case`, it works:
```
with :ok <- (case :ok do
      :ok -> :ok
    end)
do
  :ok
end
```

It took me a long time to find the source of this error in a large `with` chain because the error message isn't very descriptive and always cites the line number of the `do` for the `with` block rather than the exact line of the offending `case`.

Happy to have a discussion on what the best way to handle this is.

**Comment by NickNeck** [comment]
I think this behaviour is correct. The `with` expected a function and will interpret the `case :ok` as the function given to `with`. The `do` block is then a part of the `with` and the second `do` block is isolated and cause the syntax error. But I am not sure if I am right.
