### ISSUE TITLE
Releases: Failing text plus warnings

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8735]
It is failing every single time.

```console
==> mix (ex_unit)
Excluding tags: [windows: true]

........................................................................................................................................................................../home/eksperimental/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test executes rpc instructions/_build/dev/rel/permanent1/releases/0.1.0/elixir: 189: [: unexpected operator
.../home/eksperimental/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test assembles a custom release/demo/releases/0.2.0/elixir: 189: [: unexpected operator
./home/eksperimental/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test assembles a bootable release with ERTS/_build/dev/rel/release_test/releases/0.1.0/elixir: 189: [: unexpected operator
./home/eksperimental/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test runs in daemon mode/_build/dev/rel/permanent2/releases/0.1.0/elixir: 189: [: unexpected operator


  1) test runs in daemon mode (Mix.Tasks.ReleaseTest)
     /home/eksperimental/elixir/lib/mix/test/mix/tasks/release_test.exs:147
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:
     
       1. per test by setting "@tag timeout: x"
       2. per case by setting "@moduletag timeout: x"
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. or set it to infinity per run by calling "mix test --trace"
          (useful when using IEx.pry/0)
     
     Timeouts are given as integers in milliseconds.
     
     stacktrace:
       (elixir) lib/process.ex:253: Process.sleep/1
       test/mix/tasks/release_test.exs:216: Mix.Tasks.ReleaseTest.wait_until_evaled/1
       test/mix/tasks/release_test.exs:157: anonymous fn/1 in Mix.Tasks.ReleaseTest."test runs in daemon mode"/1
       (mix) lib/mix/project.ex:348: Mix.Project.in_project/4
       (elixir) lib/file.ex:1536: File.cd!/2
       test/test_helper.exs:124: MixTest.Case.in_fixture/3
       test/mix/tasks/release_test.exs:148: (test)
       (ex_unit) lib/ex_unit/runner.ex:355: ExUnit.Runner.exec_test/1
       (stdlib) timer.erl:166: :timer.tc/1
       (ex_unit) lib/ex_unit/runner.ex:306: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4

.............................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 218.3 seconds (6.4s on load, 211.9s on tests)
9 doctests, 580 tests, 1 failure
```

**Comment by josevalim** [comment]
Fixed in master already. :) Sorry for the hiccup.

**Comment by josevalim** [comment]
Eh, I forgot to push. That's why it was not fixed in master. Sorry, pushed now.

**Comment by eksperimental** [comment]
Great. Thank you

**Comment by eksperimental** [comment]
This is happening randomly, same kind of error

https://travis-ci.org/elixir-lang/elixir/jobs/487069352#L500

```
  1) test executes rpc instructions (Mix.Tasks.ReleaseTest)
     /home/travis/build/elixir-lang/elixir/lib/mix/test/mix/tasks/release_test.exs:121
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:
     
       1. per test by setting "@tag timeout: x"
       2. per case by setting "@moduletag timeout: x"
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. or set it to infinity per run by calling "mix test --trace"
          (useful when using IEx.pry/0)
     
     Timeouts are given as integers in milliseconds.
     
     stacktrace:
       (elixir) lib/process.ex:253: Process.sleep/1
       test/mix/tasks/release_test.exs:222: Mix.Tasks.ReleaseTest.wait_until/1
       test/mix/tasks/release_test.exs:130: anonymous fn/1 in Mix.Tasks.ReleaseTest."test executes rpc instructions"/1
       (mix) lib/mix/project.ex:348: Mix.Project.in_project/4
       (elixir) lib/file.ex:1536: File.cd!/2
       test/test_helper.exs:124: MixTest.Case.in_fixture/3
       test/mix/tasks/release_test.exs:122: (test)
       (ex_unit) lib/ex_unit/runner.ex:355: ExUnit.Runner.exec_test/1
       (stdlib) timer.erl:166: :timer.tc/1
       (ex_unit) lib/ex_unit/runner.ex:306: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4
warning: redefining module ReleaseTest.MixProject (current version defined in memory)
  /home/travis/build/elixir-lang/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test requires confirmation if release already exists unless forcing/mix.exs:1
warning: redefining module ReleaseTest (current version loaded from /home/travis/build/elixir-lang/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test executes rpc instructions/_build/dev/lib/release_test/ebin/Elixir.ReleaseTest.beam)
  lib/release_test.ex:1
```
