### ISSUE TITLE
Two more tests failing

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8738]
These have happened more than 5 times as I am working on the new POSIX complaint PR. I would say it is not related to the changes introduced, but I cannot assure that.

```==> mix (ex_unit)
Excluding tags: [windows: true]

..........................................................................................................................................................................

  1) test runs in daemon mode (Mix.Tasks.ReleaseTest)
     test/mix/tasks/release_test.exs:147
     Assertion with =~ failed
     code:  assert File.read!(Path.join(root, "tmp/log/erlang.log.1")) =~ :erlang.system_info(:system_version) |> List.to_string() |> String.trim()
     left:  "\n=====\n===== LOGGING STARTED Wed Jan 30 04:27:44 WIB 2019\n=====\n"
     right: "Erlang/OTP 21 [erts-10.0.5] [source] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]"
     stacktrace:
       test/mix/tasks/release_test.exs:171: anonymous fn/1 in Mix.Tasks.ReleaseTest."test runs in daemon mode"/1
       (mix) lib/mix/project.ex:348: Mix.Project.in_project/4
       (elixir) lib/file.ex:1536: File.cd!/2
       test/test_helper.exs:124: MixTest.Case.in_fixture/3
       test/mix/tasks/release_test.exs:148: (test)

epmd: Wed Jan 30 04:27:47 2019: node name already occupied release_test
Protocol 'inet_tcp': the name release_test@127.0.0.1 seems to be in use by another Erlang node


  2) test assembles a bootable release with ERTS (Mix.Tasks.ReleaseTest)
     test/mix/tasks/release_test.exs:8
     Assertion with == failed
     code:  assert System.cmd(Path.join(root, "bin/start"), []) == {"", 0}
     left:  {"", 1}
     right: {"", 0}
     stacktrace:
       test/mix/tasks/release_test.exs:40: anonymous fn/1 in Mix.Tasks.ReleaseTest."test assembles a bootable release with ERTS"/1
       (mix) lib/mix/project.ex:348: Mix.Project.in_project/4
       (elixir) lib/file.ex:1536: File.cd!/2
       test/test_helper.exs:124: MixTest.Case.in_fixture/3
       test/mix/tasks/release_test.exs:9: (test)

.................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 170.5 seconds (5.2s on load, 165.3s on tests)
9 doctests, 580 tests, 2 failures
```

**Comment by josevalim** [comment]
@eksperimental the second test may be because of your changes. To be sure, make sure you kill any "beam.smp" instances before running the suite.
