### ISSUE TITLE
compiler: handle "sequential" matches

### ISSUE THREAD

**Issue by fenollp** [elixir-lang/elixir#8867]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
* Operating system: 

### Current behavior

```elixir
  def on_msg(payload, %{
        app_id: app,
        exchange: "odds_notification",
        delivery_tag: _tag,
        priority: :undefined,
        redelivered: false,
        routing_key: key
      })
      when is_binary(payload) and app in ["dispatcher", "tangerine"] and
             key in ["#{app}.market"] do
    {:ok, notif} = payload |> Jason.decode!() |> Notif.from_json()
    on_notif(notif)
    :ack
  end
```

### Expected behavior

Compile & have clause match when `(app=dispatcher andalso key=dispatcher.market) orelse (app=tangerine andalso key=tangerine.market)`.

### Actual behavior

```erlang
Compiling 1 file (.ex)
Function: on_msg/2

== Compilation error in file lib/heimdall.ex ==
** (CompileError) lib/heimdall.ex: internal error in v3_codegen;
crash reason: {case_clause,
    {'EXIT',
        {{badmatch,
             {k_remote,[],
                 {k_atom,
                     [37,{file,"lib/heimdall.ex"},compiler_generated],
                     'Elixir.String.Chars'},
                 {k_atom,
                     [37,{file,"lib/heimdall.ex"},compiler_generated],
                     to_string},
                 1}},
         [{v3_codegen,call_cg,7,[{file,"v3_codegen.erl"},{line,1680}]},
          {v3_codegen,'-cg_list/4-anonymous-0-',3,
              [{file,"v3_codegen.erl"},{line,528}]},
          {v3_codegen,flatmapfoldl,3,[{file,"v3_codegen.erl"},{line,2839}]},
          {v3_codegen,cg_list,4,[{file,"v3_codegen.erl"},{line,527}]},
          {v3_codegen,cg_block,4,[{file,"v3_codegen.erl"},{line,816}]},
          {v3_codegen,block_cg,4,[{file,"v3_codegen.erl"},{line,777}]},
          {v3_codegen,match_cg,4,[{file,"v3_codegen.erl"},{line,645}]},
          {v3_codegen,guard_match_cg,6,
              [{file,"v3_codegen.erl"},{line,623}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
  in call from compile:fold_comp/4 (compile.erl, line 376)
  in call from compile:internal_comp/5 (compile.erl, line 360)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from elixir_erl_compiler:compile/4 (src/elixir_erl_compiler.erl, line 52)
  in call from elixir_erl:load_form/5 (src/elixir_erl.erl, line 439)
  in call from elixir_erl_compiler:'-spawn/2-fun-0-'/3 (src/elixir_erl_compiler.erl, line 12)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

And using `key == "#{app}.market" instead:

```erlang
Compiling 1 file (.ex)
Function: on_msg/2

== Compilation error in file lib/heimdall.ex ==
** (CompileError) lib/heimdall.ex: internal error in v3_codegen;
crash reason: {case_clause,
    {'EXIT',
        {{badmatch,
             {k_remote,[],
                 {k_atom,
                     [37,{file,"lib/heimdall.ex"},compiler_generated],
                     'Elixir.String.Chars'},
                 {k_atom,
                     [37,{file,"lib/heimdall.ex"},compiler_generated],
                     to_string},
                 1}},
         [{v3_codegen,call_cg,7,[{file,"v3_codegen.erl"},{line,1680}]},
          {v3_codegen,'-cg_list/4-anonymous-0-',3,
              [{file,"v3_codegen.erl"},{line,528}]},
          {v3_codegen,flatmapfoldl,3,[{file,"v3_codegen.erl"},{line,2839}]},
          {v3_codegen,cg_list,4,[{file,"v3_codegen.erl"},{line,527}]},
          {v3_codegen,cg_block,4,[{file,"v3_codegen.erl"},{line,816}]},
          {v3_codegen,block_cg,4,[{file,"v3_codegen.erl"},{line,777}]},
          {v3_codegen,match_cg,4,[{file,"v3_codegen.erl"},{line,645}]},
          {v3_codegen,guard_match_cg,6,
              [{file,"v3_codegen.erl"},{line,623}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
  in call from compile:fold_comp/4 (compile.erl, line 376)
  in call from compile:internal_comp/5 (compile.erl, line 360)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from elixir_erl_compiler:compile/4 (src/elixir_erl_compiler.erl, line 52)
  in call from elixir_erl:load_form/5 (src/elixir_erl.erl, line 439)
  in call from elixir_erl_compiler:'-spawn/2-fun-0-'/3 (src/elixir_erl_compiler.erl, line 12)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by ericmj** [comment]
The bug seems to be that string interpolation expands incorrectly in guard expression. We should do the same expansion as we do in match expressions.

You can work around the issue by doing the expansion manually: `key in [app <> ".market"]`.

**Comment by josevalim** [comment]
There are two fixes to be done here. One in the <<>> macro and potentially another in the compiler that should have detected this and raised early.

**Comment by fertapric** [comment]
I’m currently working on this one.

**Comment by fertapric** [comment]
With #8905, the compiler will raise when using string interpolations in guards. That should solve one of two fixes mentioned.

However, I think string interpolations in the form of `"#{arg} string"` should raise, because it implies calling the `String.Chars` protocol. If we make it work for some cases, users might expect this to work:

```elixir
defmodule Foo do
  def foo(a, b) when a in ["#{b}.market"] do
    a
  end
end

Foo.foo("1.market", 1)
```

**Comment by josevalim** [comment]
Closing in favor of the PR.

**Comment by fenollp** [comment]
Cool! I agree it should raise. I think the compiler should emit a suggestion as well when it has deduced that `b` can only be a binary:

> Function calls are not allowed in guard patterns (`String.Chars` called)
> However you can use this pattern: `when a in [b <> ".market"]`

or something of this kind.
Thanks
