### ISSUE TITLE
Lexical scoping of `with` statement in console

### ISSUE THREAD

**Issue by virtual-light** [elixir-lang/elixir#8902]
### Environment

Elixir 1.8.1 (compiled with Erlang/OTP 21)
Linux phoenix 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 GNU/Linux

```
$ iex

Erlang/OTP 21 [erts-10.2.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> a = %{a: 1, b: 2}
%{a: 1, b: 2}
iex(2)> r = with %{a: v, b: 2} <- a, 2 <- 1 do "lol" else _ -> v end
warning: variable "v" is unused (if the variable is not meant to be used, prefix it with an underscore)
  iex:2

%{a: 1, b: 2}
iex(3)> p = [a: "b"]                                                
[a: "b"]
iex(4)> r = with %{a: v, b: 2} <- a, 2 <- 1 do "lol" else _ -> v end
warning: variable "v" is unused (if the variable is not meant to be used, prefix it with an underscore)
  iex:4

[a: "b"]
```

The same with module declaration:

```
iex(8)> defmodule Test do
...(8)>   def run do
...(8)>     a = %{a: 1, b: 2}
...(8)>     with %{a: v, b: 2} <- a, 2 <- 1 do "lol" else _val -> v end
...(8)>   end
...(8)> end
warning: variable "v" is unused (if the variable is not meant to be used, prefix it with an underscore)
  iex:11

warning: variable "v" does not exist and is being expanded to "v()", please use parentheses to remove the ambiguity or change the variable name
  iex:11

{:module, Test,
 <<70, 79, 82, 49, 0, 0, 4, 244, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 151,
   0, 0, 0, 17, 15, 69, 108, 105, 120, 105, 114, 46, 69, 121, 114, 46, 84, 101,
   115, 116, 8, 95, 95, 105, 110, 102, 111, ...>>, {:run, 0}}

Test.run
{:module, Test,
 <<70, 79, 82, 49, 0, 0, 4, 244, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 151,
   0, 0, 0, 17, 15, 69, 108, 105, 120, 105, 114, 46, 69, 121, 114, 46, 84, 101,
   115, 116, 8, 95, 95, 105, 110, 102, 111, ...>>, {:run, 0}}

```

### Current behavior

Looks like scoping is broken. This error happens only in console. 
When trying to compile `.ex` file that contains this code it crashes with error:

```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Compiling 18 files (.ex)
warning: variable "v" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/text.ex:4

warning: variable "v" does not exist and is being expanded to "v()", please use parentheses to remove the ambiguity or change the variable name
  lib/text.ex:4


== Compilation error in file lib/text.ex ==
** (CompileError) lib/text.ex:4: undefined function v/0
    (elixir) src/elixir_locals.erl:107: :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2 
    (elixir) src/elixir_locals.erl:108: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

```

### Expected behavior
Accessing from the `error` block to the variable declared  in the `with` block should raise with: `undefined function v/0`

**Comment by fertapric** [comment]
@virtual-light IEx helpers are included by default in the IEx session, being `v/0` one of them. `v` is expanded to `v()` which retrieves the last value from the history.

If the `v` variable is replaced with `vv` everything works as expected:

```elixir
iex(1)> a = %{a: 1, b: 2}
%{a: 1, b: 2}
iex(2)> with %{a: vv, b: 2} <- a, 2 <- 1 do "lol" else _ -> vv end
warning: variable "vv" is unused (if the variable is not meant to be used, prefix it with an underscore)
  iex:2

** (CompileError) iex:2: undefined function vv/0
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
```
