### ISSUE TITLE
Logger fails trying to translate error, crashes Logger

### ISSUE THREAD

**Issue by brainlid** [elixir-lang/elixir#9008]
### Environment

* Elixir & Erlang/OTP versions: 1.8.1, OTP 21
* Operating system: Arch Linux

### Current behavior

I'm encountering an error with Cowboy but it is crashing the system with a Logger error.

```
[error] Process #PID<0.82.0> raised an exception
** (ArgumentError) argument error
    :erlang.monitor(:process, {:error, {:undef, [{IEx.Evaluator, :init, [:ack, #PID<0.82.0>, #PID<0.65.0>, [dot_iex_path: nil]], []}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}})
    (iex) lib/iex/server.ex:46: IEx.Server.run_without_registration/1
[debug] Failure while translating Erlang's logger event
** (UndefinedFunctionError) function Plug.Cowboy.Translator.translate/4 is undefined or private
    (plug_cowboy) Plug.Cowboy.Translator.translate(:debug, :debug, :report, {:logger, [logger: :remove_handler_failed, reason: {:attempting_syncronous_call_to_self, {:remove_handler, Logger}}]})
    (logger) lib/logger/erlang_handler.ex:104: Logger.ErlangHandler.translate/6
    (logger) lib/logger/erlang_handler.ex:97: Logger.ErlangHandler.translate/5
    (logger) lib/logger/erlang_handler.ex:33: anonymous fn/3 in Logger.ErlangHandler.log/2
    (logger) lib/logger.ex:867: Logger.normalize_message/2
    (logger) lib/logger.ex:690: Logger.__do_log__/3
    (kernel) logger_backend.erl:51: :logger_backend.call_handlers/3
    (kernel) logger_backend.erl:38: :logger_backend.log_allowed/2

[error] Failure while translating Erlang's logger event
** (UndefinedFunctionError) function Plug.Cowboy.Translator.translate/4 is undefined or private
    (plug_cowboy) Plug.Cowboy.Translator.translate(:debug, :error, :report, {{:erl_prim_loader, :file_error}, 'File operation error: emfile. Target: /home/mark/client/_build/dev/lib/jason/ebin/Elixir.Jason.Encode.beam. Function: get_file. Process: code_server.'})
    (logger) lib/logger/erlang_handler.ex:104: Logger.ErlangHandler.translate/6
    (logger) lib/logger/erlang_handler.ex:97: Logger.ErlangHandler.translate/5
    (logger) lib/logger/erlang_handler.ex:27: anonymous fn/3 in Logger.ErlangHandler.log/2
    (logger) lib/logger.ex:867: Logger.normalize_message/2
    (logger) lib/logger.ex:690: Logger.__do_log__/3
    (kernel) logger_backend.erl:51: :logger_backend.call_handlers/3
    (kernel) logger_backend.erl:38: :logger_backend.log_allowed/2
    (kernel) logger_server.erl:351: :logger_server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

The result is that Logger is stopped.

```
Logger - error: {removed_failing_handler,'Elixir.Logger'}
```

**Comment by josevalim** [comment]
Thanks @brainlid. can you please provide a sample app that reproduces the error? The root cause seems to be that a certain module is being added as a translator but it does not exist.

**Comment by brainlid** [comment]
This is 2 new phoenix applications. Created to try and load test a server. So the client is not a "real" client, it intentionally opens many sockets to the server. I believe this is a problem with Cowboy, but it's escalating the crash in an unexpected way.

- Start `server`: `iex -S mix phx.server`
- Start `client`: `iex -S mix phx.server`

The problem only shows up when the `client/config/config.exs` has the setting:

```
config :client, :fake_device_count, 1000
```
Or higher. I just tried it again with the zip file and I had to raise the count to 2000 to re-create the problem.

The error happens in the client app.

[client-server-test.zip](https://github.com/elixir-lang/elixir/files/3138279/client-server-test.zip)

**Comment by josevalim** [comment]
So what is happening is that you are running out of file descriptors. Then an error happens because of that and Logger attempts to log it. But in order to log it, it needs to load some .beam from disk, but you are out of file descriptors, which makes thing cascade. Increase your file descriptors limit and everything should be good to go!

**Comment by brainlid** [comment]
Wow. Thanks for the help!
