### ISSUE TITLE
Inconsistent filenames in stacktraces after consolidation

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#9095]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): latest master
* Operating system: macos

### Current behavior

Inside of any mix project:
```
$ iex
iex(1)> Enum.map(1, 1)
** (Protocol.UndefinedError) protocol Enumerable not implemented for 1 of type Integer
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3023: Enum.map/2
```

```
$ iex -S mix
iex(1)> Enum.map(1, 1)
** (Protocol.UndefinedError) protocol Enumerable not implemented for 1 of type Integer. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
    (elixir) /Users/michalmuskala/src/oss/elixir/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /Users/michalmuskala/src/oss/elixir/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3023: Enum.map/2
```

### Expected behavior

The stacktrace entry should be the same in both cases

**Comment by josevalim** [comment]
Closing in favor of #9099.
