### ISSUE TITLE
Formatter fails on sigil definition (Elixir 1.9.0-rc.0

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#9123]
### Environment

Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]
IEx 1.9.0-rc.0 (aad7aa4) (compiled with Erlang/OTP 22)
Mac OS X Mojave

### Current behavior

With the module:
```elixir
defmodule Fmt do
  def sigil_d(<< year :: bytes-4, "-", month :: bytes-2, "-", day :: bytes-2 >>, calendar) do
    ymd(year, month, day, calendar)
  end

  defp ymd(_year, _month, _day, _calendar) do
    :ok
  end
end
```
Running `mix format` produces:
```bash
$ mix format
mix format failed for file: lib/fmt.ex
** (KeyError) key :terminator not found in: [eol: false, end: [line: 2], line: 2]
    (elixir) lib/keyword.ex:393: Keyword.fetch!/2
    (elixir) lib/code/formatter.ex:1370: Code.Formatter.maybe_sigil_to_algebra/4
    (elixir) lib/code/formatter.ex:529: Code.Formatter.quoted_to_algebra/3
    (elixir) lib/code/formatter.ex:1628: anonymous fn/6 in Code.Formatter.args_to_algebra_with_comments/7
    (elixir) lib/code/formatter.ex:1646: Code.Formatter.args_to_algebra_with_comments/7
    (elixir) lib/code/formatter.ex:1197: Code.Formatter.call_args_to_algebra_no_blocks/6
    (elixir) lib/code/formatter.ex:1118: Code.Formatter.call_args_to_algebra/6
    (elixir) lib/code/formatter.ex:1084: Code.Formatter.local_to_algebra/5
```

### Expected behavior

Format the code :-)

**Comment by Eiji7** [comment]
I tried your code and same happens for me. However I have tested it on latest stable releases i.e.:
```bash
$ asdf current
elixir         1.8.2-otp-22 (set by …)
erlang         22.0.1   (set by …)
```
