### ISSUE TITLE
"mix hex.outdated" issue with elixir 1.9

### ISSUE THREAD

**Issue by maxguzenski** [elixir-lang/elixir#9170]
### Environment

Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.9.0 (compiled with Erlang/OTP 22)

macOS

### Current behavior

After update to elixir 1.9 and erlang 22 using "brew upgrade erlang elixir", "mix hex.outdated" doesnt work anymore:

```
** (UndefinedFunctionError) function Mix.Dep.loaded/1 is undefined or private
    (mix) Mix.Dep.loaded([])
    (hex) lib/mix/tasks/hex/outdated.ex:33: Mix.Tasks.Hex.Outdated.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```
### Expected behavior
List outdated dependencies

**Comment by maxguzenski** [comment]
Update hex to the last version fix this issue:

```
mix local.hex
```
