### ISSUE TITLE
make test fails in String.trim_trailing

### ISSUE THREAD

**Issue by norbusan** [elixir-lang/elixir#9173]
Dear all,

I am trying to build Elixir on Debian/unstable (or buster), but the `make test` run fails:
```
...
==> mix (ex_unit)
Excluding tags: [windows: true]

....................................................................................................................................2019-06-28 12:46:04.860137 ~s~n
	

  1) test runs eval and version commands (Mix.Tasks.ReleaseTest)
     test/mix/tasks/release_test.exs:288
     Assertion with == failed
     code:  assert String.trim_trailing(hello_world) == "hello_world"
     left:  "\"#Port<0.4>: <unknown>:  driver gone away without deselecting!\\n\"\r\n=ERROR REPORT==== 28-Jun-2019::12:46:04.860137 ===\n#Port<0.4>: <unknown>:  driver gone away without deselecting!\n\n\nhello_world"
     right: "hello_world"
     stacktrace:
       test/mix/tasks/release_test.exs:311: anonymous fn/1 in Mix.Tasks.ReleaseTest."test runs eval and version commands"/1
       (mix) lib/mix/project.ex:352: Mix.Project.in_project/4
       (elixir) lib/file.ex:1542: File.cd!/2
       test/test_helper.exs:119: MixTest.Case.in_fixture/3
       test/mix/tasks/release_test.exs:293: (test)

......2019-06-28 12:46:10.205809 ~s~n
	..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 58.9 seconds (1.8s on load, 57.1s on tests)
9 doctests, 620 tests, 1 failure

Randomized with seed 464170
make: *** [Makefile:113: test_mix] Error 1
```

### Environment

* Current Elixir is 1.8.1 
```
$ elixir --version
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.8.2 (compiled with Erlang/OTP 21)
```

* Operating system: Linux (Debian/unstable)

**Comment by josevalim** [comment]
Hi @norbusan! The "driver gone away without deselecting" is a bug in Erlang/OTP, so if you upgrade accordingly, it should go away. Thanks for the report. :+1:

**Comment by norbusan** [comment]
@josevalim Thanks, indeed, pushing Erlang to 22 fixed that. Sorry for the noise!
