### ISSUE TITLE
Running `mix` returns warning :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead

### ISSUE THREAD

**Issue by dopatraman** [elixir-lang/elixir#9416]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.0-dev (553b2b2) (compiled with Erlang/OTP 22)
```
* Operating system: 
Ubuntu 16.04

### Current behavior
I ran `mix ecto.setup` on a machine twice -- the setup worked properly but now everytime I enter the `mix` command in my terminal, I see this output:
```
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0-dev) lib/supervisor.ex:612: Supervisor.init/2
  (elixir 1.10.0-dev) lib/supervisor.ex:564: Supervisor.start_link/2
  (phoenix 1.4.8) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.10) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.10) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.10) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.10) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.10) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0-dev) lib/supervisor.ex:612: Supervisor.init/2
  (elixir 1.10.0-dev) lib/supervisor.ex:564: Supervisor.start_link/2
  (phoenix 1.4.8) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.10) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.10) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.10) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.10) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.10) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0-dev) lib/supervisor.ex:612: Supervisor.init/2
  (elixir 1.10.0-dev) lib/supervisor.ex:564: Supervisor.start_link/2
  (phoenix 1.4.8) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.10) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.10) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.10) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.10) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.10) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.10) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### Expected behavior
This behavior doesn't seem to be breaking anything, but it is strange. Why is this happening?

**Comment by josevalim** [comment]
Phoenix/Ecto are using deprecated features. The warning is OK, but they should eventually update their code. Typically the warnings are addressed in their master version. So if you are using Elixir master, consider using Phoenix master too.

**Comment by zairecrypto** [comment]
> So if you are using Elixir master, consider using Phoenix master too.

Can you explain what we have to change in the code or how to run Phoenix master?

Also, is it going to be a problem when the project is uploaded on production?

**Comment by connorjacobsen** [comment]
In your `mix.exs`, instead of:

```elixir
{:phoenix, "~> 1.5.1"}
```

You would want something like:

```elixir
{:phoenix, github: "phoenixframework/phoenix", branch: "master"}
```

You could also use `ref` or `tag` to pin the commit/tag you want to depend on that way new commits won't break your code.
