### ISSUE TITLE
Mix compile errors at :unicode.characters_to_binary/1

### ISSUE THREAD

**Issue by kanes115** [elixir-lang/elixir#9908]
# Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.9.4 (compiled with Erlang/OTP 22)
```
Erlang and elixir installed with `asdf`.

* Operating system: MacOS Catalina 10.15.3

### Current behavior

I try to compile the following file. 
```
defmodule Foo do

  defmacrop baz(pattern) do
    quote do
        fn
          <<unquote(pattern), rest::bitstring>> -> :ok
        end
    end
  end

  def foo, do: baz(<<value::bitstring>>)
end

```

I get an error:
```
== Compilation error in file schema.ex ==
** (ArgumentError) argument error
    (stdlib) :unicode.characters_to_binary(Foo)
    (elixir) src/elixir_utils.erl:121: :elixir_utils.characters_to_binary/1
    (elixir) src/elixir_erl_compiler.erl:74: anonymous fn/1 in :elixir_erl_compiler.format_errors/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
** (CompileError)  compile error
    (iex) lib/iex/helpers.ex:200: IEx.Helpers.c/2
```

I was suspecting #9801 [erlang-issue](https://bugs.erlang.org/browse/ERL-1163?jql=project%20%3D%20ERL%20AND%20fixVersion%20%3D%20OTP-22.2.7) to be the cause but I tried the newest erlang 22 versions.

### Expected behaviour

It should result in compile error such as this:
```
== Compilation error in file schema.ex ==
** (CompileError) schema.ex:11: a binary field without size is only allowed at the end of a binary pattern and never allowed in binary generators
    (elixir) src/elixir_bitstring.erl:173: :elixir_bitstring.expand_specs/6
    (elixir) src/elixir_bitstring.erl:41: :elixir_bitstring.expand/8
    (elixir) src/elixir_bitstring.erl:10: :elixir_bitstring.expand/4
    (elixir) src/elixir_fn.erl:14: anonymous fn/4 in :elixir_fn.expand/3
    expanding macro: Foo.baz/1
** (CompileError)  compile error
    (iex) lib/iex/helpers.ex:200: IEx.Helpers.c/2
```

**Comment by josevalim** [comment]
Can you please provide a link to the project?

**Comment by kanes115** [comment]
@josevalim I have added it to the description (https://github.com/membraneframework/membrane-element-mp4).

**Comment by kanes115** [comment]
It actually is enough to comment out function `parse_field/1` and it is compiled without errors.

**Comment by kanes115** [comment]
```
iex(26)> :dbg.tp(:elixir_erl_compiler, :format_errors, :x)
{:ok, [{:matched, :nonode@nohost, 0}, {:saved, :x}]}
iex(27)> :dbg.tpl(:elixir_erl_compiler, :format_errors, :x)
{:ok, [{:matched, :nonode@nohost, 1}, {:saved, :x}]}
iex(28)> :dbg.p(:all, :c)
{:ok, [{:matched, :nonode@nohost, 56}]}
```

yields:
```
(<0.175.0>) call elixir_erl_compiler:format_errors([{'Elixir.Membrane.Element.MP4.Schema.Spec',
     [{none,core_lint,{tail_segment_not_at_end,{parse_field,1}}}]}])
(<0.175.0>) exception_from {elixir_erl_compiler,format_errors,1} {error,badarg}
```

And I found an appropriate line in erlang linter describing the error:
```
format_error({tail_segment_not_at_end,{F,A}}) ->
      io_lib:format("binary tail segment not at end in ~w/~w", [F,A]).
```

It looks like there is an error in the code syntax that elixir compiler struggles to print out.

**Comment by josevalim** [comment]
I can't use the linked repo because it depends on private github repos. :) Since you have already done a great job isolating the error, can you please provide a minimal elixir code snippet that reproduces it? Thanks!

**Comment by kanes115** [comment]
The description was edited to contain minimal working example.

**Comment by mat-hek** [comment]
While playing with this I noticed a weird behaviour:
```elixir
iex(2)> <<(<<value::bitstring>>), rest::bitstring>> = <<1,2,3>>
<<1, 2, 3>>
iex(3)> value
<<1, 2, 3>>
iex(4)> rest
""
```

> Erlang/OTP 22 [erts-10.5.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
> Elixir 1.9.4 (compiled with Erlang/OTP 22)
