### ISSUE TITLE
IEx.configure/1 crashing on what is perhaps an invalid option

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#9959]
### Environment

```
$ elixir --version
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 22)
```

### Current behavior

This happened to me, and probably someone might know or guess what happened.

```
iex(60)> IEx.configure(width: :infinity)
** (exit) exited in: GenServer.call(IEx.Config, {:update, {IEx.Config, :handle_configure, [[width: :infinity]]}}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) invalid configuration or value for pair :width - :infinity
            (iex) lib/iex/config.ex:183: IEx.Config.merge_option/3
            (elixir) lib/keyword.ex:780: Keyword.do_merge/6
            (iex) lib/iex/config.ex:163: IEx.Config.handle_configure/2
            (elixir) lib/agent/server.ex:23: Agent.Server.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:1009: GenServer.call/3
iex(60)>
nil
iex(61)>
nil
iex(62)>
nil
iex(63)> IEx.configure(width: :infinity)
** (exit) exited in: GenServer.call(IEx.Config, {:update, {IEx.Config, :handle_configure, [[width: :infinity]]}}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) invalid configuration or value for pair :width - :infinity
            (iex) lib/iex/config.ex:183: IEx.Config.merge_option/3
            (elixir) lib/keyword.ex:780: Keyword.do_merge/6
            (iex) lib/iex/config.ex:163: IEx.Config.handle_configure/2
            (elixir) lib/agent/server.ex:23: Agent.Server.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:1009: GenServer.call/3
iex(63)>
nil
iex(64)>
nil
iex(65)>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C$ MIX_ENV=test iex -S mix
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> IEx.configure(width: :infinity)
:ok
iex(2)>
```

This is reproducible as stated in the following comment.

**Comment by mguimas** [comment]
On a fresh IEx session this happens, and is reproducible:

```
Interactive Elixir (1.9.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> IEx.configure(width: :infinity)
:ok
iex(2)> IEx.configure(width: :infinity)

21:50:47.394 [error] GenServer IEx.Config terminating
** (ArgumentError) invalid configuration or value for pair :width - :infinity
    (iex) lib/iex/config.ex:183: IEx.Config.merge_option/3
    (elixir) lib/keyword.ex:780: Keyword.do_merge/6
    (iex) lib/iex/config.ex:163: IEx.Config.handle_configure/2
    (elixir) lib/agent/server.ex:23: Agent.Server.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.369.0>): {:update, {IEx.Config, :handle_configure, [[width: :infinity]]}}
State: IEx.Config
Client #PID<0.369.0> is alive

    (stdlib) gen.erl:167: :gen.do_call/4
    (elixir) lib/gen_server.ex:1006: GenServer.call/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:275: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
** (exit) exited in: GenServer.call(IEx.Config, {:update, {IEx.Config, :handle_configure, [[width: :infinity]]}}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) invalid configuration or value for pair :width - :infinity
            (iex) lib/iex/config.ex:183: IEx.Config.merge_option/3
            (elixir) lib/keyword.ex:780: Keyword.do_merge/6
            (iex) lib/iex/config.ex:163: IEx.Config.handle_configure/2
            (elixir) lib/agent/server.ex:23: Agent.Server.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:1009: GenServer.call/3
iex(2)>
```

**Comment by mguimas** [comment]
The happens because the agent is crashing due to the function [merge_option/3](https://github.com/elixir-lang/elixir/blob/1a2f5e582854b9ad4fc5112a5226f9c62bdecb52/lib/iex/lib/iex/config.ex#L199)

I don't know if this is the desired behavior or not, however it seems ugly seeing this happening in IEx.

**Comment by ericmj** [comment]
It is not documented to be a valid option per https://hexdocs.pm/iex/IEx.html#configure/1-width. Maybe we should add support for it but I am not sure that would work since `:io.columns/0` is not guaranteed to work and I don't think anyone want infinite width lines.

**Comment by mguimas** [comment]
I discovered this issue by accident while trying to type this other valid option
```
iex(35)>  IEx.configure(inspect: [width: :infinity])
:ok
iex(36)>  IEx.configure(inspect: [width: :infinity])
:ok
```
I do not know if these two `width` are related or not, but at least this one is documented to accept `:infinity` (see `h Inspect.Opts`).

**Comment by ericmj** [comment]
`inspect` does not fall back on `:io.columns` and does not look terrible when rendered with infinite width. But things like `IO.ANSI.Docs`, which uses the IEx width option, would be broken when rendered with infinite width.
